import { createHash } from 'node:crypto';
import { BUSINESS_OBJECT_CATALOG } from '../../agent/knowledge/business-object.catalog.js';
import type { BusinessActionIntent, BusinessObjectDefinition } from '../../agent/knowledge/knowledge.types.js';
import type { AgentV2CapabilityManifest } from '../capability/agent-v2-capability.types.js';
import type {
  BuildAgentV2KnowledgeGraphInput,
  KnowledgeGraphCoverageReport,
  KnowledgeGraphEdge,
  KnowledgeGraphEdgeType,
  KnowledgeGraphGap,
  KnowledgeGraphManualOverrideMergeDetail,
  KnowledgeGraphManualOverrideSource,
  KnowledgeGraphNode,
  KnowledgeGraphNodeType,
  KnowledgeGraphSemanticTermSource,
  KnowledgeGraphSnapshot,
  KnowledgeGraphSource,
  KnowledgeGraphSummary,
} from './knowledge-graph.types.js';

type PrismaField = {
  name: string;
  rawType: string;
  type: string;
  attributes: string;
  optional: boolean;
  list: boolean;
  id: boolean;
  unique: boolean;
  indexed: boolean;
  relation: boolean;
};

type PrismaModel = {
  name: string;
  fields: PrismaField[];
  indexes: string[][];
};

type GraphAccumulator = {
  nodes: Map<string, KnowledgeGraphNode>;
  edges: Map<string, KnowledgeGraphEdge>;
};

const SCALAR_TYPES = new Set(['String', 'Int', 'BigInt', 'Float', 'Decimal', 'Boolean', 'DateTime', 'Json', 'Bytes', 'Unsupported']);

const NODE_TYPES: KnowledgeGraphNodeType[] = [
  'Domain',
  'BusinessObject',
  'DataModel',
  'Field',
  'Capability',
  'ActionIntent',
  'Word',
  'PermissionCode',
];

const EDGE_TYPES: KnowledgeGraphEdgeType[] = [
  'BELONGS_TO',
  'COMPOSED_OF',
  'HAS_FIELD',
  'FK_RELATION',
  'SYNONYM_OF',
  'TRIGGERS',
  'SUPPORTS_ACTION',
  'EXCLUDES',
  'REQUIRES_PERM',
];

const DOMAIN_LABELS: Record<string, string> = {
  business: '经营概览',
  customer: '客户',
  finance: '财务',
  inventory: '库存',
  marketing: '营销',
  order: '订单收银',
  card: '次卡权益',
  memberCard: '会员卡',
  store: '门店',
  terminal: '智能终端',
  industry: '行业供应链',
  automation: '自动化',
  unknown: '未分类',
};

const BUSINESS_OBJECT_DOMAIN: Record<string, string> = {
  MarketingActivity: 'marketing',
  MarketingPage: 'marketing',
  Customer: 'customer',
  InventoryProduct: 'inventory',
  Project: 'store',
  Beautician: 'store',
  StaffEfficiency: 'finance',
  Order: 'order',
  MemberCard: 'card',
  Reservation: 'store',
  Schedule: 'store',
  Supplier: 'industry',
  Terminal: 'terminal',
  Automation: 'automation',
  FinanceMetric: 'finance',
  BusinessOverview: 'business',
  Unknown: 'unknown',
};

const ACTION_INTENTS: BusinessActionIntent[] = [
  'lookup',
  'list',
  'summary',
  'get_link',
  'analyze',
  'diagnose',
  'recommend',
  'compare',
  'draft',
  'confirm_action',
  'print',
];

export function buildAgentV2KnowledgeGraph(input: BuildAgentV2KnowledgeGraphInput): KnowledgeGraphSnapshot {
  const schemaHash = computeSchemaHash(input.schema);
  const models = parsePrismaModels(input.schema);
  const modelNames = new Set(models.map((model) => model.name));
  const graph: GraphAccumulator = { nodes: new Map(), edges: new Map() };

  addDomainNodes(graph, input.generatedAt);
  addActionIntentNodes(graph, input.generatedAt);
  addPrismaNodes(graph, models, modelNames, input);
  addBusinessObjectNodes(graph, BUSINESS_OBJECT_CATALOG, modelNames, input);
  addSemanticTermNodes(graph, input.semanticTerms, input.generatedAt);
  addManifestNodes(graph, input.manifests, modelNames, input);
  addControllerEndpointNodes(graph, input);
  addFrontendRouteNodes(graph, input);
  addManifestExcludeEdges(graph, input.manifests, input.generatedAt);
  const manualOverrideMergeDetails = addManualOverrideEdges(graph, input.manualOverrides ?? [], input.generatedAt);

  const nodes = [...graph.nodes.values()].sort((a, b) => a.id.localeCompare(b.id));
  const edges = [...graph.edges.values()].sort((a, b) => a.id.localeCompare(b.id));
  const summary = buildSummary(input.generatedAt, schemaHash, nodes, edges, input.manifests.length);
  const report = buildCoverageReport(input.generatedAt, schemaHash, summary, nodes, edges, models, input.manifests, input.manualOverrides ?? [], manualOverrideMergeDetails);

  return {
    generatedAt: input.generatedAt,
    schemaHash,
    summary,
    nodes,
    edges,
    report,
  };
}

export function renderKnowledgeGraphGeneratedFile(snapshot: KnowledgeGraphSnapshot) {
  const snapshotJson = JSON.stringify(snapshot);
  const snapshotJsonChunks = chunkString(snapshotJson, 12000);
  return `// Auto-generated by prisma/agent-v2-knowledge-graph.ts. Do not edit manually.
// schemaHash: ${snapshot.schemaHash}
import type { KnowledgeGraphSnapshot } from '../knowledge-graph.types.js';

export const AGENT_V2_KNOWLEDGE_GRAPH_GENERATED_AT = '${snapshot.generatedAt}';

export const AGENT_V2_KNOWLEDGE_GRAPH_SCHEMA_HASH = '${snapshot.schemaHash}';

export const AGENT_V2_KNOWLEDGE_GRAPH_SUMMARY = ${JSON.stringify(snapshot.summary, null, 2)} as const;

const AGENT_V2_KNOWLEDGE_GRAPH_SNAPSHOT_JSON: string = [
${snapshotJsonChunks.map((chunk) => `  ${JSON.stringify(chunk)}`).join(',\n')}
].join('');

export const AGENT_V2_KNOWLEDGE_GRAPH_SNAPSHOT = JSON.parse(AGENT_V2_KNOWLEDGE_GRAPH_SNAPSHOT_JSON) as KnowledgeGraphSnapshot;
`;
}

export function computeSchemaHash(schema: string) {
  return createHash('sha256').update(schema.replace(/\r\n/g, '\n'), 'utf8').digest('hex');
}

export function parsePrismaModels(schema: string): PrismaModel[] {
  const models: PrismaModel[] = [];
  const modelRegex = /^model\s+(\w+)\s+\{([\s\S]*?)^\}/gm;
  let match: RegExpExecArray | null;
  while ((match = modelRegex.exec(schema))) {
    const name = match[1];
    const body = match[2];
    const rawLines = body
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith('//'));
    const indexes = rawLines.filter((line) => line.startsWith('@@')).flatMap(parseModelIndexFields);
    const indexedFields = new Set(indexes.flat());
    const fields = rawLines
      .filter((line) => !line.startsWith('@@'))
      .map(parseFieldLine)
      .filter((field): field is PrismaField => Boolean(field))
      .map((field) => ({ ...field, indexed: field.indexed || indexedFields.has(field.name) }));
    models.push({ name, fields, indexes });
  }
  return models;
}

function addDomainNodes(graph: GraphAccumulator, generatedAt: string) {
  for (const [domain, displayName] of Object.entries(DOMAIN_LABELS)) {
    addNode(graph, {
      id: domainId(domain),
      type: 'Domain',
      name: domain,
      displayName,
      source: 'business_object_catalog',
      confidence: 1,
      updatedAt: generatedAt,
    });
  }
}

function addActionIntentNodes(graph: GraphAccumulator, generatedAt: string) {
  for (const action of ACTION_INTENTS) {
    addNode(graph, {
      id: actionId(action),
      type: 'ActionIntent',
      name: action,
      displayName: action,
      source: 'business_object_catalog',
      confidence: 1,
      updatedAt: generatedAt,
    });
  }
}

function addPrismaNodes(
  graph: GraphAccumulator,
  models: PrismaModel[],
  modelNames: Set<string>,
  input: BuildAgentV2KnowledgeGraphInput,
) {
  for (const model of models) {
    addNode(graph, {
      id: modelId(model.name),
      type: 'DataModel',
      name: model.name,
      displayName: model.name,
      source: 'prisma',
      sourcePath: input.schemaPath,
      confidence: 1,
      updatedAt: input.generatedAt,
      properties: {
        storeScoped: model.fields.some((field) => field.name === 'storeId' || field.type === 'Store'),
        fieldCount: model.fields.length,
        indexCount: model.indexes.length,
      },
    });

    for (const field of model.fields) {
      const fieldNodeId = fieldId(model.name, field.name);
      const relation = modelNames.has(field.type) && !SCALAR_TYPES.has(field.type);
      addNode(graph, {
        id: fieldNodeId,
        type: 'Field',
        name: `${model.name}.${field.name}`,
        displayName: field.name,
        source: 'prisma',
        sourcePath: input.schemaPath,
        confidence: 1,
        updatedAt: input.generatedAt,
        properties: {
          model: model.name,
          type: field.type,
          rawType: field.rawType,
          optional: field.optional,
          list: field.list,
          id: field.id,
          unique: field.unique,
          indexed: field.indexed,
          relation,
          sensitive: isSensitiveField(field.name),
        },
      });
      addEdge(graph, {
        type: 'HAS_FIELD',
        from: modelId(model.name),
        to: fieldNodeId,
        label: field.name,
        source: 'prisma',
        sourcePath: input.schemaPath,
        confidence: 1,
        updatedAt: input.generatedAt,
      });

      if (relation) {
        const relationArgs = parseRelationArgs(field.attributes);
        addEdge(graph, {
          type: 'FK_RELATION',
          from: modelId(model.name),
          to: modelId(field.type),
          label: `${model.name}.${field.name} -> ${field.type}`,
          source: 'prisma',
          sourcePath: input.schemaPath,
          confidence: 1,
          updatedAt: input.generatedAt,
          properties: {
            field: field.name,
            relationType: field.list ? 'one_to_many' : relationArgs.fields.length ? 'many_to_one' : 'one_to_one',
            joinFields:
              relationArgs.fields.length && relationArgs.references.length
                ? relationArgs.fields.map((from, index) => ({ from, to: relationArgs.references[index] ?? 'id' }))
                : [{ from: field.name, to: 'id' }],
            businessMeaning: `Prisma relation: ${model.name}.${field.name} -> ${field.type}`,
          },
        });
      }
    }
  }
}

function addBusinessObjectNodes(
  graph: GraphAccumulator,
  catalog: BusinessObjectDefinition[],
  modelNames: Set<string>,
  input: BuildAgentV2KnowledgeGraphInput,
) {
  for (const item of catalog) {
    const domain = BUSINESS_OBJECT_DOMAIN[item.objectType] ?? 'unknown';
    addNode(graph, {
      id: businessObjectId(item.objectType),
      type: 'BusinessObject',
      name: item.objectType,
      displayName: item.displayName,
      description: item.description,
      source: 'business_object_catalog',
      sourcePath: input.businessObjectCatalogPath,
      confidence: 1,
      updatedAt: input.generatedAt,
      properties: {
        aliases: item.aliases,
        queryableFields: item.queryableFields,
        displayFields: item.displayFields,
        evidenceSourceModels: item.evidenceSourceModels ?? [],
        governanceNote: item.governanceNote,
      },
    });
    addEdge(graph, {
      type: 'BELONGS_TO',
      from: businessObjectId(item.objectType),
      to: domainId(domain),
      label: domain,
      source: 'business_object_catalog',
      sourcePath: input.businessObjectCatalogPath,
      confidence: 1,
      updatedAt: input.generatedAt,
    });

    for (const model of [...item.sourceModels, ...(item.evidenceSourceModels ?? [])]) {
      addNode(graph, {
        id: modelId(model),
        type: 'DataModel',
        name: model,
        displayName: model,
        source: modelNames.has(model) ? 'prisma' : 'business_object_catalog',
        sourcePath: modelNames.has(model) ? input.schemaPath : input.businessObjectCatalogPath,
        confidence: modelNames.has(model) ? 1 : 0.72,
        updatedAt: input.generatedAt,
        properties: {
          declaredByBusinessObject: item.objectType,
          missingInPrismaSchema: !modelNames.has(model),
        },
      });
      addEdge(graph, {
        type: 'COMPOSED_OF',
        from: businessObjectId(item.objectType),
        to: modelId(model),
        label: item.evidenceSourceModels?.includes(model) ? 'evidence_source_model' : 'source_model',
        source: 'business_object_catalog',
        sourcePath: input.businessObjectCatalogPath,
        confidence: modelNames.has(model) ? 1 : 0.72,
        updatedAt: input.generatedAt,
      });
    }

    for (const alias of item.aliases) {
      addWordSynonymEdge(graph, alias, businessObjectId(item.objectType), input.generatedAt, input.businessObjectCatalogPath, 'business_object_catalog');
    }

    for (const action of item.supportedActions) {
      if (action === 'unknown') continue;
      addEdge(graph, {
        type: 'SUPPORTS_ACTION',
        from: businessObjectId(item.objectType),
        to: actionId(action),
        label: action,
        source: 'business_object_catalog',
        sourcePath: input.businessObjectCatalogPath,
        confidence: 1,
        updatedAt: input.generatedAt,
      });
    }
  }
}

function addSemanticTermNodes(graph: GraphAccumulator, terms: KnowledgeGraphSemanticTermSource[], generatedAt: string) {
  for (const item of terms) {
    const normalized = normalizeTerm(item.term);
    if (!normalized) continue;
    addNode(graph, {
      id: wordId(item.term),
      type: 'Word',
      name: item.term,
      displayName: item.term,
      source: 'semantic_lexicon',
      sourcePath: item.sourcePath,
      confidence: 0.86,
      updatedAt: generatedAt,
      properties: {
        category: item.category,
      },
    });
  }
}

function addManifestNodes(
  graph: GraphAccumulator,
  manifests: AgentV2CapabilityManifest[],
  modelNames: Set<string>,
  input: BuildAgentV2KnowledgeGraphInput,
) {
  for (const manifest of manifests) {
    const capabilityNodeId = capabilityId(manifest.capabilityId);
    addNode(graph, {
      id: capabilityNodeId,
      type: 'Capability',
      name: manifest.capabilityId,
      displayName: manifest.displayName,
      description: manifest.description,
      source: 'manifest',
      confidence: 1,
      updatedAt: input.generatedAt,
      properties: {
        version: manifest.version,
        status: manifest.status,
        source: manifest.source,
        domain: manifest.domain,
        businessObject: manifest.businessObject,
        outputKinds: manifest.outputKinds,
        executor: manifest.executor,
        releaseStrategy: manifest.releaseStrategy,
        riskLevel: manifest.riskLevel,
        examples: manifest.examples,
        negativeExamples: manifest.negativeExamples,
        boundaryNotes: manifest.boundaryNotes,
      },
    });
    addEdge(graph, {
      type: 'BELONGS_TO',
      from: capabilityNodeId,
      to: domainId(manifest.domain),
      label: manifest.domain,
      source: 'manifest',
      confidence: 1,
      updatedAt: input.generatedAt,
    });

    for (const action of manifest.actions) {
      const mappedAction = action === 'confirm_action' ? 'confirm_action' : action;
      addEdge(graph, {
        type: 'SUPPORTS_ACTION',
        from: capabilityNodeId,
        to: actionId(mappedAction),
        label: mappedAction,
        source: 'manifest',
        confidence: 1,
        updatedAt: input.generatedAt,
      });
    }

    for (const model of manifest.sourceModels) {
      addNode(graph, {
        id: modelId(model),
        type: 'DataModel',
        name: model,
        displayName: model,
        source: modelNames.has(model) ? 'prisma' : 'manifest',
        confidence: modelNames.has(model) ? 1 : 0.78,
        updatedAt: input.generatedAt,
        properties: {
          declaredByCapability: manifest.capabilityId,
          missingInPrismaSchema: !modelNames.has(model),
        },
      });
      addEdge(graph, {
        type: 'COMPOSED_OF',
        from: capabilityNodeId,
        to: modelId(model),
        label: 'source_model',
        source: 'manifest',
        confidence: modelNames.has(model) ? 1 : 0.78,
        updatedAt: input.generatedAt,
      });
    }

    for (const keyword of manifest.triggerKeywords) {
      addWordSynonymEdge(graph, keyword, capabilityNodeId, input.generatedAt, undefined, 'manifest', 'TRIGGERS');
    }
    for (const example of manifest.examples.slice(0, 8)) {
      addWordSynonymEdge(graph, example, capabilityNodeId, input.generatedAt, undefined, 'manifest', 'TRIGGERS');
    }

    for (const permission of manifest.permissionCodes) {
      addPermissionNodeAndEdge(graph, capabilityNodeId, permission, 'manifest', input.generatedAt);
    }
  }
}

function addControllerEndpointNodes(graph: GraphAccumulator, input: BuildAgentV2KnowledgeGraphInput) {
  for (const endpoint of input.controllerEndpoints) {
    const nodeId = endpointId(endpoint.method, endpoint.path);
    addNode(graph, {
      id: nodeId,
      type: 'Capability',
      name: `${endpoint.method} ${endpoint.path}`,
      displayName: `${endpoint.method} ${endpoint.path}`,
      source: 'controller',
      sourcePath: endpoint.file,
      confidence: 0.7,
      updatedAt: input.generatedAt,
      properties: {
        handler: endpoint.handler,
        line: endpoint.line,
        dtoNames: endpoint.dtoNames,
        candidateOnly: true,
      },
    });
    for (const permission of endpoint.permissions) {
      addPermissionNodeAndEdge(graph, nodeId, permission, 'controller', input.generatedAt, endpoint.file);
    }
  }
}

function addFrontendRouteNodes(graph: GraphAccumulator, input: BuildAgentV2KnowledgeGraphInput) {
  for (const route of input.frontendRoutes) {
    const nodeId = routeId(route.path);
    addNode(graph, {
      id: nodeId,
      type: 'Capability',
      name: route.path,
      displayName: route.path,
      source: 'frontend_route',
      sourcePath: route.file,
      confidence: 0.62,
      updatedAt: input.generatedAt,
      properties: {
        line: route.line,
        candidateOnly: true,
      },
    });
    if (route.permission) {
      addPermissionNodeAndEdge(graph, nodeId, route.permission, 'frontend_route', input.generatedAt, route.file);
    }
  }
}

function addManifestExcludeEdges(graph: GraphAccumulator, manifests: AgentV2CapabilityManifest[], generatedAt: string) {
  for (const source of manifests) {
    const negativeText = source.negativeExamples.join(' ');
    for (const target of manifests) {
      if (source.capabilityId === target.capabilityId) continue;
      const targetHints = [...target.triggerKeywords, ...target.examples].filter((hint) => hint.length >= 3);
      const matched = targetHints.find((hint) => negativeText.includes(hint));
      if (!matched) continue;
      addEdge(graph, {
        type: 'EXCLUDES',
        from: capabilityId(source.capabilityId),
        to: capabilityId(target.capabilityId),
        label: matched,
        source: 'manifest',
        confidence: 0.82,
        updatedAt: generatedAt,
        properties: {
          inferredFromNegativeExamples: true,
          matchedText: matched,
        },
      });
    }
  }
}

function addManualOverrideEdges(graph: GraphAccumulator, overrides: KnowledgeGraphManualOverrideSource[], generatedAt: string) {
  const details: KnowledgeGraphManualOverrideMergeDetail[] = [];

  for (const override of overrides) {
    const relationType = normalizeOverrideRelationType(override.relationType);
    const confidence = clampConfidence(override.confidence ?? 1);
    const sourcePath = `agent_knowledge_graph_overrides:${override.id}`;
    const properties = {
      overrideId: override.id,
      overrideType: override.overrideType,
      reason: override.reason ?? undefined,
      payload: override.payload ?? undefined,
    };

    if (override.overrideType === 'synonym' && relationType === 'SYNONYM_OF') {
      const synonym = String(override.value ?? '').trim();
      const targetNodeId = String(override.targetNodeId ?? '').trim();
      if (!synonym || !targetNodeId) {
        details.push(manualOverrideDetail(override, 'skipped', sourcePath, {
          issue: 'synonym override requires value and targetNodeId',
        }));
        continue;
      }
      if (!graph.nodes.has(targetNodeId)) {
        details.push(manualOverrideDetail(override, 'conflict', sourcePath, {
          issue: `targetNodeId not found: ${targetNodeId}`,
        }));
        continue;
      }
      const nodeId = wordId(synonym);
      const mergedEdgeId = edgeId('SYNONYM_OF', nodeId, targetNodeId, override.label ?? synonym);
      addNode(graph, {
        id: nodeId,
        type: 'Word',
        name: synonym,
        displayName: synonym,
        source: 'manual_override',
        sourcePath,
        confidence,
        updatedAt: generatedAt,
        properties,
      });
      addEdge(graph, {
        type: 'SYNONYM_OF',
        from: nodeId,
        to: targetNodeId,
        label: override.label ?? synonym,
        source: 'manual_override',
        sourcePath,
        confidence,
        updatedAt: generatedAt,
        properties,
      });
      details.push(manualOverrideDetail(override, 'adopted', sourcePath, { nodeId, edgeId: mergedEdgeId }));
      continue;
    }

    if (override.overrideType === 'exclude' && relationType === 'EXCLUDES') {
      const sourceNodeId = String(override.sourceNodeId ?? '').trim();
      const targetNodeId = String(override.targetNodeId ?? '').trim();
      if (!sourceNodeId || !targetNodeId) {
        details.push(manualOverrideDetail(override, 'skipped', sourcePath, {
          issue: 'exclude override requires sourceNodeId and targetNodeId',
        }));
        continue;
      }
      if (!graph.nodes.has(sourceNodeId) || !graph.nodes.has(targetNodeId)) {
        const missing = [sourceNodeId, targetNodeId].filter((nodeId) => !graph.nodes.has(nodeId)).join(', ');
        details.push(manualOverrideDetail(override, 'conflict', sourcePath, {
          issue: `node not found: ${missing}`,
        }));
        continue;
      }
      const mergedEdgeId = edgeId('EXCLUDES', sourceNodeId, targetNodeId, override.label ?? override.reason ?? `manual_override:${override.id}`);
      addEdge(graph, {
        type: 'EXCLUDES',
        from: sourceNodeId,
        to: targetNodeId,
        label: override.label ?? override.reason ?? `manual_override:${override.id}`,
        source: 'manual_override',
        sourcePath,
        confidence,
        updatedAt: generatedAt,
        properties,
      });
      details.push(manualOverrideDetail(override, 'adopted', sourcePath, { edgeId: mergedEdgeId }));
      continue;
    }

    details.push(manualOverrideDetail(override, 'skipped', sourcePath, {
      issue: relationType
        ? `${override.overrideType} override does not support ${relationType}`
        : `unsupported relationType: ${override.relationType}`,
    }));
  }

  return details;
}

function buildSummary(
  generatedAt: string,
  schemaHash: string,
  nodes: KnowledgeGraphNode[],
  edges: KnowledgeGraphEdge[],
  activeCapabilityCount: number,
): KnowledgeGraphSummary {
  return {
    generatedAt,
    schemaHash,
    nodeCount: nodes.length,
    edgeCount: edges.length,
    nodeCountsByType: countByFixed(nodes, NODE_TYPES, (node) => node.type),
    edgeCountsByType: countByFixed(edges, EDGE_TYPES, (edge) => edge.type),
    businessObjectCount: nodes.filter((node) => node.type === 'BusinessObject').length,
    dataModelCount: nodes.filter((node) => node.type === 'DataModel').length,
    activeCapabilityCount,
    permissionCodeCount: nodes.filter((node) => node.type === 'PermissionCode').length,
  };
}

function buildCoverageReport(
  generatedAt: string,
  schemaHash: string,
  summary: KnowledgeGraphSummary,
  nodes: KnowledgeGraphNode[],
  edges: KnowledgeGraphEdge[],
  models: PrismaModel[],
  manifests: AgentV2CapabilityManifest[],
  manualOverrides: KnowledgeGraphManualOverrideSource[],
  manualOverrideMergeDetails: KnowledgeGraphManualOverrideMergeDetail[],
): KnowledgeGraphCoverageReport {
  const gaps: KnowledgeGraphGap[] = [];
  const edgeKey = new Set(edges.map((edge) => `${edge.type}:${edge.from}:${edge.to}`));
  const modelSet = new Set(models.map((model) => model.name));

  for (const object of BUSINESS_OBJECT_CATALOG) {
    const objectNodeId = businessObjectId(object.objectType);
    const hasModel = object.sourceModels.some((model) => edgeKey.has(`COMPOSED_OF:${objectNodeId}:${modelId(model)}`));
    if (!hasModel) {
      gaps.push({
        code: 'business_object_missing_source_model',
        severity: 'blocker',
        title: '业务对象缺少数据模型',
        detail: `${object.displayName} 未声明可组成业务对象的 sourceModels。`,
        targetId: objectNodeId,
        suggestedFix: '在 business-object.catalog.ts 中补齐 sourceModels，或确认该对象是否应下线。',
      });
    }
  }

  for (const object of BUSINESS_OBJECT_CATALOG) {
    for (const model of object.sourceModels) {
      if (modelSet.has(model)) continue;
      gaps.push({
        code: 'business_object_model_missing_in_prisma',
        severity: 'warning',
        title: '业务对象声明模型未出现在 Prisma',
        detail: `${object.displayName} 声明了 ${model}，但当前 schema.prisma 未找到该模型。`,
        targetId: modelId(model),
        suggestedFix: '确认模型是否已迁移、是否为外部数据源，必要时改为 evidenceSourceModels 或治理说明。',
      });
    }
  }

  for (const manifest of manifests) {
    const capabilityNodeId = capabilityId(manifest.capabilityId);
    const hasSourceModel = manifest.sourceModels.some((model) => edgeKey.has(`COMPOSED_OF:${capabilityNodeId}:${modelId(model)}`));
    if (!hasSourceModel) {
      gaps.push({
        code: 'capability_missing_source_model',
        severity: 'blocker',
        title: '能力缺少 sourceModels',
        detail: `${manifest.capabilityId} 没有可追溯数据模型，不能进入自动发布。`,
        targetId: capabilityNodeId,
        suggestedFix: '在 Manifest 中补齐 sourceModels，或将能力标记为需要开发。',
      });
    }
    if (!manifest.permissionCodes.length) {
      gaps.push({
        code: 'capability_missing_permission',
        severity: 'blocker',
        title: '能力缺少权限码',
        detail: `${manifest.capabilityId} 未绑定 permissionCodes。`,
        targetId: capabilityNodeId,
        suggestedFix: '绑定真实权限码后才能发布或执行。',
      });
    }
    if (manifest.releaseStrategy === 'auto_publish' && manifest.riskLevel !== 'low') {
      gaps.push({
        code: 'non_low_risk_auto_publish',
        severity: 'blocker',
        title: '非低风险能力不能自动发布',
        detail: `${manifest.capabilityId} riskLevel=${manifest.riskLevel}，但 releaseStrategy=auto_publish。`,
        targetId: capabilityNodeId,
        suggestedFix: '改为 approval_required 或 write_blocked。',
      });
    }
  }

  const knownNodeIds = new Set(nodes.map((node) => node.id));
  for (const edge of edges) {
    if (knownNodeIds.has(edge.from) && knownNodeIds.has(edge.to)) continue;
    gaps.push({
      code: 'edge_endpoint_missing',
      severity: 'blocker',
      title: '图谱边指向不存在节点',
      detail: `${edge.id} 指向 ${edge.from} -> ${edge.to}，至少一端不存在。`,
      targetId: edge.id,
      suggestedFix: '修正图谱生成器，确保先创建节点再创建边。',
    });
  }

  for (const detail of manualOverrideMergeDetails) {
    if (detail.status === 'adopted') continue;
    gaps.push({
      code: `manual_override_${detail.status}`,
      severity: 'warning',
      title: detail.status === 'conflict' ? '人工图谱覆盖存在冲突' : '人工图谱覆盖未合入',
      detail: `override#${detail.id} ${detail.overrideType}/${detail.relationType} 未合入：${detail.issue ?? 'unknown reason'}`,
      targetId: detail.edgeId ?? detail.nodeId ?? detail.targetNodeId ?? detail.sourceNodeId ?? String(detail.id),
      sourcePath: detail.sourcePath,
      suggestedFix: '在治理中心修正目标节点、来源节点、关系类型或覆盖值后重新运行 kg:generate。',
    });
  }

  const blockers = gaps.filter((gap) => gap.severity === 'blocker');
  const warnings = gaps.filter((gap) => gap.severity === 'warning');
  const manualOverrideDetails = manualOverrideMergeDetails.sort((a, b) => a.id - b.id);
  return {
    generatedAt,
    schemaHash,
    passed: blockers.length === 0,
    summary,
    manualOverrides: {
      total: manualOverrides.length,
      synonyms: manualOverrides.filter((item) => item.overrideType === 'synonym').length,
      excludes: manualOverrides.filter((item) => item.overrideType === 'exclude').length,
      adopted: manualOverrideDetails.filter((item) => item.status === 'adopted').length,
      skipped: manualOverrideDetails.filter((item) => item.status === 'skipped').length,
      conflicts: manualOverrideDetails.filter((item) => item.status === 'conflict').length,
      details: manualOverrideDetails,
    },
    gaps,
    blockers,
    warnings,
  };
}

function manualOverrideDetail(
  override: KnowledgeGraphManualOverrideSource,
  status: KnowledgeGraphManualOverrideMergeDetail['status'],
  sourcePath: string,
  extra: Partial<Pick<KnowledgeGraphManualOverrideMergeDetail, 'nodeId' | 'edgeId' | 'issue'>> = {},
): KnowledgeGraphManualOverrideMergeDetail {
  return {
    id: override.id,
    overrideType: override.overrideType,
    relationType: override.relationType,
    status,
    sourceNodeId: override.sourceNodeId,
    targetNodeId: override.targetNodeId,
    value: override.value,
    label: override.label,
    sourcePath,
    ...extra,
  };
}

function addNode(graph: GraphAccumulator, node: KnowledgeGraphNode) {
  const current = graph.nodes.get(node.id);
  if (!current || current.confidence < node.confidence) {
    graph.nodes.set(node.id, { ...current, ...node, properties: { ...(current?.properties ?? {}), ...(node.properties ?? {}) } });
  }
}

function addEdge(
  graph: GraphAccumulator,
  edge: Omit<KnowledgeGraphEdge, 'id'>,
) {
  const id = edgeId(edge.type, edge.from, edge.to, edge.label);
  if (graph.edges.has(id)) return;
  graph.edges.set(id, { ...edge, id });
}

function addWordSynonymEdge(
  graph: GraphAccumulator,
  term: string,
  targetId: string,
  generatedAt: string,
  sourcePath: string | undefined,
  source: KnowledgeGraphSource,
  edgeType: Extract<KnowledgeGraphEdgeType, 'SYNONYM_OF' | 'TRIGGERS'> = 'SYNONYM_OF',
) {
  const normalized = normalizeTerm(term);
  if (!normalized) return;
  addNode(graph, {
    id: wordId(term),
    type: 'Word',
    name: term,
    displayName: term,
    source,
    sourcePath,
    confidence: source === 'manifest' ? 0.9 : 0.96,
    updatedAt: generatedAt,
  });
  addEdge(graph, {
    type: edgeType,
    from: wordId(term),
    to: targetId,
    label: term,
    source,
    sourcePath,
    confidence: source === 'manifest' ? 0.9 : 0.96,
    updatedAt: generatedAt,
  });
}

function addPermissionNodeAndEdge(
  graph: GraphAccumulator,
  fromId: string,
  permission: string,
  source: KnowledgeGraphSource,
  generatedAt: string,
  sourcePath?: string,
) {
  addNode(graph, {
    id: permissionId(permission),
    type: 'PermissionCode',
    name: permission,
    displayName: permission,
    source,
    sourcePath,
    confidence: 0.92,
    updatedAt: generatedAt,
  });
  addEdge(graph, {
    type: 'REQUIRES_PERM',
    from: fromId,
    to: permissionId(permission),
    label: permission,
    source,
    sourcePath,
    confidence: 0.92,
    updatedAt: generatedAt,
  });
}

function parseFieldLine(line: string): PrismaField | null {
  const [name, rawType, ...rest] = line.split(/\s+/);
  if (!name || !rawType) return null;
  const attributes = rest.join(' ');
  const optional = rawType.endsWith('?');
  const list = rawType.endsWith('[]');
  const type = rawType.replace(/[?\[\]]/g, '');
  return {
    name,
    rawType,
    type,
    attributes,
    optional,
    list,
    id: attributes.includes('@id'),
    unique: attributes.includes('@unique'),
    indexed: attributes.includes('@index'),
    relation: false,
  };
}

function parseModelIndexFields(line: string) {
  const matched = line.match(/\[(.*?)\]/);
  if (!matched) return [];
  return [
    matched[1]
      .split(',')
      .map((item) => item.trim().replace(/\(.+\)$/, ''))
      .filter(Boolean),
  ];
}

function parseRelationArgs(attributes: string) {
  const relation = attributes.match(/@relation\((.*?)\)/);
  if (!relation) return { fields: [] as string[], references: [] as string[] };
  return {
    fields: parseRelationArray(relation[1], 'fields'),
    references: parseRelationArray(relation[1], 'references'),
  };
}

function parseRelationArray(text: string, key: string) {
  const matched = text.match(new RegExp(`${key}:\\s*\\[(.*?)\\]`));
  if (!matched) return [];
  return matched[1]
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean);
}

function countByFixed<T, K extends string>(items: T[], keys: readonly K[], keyFn: (item: T) => K): Record<K, number> {
  const result = Object.fromEntries(keys.map((key) => [key, 0])) as Record<K, number>;
  for (const item of items) {
    const key = keyFn(item);
    result[key] = (result[key] ?? 0) + 1;
  }
  return result;
}

function normalizeOverrideRelationType(value: string): KnowledgeGraphEdgeType | null {
  const relationType = String(value ?? '').trim().toUpperCase();
  return EDGE_TYPES.includes(relationType as KnowledgeGraphEdgeType) ? (relationType as KnowledgeGraphEdgeType) : null;
}

function clampConfidence(value: number) {
  if (!Number.isFinite(value)) return 1;
  return Math.max(0, Math.min(1, value));
}

function normalizeTerm(term: string) {
  return String(term || '')
    .trim()
    .toLowerCase()
    .replace(/\s+/g, '');
}

function stableId(value: string) {
  return normalizeTerm(value).replace(/[^a-z0-9\u4e00-\u9fa5:._-]+/g, '-');
}

function domainId(domain: string) {
  return `domain:${stableId(domain || 'unknown')}`;
}

function businessObjectId(objectType: string) {
  return `business-object:${stableId(objectType)}`;
}

function modelId(model: string) {
  return `data-model:${stableId(model)}`;
}

function fieldId(model: string, field: string) {
  return `field:${stableId(model)}.${stableId(field)}`;
}

function capabilityId(id: string) {
  return `capability:${stableId(id)}`;
}

function endpointId(method: string, path: string) {
  return `capability:endpoint:${stableId(method)}:${stableId(path)}`;
}

function routeId(path: string) {
  return `capability:route:${stableId(path)}`;
}

function actionId(action: string) {
  return `action:${stableId(action)}`;
}

function wordId(term: string) {
  return `word:${stableId(term)}`;
}

function permissionId(permission: string) {
  return `permission:${stableId(permission)}`;
}

function edgeId(type: KnowledgeGraphEdgeType, from: string, to: string, label?: string) {
  return `${type}:${from}->${to}${label ? `:${stableId(label)}` : ''}`;
}

function isSensitiveField(field: string) {
  return /phone|mobile|idcard|password|token|secret|openid|unionid|address/i.test(field);
}

function chunkString(value: string, chunkSize: number) {
  const chunks: string[] = [];
  for (let index = 0; index < value.length; index += chunkSize) {
    chunks.push(value.slice(index, index + chunkSize));
  }
  return chunks;
}
