import type { BusinessObjectDefinition } from './knowledge.types.js';

export const BUSINESS_OBJECT_CATALOG: BusinessObjectDefinition[] = [
  {
    objectType: 'Order',
    displayName: '订单',
    sourceModels: ['ProductOrder', 'OrderItem', 'PaymentRecord', 'RefundRecord'],
    aliases: ['订单', '流水', '收银单', '消费单', '核销单', '办卡订单', '充值订单', '退款单'],
    description: '门店收银、核销、办卡、充值、退款等交易记录。',
    queryableFields: ['id', 'orderNo', 'checkoutGroupNo', 'customerName', 'totalAmount', 'netAmount', 'status', 'payMethod', 'paymentNo', 'refundNo'],
    displayFields: {
      orderNo: '订单号',
      checkoutGroupNo: '收银组号',
      customerName: '客户姓名',
      totalAmount: '订单金额',
      netAmount: '实收金额',
      status: '订单状态',
      payMethod: '支付方式',
      listAmount: '原价金额',
      itemType: '明细类型',
      unitPrice: '单价',
      subtotal: '小计金额',
      discount: '折扣',
      itemDiscountAmount: '单项优惠金额',
      orderDiscountAmount: '整单优惠金额',
      orderAllocatedDiscountAmount: '分摊整单优惠',
      totalDiscountAmount: '总优惠金额',
      discountSource: '优惠来源',
      discountPayload: '优惠明细',
      isGift: '是否赠送',
      eligibleForOrderDiscount: '是否参与整单优惠',
      paymentNo: '支付流水号',
      amount: '金额',
      refundNo: '退款单号',
      refundedAt: '退款时间',
    },
    supportedActions: ['lookup', 'list', 'summary', 'print'],
  },
  {
    objectType: 'MemberCard',
    displayName: '客户卡项',
    sourceModels: ['CustomerCard', 'CardUsageRecord', 'Card', 'CustomerBalanceAccount', 'CustomerBalanceTransaction'],
    aliases: ['卡项', '会员卡', '次卡', '疗程卡', '权益卡', '剩余次数'],
    description: '客户持有卡项、权益、储值余额、剩余次数、到期和核销记录。',
    queryableFields: ['id', 'cardName', 'remainingTimes', 'expiryDate', 'status', 'balance', 'amount'],
    displayFields: {
      cardName: '卡项名称',
      totalTimes: '总次数',
      remainingTimes: '剩余次数',
      expiryDate: '到期时间',
      status: '卡项状态',
      price: '卡项价格',
      paidAmount: '实付金额',
      discountAmount: '优惠金额',
      giftTimes: '赠送次数',
      recognizedAmount: '核销确认收入',
      balance: '当前余额',
      amount: '交易金额',
      cashBalance: '现金余额',
      giftBalance: '赠送余额',
      accountId: '余额账户',
      type: '交易类型',
      cashBalanceBefore: '变动前现金余额',
      cashBalanceAfter: '变动后现金余额',
      giftBalanceBefore: '变动前赠送余额',
      giftBalanceAfter: '变动后赠送余额',
      giftAmount: '赠送金额',
      transactionType: '余额变动类型',
      paymentMethod: '支付方式',
    },
    supportedActions: ['lookup', 'summary', 'list', 'diagnose'],
  },
  {
    objectType: 'MarketingActivity',
    displayName: '营销活动',
    sourceModels: ['MarketingActivity', 'MarketingPage', 'Promotion', 'MarketingAutomationExecution', 'MarketingAutomationStrategy', 'MarketingRuleTemplate'],
    evidenceSourceModels: [
      'MarketingPageLead',
      'MarketingRecommendationSnapshot',
      'MarketingAttribution',
      'MarketingPageAttribution',
      'MarketingPageEvent',
      'MarketingPageVersion',
      'RecommendationEvent',
      'AmiGlowDisplayConfig',
    ],
    aliases: ['活动', '营销活动', '推广活动', '优惠活动', '召回活动', '回店礼', '护理礼'],
    description: '门店营销活动、回店活动、优惠活动、推广页、线索和归因效果。',
    queryableFields: ['id', 'title', 'status', 'publishStatus', 'startDate', 'endDate', 'publishedAt', 'leadCount', 'conversionRate'],
    displayFields: {
      id: '活动ID',
      title: '活动名称',
      status: '活动状态',
      publishStatus: '发布状态',
      startDate: '开始时间',
      endDate: '结束时间',
      shareUrl: '活动链接',
      miniappPath: '小程序路径',
      qrCodeUrl: '二维码',
      discount: '活动优惠',
      discountText: '优惠说明',
      type: '活动类型',
      thresholdAmount: '门槛金额',
      discountAmount: '优惠金额',
      discountRate: '折扣率',
      giftText: '赠品说明',
      maxIssueCount: '最大发放数',
      issuedCount: '已发放数',
      usedCount: '已使用数',
      estimatedCost: '预计成本',
      grossMarginGuard: '毛利保护线',
      approvalStatus: '审批状态',
      sourceType: '来源类型',
      runtimeType: '运行类型',
      executionType: '执行方式',
      strategyId: '策略ID',
      strategyName: '策略名称',
      targetCount: '目标人数',
      triggeredCount: '触发人数',
      reachedCount: '触达人次',
      triggerType: '触发类型',
      predictedRevenue: '预计收入',
      actualRevenue: '实际收入',
      conversionType: '转化类型',
      leadCount: '线索数',
      conversionRate: '转化率',
      attributedRevenue: '归因收入',
    },
    supportedActions: ['lookup', 'list', 'get_link', 'analyze', 'recommend', 'draft'],
    governanceNote: 'MarketingPageLead、MarketingRecommendationSnapshot、MarketingAttribution、MarketingPageAttribution、MarketingPageEvent 仅作为营销效果和推荐解释证据来源。',
  },
  {
    objectType: 'MarketingPage',
    displayName: '营销推广页',
    sourceModels: ['MarketingPage'],
    aliases: ['推广页', '活动页', 'H5', '活动链接', '二维码', '小程序路径'],
    description: '营销活动对应的 H5、分享链接、小程序路径和二维码。',
    queryableFields: ['id', 'title', 'slug', 'shareUrl', 'miniappPath', 'qrCodeUrl', 'status'],
    displayFields: {
      title: '页面标题',
      slug: '页面标识',
      shareUrl: '活动链接',
      miniappPath: '小程序路径',
      qrCodeUrl: '二维码',
      status: '页面状态',
    },
    supportedActions: ['lookup', 'get_link'],
  },
  {
    objectType: 'Customer',
    displayName: '客户',
    sourceModels: ['Customer', 'CustomerHealthProfile', 'SkinTest', 'TerminalFollowUpTask'],
    evidenceSourceModels: ['CustomerAppEvent', 'CustomerBehaviorEvent', 'CustomerPredictionSnapshot', 'CustomerAppIdentity'],
    aliases: ['客户', '会员', '顾客', '老客', '新客'],
    description: '门店客户、会员资料、消费、预约、触达、行为和预测关联对象。',
    queryableFields: ['id', 'name', 'phone', 'memberNo', 'levelName', 'lastVisitDate', 'totalSpent'],
    displayFields: {
      name: '客户姓名',
      phone: '手机号',
      memberNo: '会员号',
      levelName: '会员等级',
      maritalStatus: '婚育状态',
      skinType: '肤质类型',
      skinStatus: '皮肤状态',
      lastVisitDate: '最近到店',
      totalSpent: '累计消费',
      visitCount: '到店次数',
      churnRiskScore: '流失风险分',
      repurchaseOpportunityScore: '复购机会分',
      triggerType: '触发类型',
      status: '跟进状态',
      resultType: '跟进结果',
    },
    supportedActions: ['lookup', 'list', 'recommend', 'diagnose'],
    governanceNote: 'TerminalFollowUpTask、CustomerAppEvent、CustomerBehaviorEvent、CustomerPredictionSnapshot 只作为客户召回、复购和渠道解释证据。',
  },
  {
    objectType: 'InventoryProduct',
    displayName: '库存商品',
    sourceModels: ['Product', 'StockBatch', 'StockMovement', 'TransferOrder', 'Category', 'SupplySku', 'SupplyCatalogMapping'],
    aliases: ['商品', '产品', '库存商品', 'SKU', '耗材'],
    description: '门店商品、SKU、库存批次、出入库流水、调拨和耗材对象。',
    queryableFields: ['id', 'name', 'sku', 'brand', 'currentStock', 'safetyStock', 'expiryDate'],
    displayFields: {
      name: '商品名称',
      sku: 'SKU',
      brand: '品牌',
      costPrice: '成本价',
      retailPrice: '零售价',
      salePrice: '销售价',
      discountRate: '折扣率',
      discountLabel: '折扣标签',
      miniappStatus: '小程序状态',
      auditStatus: '审核状态',
      mappingStatus: '映射状态',
      status: '商品状态',
      currentStock: '当前库存',
      safetyStock: '安全库存',
      expiryDate: '到期时间',
      movementType: '库存变动类型',
      sourceType: '来源类型',
      productCount: '商品数量',
      quantity: '数量',
      transferStatus: '调拨状态',
    },
    supportedActions: ['lookup', 'list', 'diagnose', 'recommend'],
  },
  {
    objectType: 'Project',
    displayName: '护理项目',
    sourceModels: ['Project', 'ProjectBomItem', 'ProjectType'],
    evidenceSourceModels: ['ConsumptionRecord', 'IndustryServiceTemplate', 'IndustryProjectBomTemplate', 'IndustryProjectBomItemTemplate'],
    aliases: ['项目', '护理项目', '服务项目', '疗程', '加项'],
    description: '门店护理服务项目、疗程、BOM 标准耗材和项目经营分析对象。',
    queryableFields: ['id', 'name', 'typeId', 'productId', 'standardQty', 'costAmount'],
    displayFields: {
      name: '项目名称',
      typeId: '项目分类ID',
      typeName: '项目分类',
      price: '项目价格',
      status: '项目状态',
      productName: '耗材名称',
      standardQty: '标准用量',
      costAmount: '耗材成本',
      consumptionQty: '实际消耗量',
    },
    supportedActions: ['lookup', 'list', 'analyze', 'diagnose'],
    governanceNote: 'ConsumptionRecord 只作为项目耗材、服务完成和毛利解释证据。',
  },
  {
    objectType: 'Beautician',
    displayName: '美容师',
    sourceModels: [
      'Beautician',
      'BeauticianLevel',
      'CommissionRecord',
      'CommissionRule',
      'CommissionRuleAssignment',
      'CommissionSettlement',
      'CommissionSettlementRecord',
    ],
    evidenceSourceModels: ['BeauticianProjectSkill'],
    aliases: ['美容师', '员工', '店员', '顾问', '技师'],
    description: '门店服务人员、排班、项目技能、提成规则和绩效结算对象。',
    queryableFields: ['id', 'name', 'levelName', 'status', 'commissionAmount', 'settlementStatus'],
    displayFields: {
      name: '员工姓名',
      phone: '手机号',
      levelName: '级别',
      status: '状态',
      type: '提成类型',
      targetType: '提成对象',
      rate: '提成比例',
      fixedAmount: '固定提成',
      sourceType: '来源类型',
      sourceAmount: '计提基数',
      amount: '提成金额',
      commissionRecordId: '提成记录ID',
      amountSnapshot: '结算时提成金额',
      statusSnapshot: '结算时状态',
      projectAmount: '项目提成',
      productAmount: '商品提成',
      cardSaleAmount: '售卡提成',
      rechargeAmount: '充值提成',
      otherAmount: '其他提成',
      totalAmount: '提成总额',
      netAmount: '实发金额',
      commissionAmount: '提成金额',
      settlementStatus: '结算状态',
      skillLevel: '项目技能等级',
      ruleName: '提成规则',
    },
    supportedActions: ['lookup', 'list', 'summary', 'diagnose'],
    governanceNote: 'BeauticianProjectSkill 作为排班匹配、服务质量和绩效解释证据。',
  },
  {
    objectType: 'Reservation',
    displayName: '预约',
    sourceModels: ['Reservation', 'CheckInRecord', 'ServiceTask'],
    aliases: ['预约', '到店', '未到店', '今日预约', '预约客户'],
    description: '门店预约、到店、未到店和预约状态对象。',
    queryableFields: ['id', 'customerId', 'beauticianId', 'projectId', 'date', 'startTime', 'status'],
    displayFields: {
      customerName: '客户姓名',
      beauticianName: '美容师',
      projectName: '预约项目',
      date: '预约日期',
      startTime: '开始时间',
      status: '预约状态',
      taskStatus: '服务任务状态',
      completedAt: '完成时间',
    },
    supportedActions: ['lookup', 'list', 'summary', 'diagnose'],
  },
  {
    objectType: 'Schedule',
    displayName: '排班',
    sourceModels: [
      'BeauticianSchedule',
      'Schedule',
      'Reservation',
      'AppointmentGapCandidate',
      'AppointmentGapOpportunity',
      'BeauticianAvailability',
      'BeauticianTimeOff',
      'ResourceBooking',
      'StoreResource',
      'SchedulingRuleConfig',
    ],
    evidenceSourceModels: ['AppointmentGapOpportunityEvent', 'ScheduleVersion', 'SmartSchedulingRun'],
    aliases: ['排班', '班表', '空档', '忙闲', '可用时段', '占用率'],
    description: '美容师排班、忙闲、空档、请假和时段占用情况。',
    queryableFields: ['beauticianId', 'date', 'startTime', 'endTime', 'status'],
    displayFields: {
      beauticianName: '美容师',
      date: '日期',
      startTime: '开始时间',
      endTime: '结束时间',
      utilizationRate: '利用率',
      status: '排班状态',
      type: '可用类型',
      sourceType: '来源类型',
      bookedCount: '已预约数',
      gapType: '空档类型',
      estimatedRevenue: '预计收入',
      expectedFillRate: '预计填档率',
      candidateCount: '候选客户数',
      lastGeneratedAt: '最近生成时间',
    },
    supportedActions: ['lookup', 'list', 'summary', 'analyze', 'diagnose'],
  },
  {
    objectType: 'Supplier',
    displayName: '供应商采购',
    sourceModels: [
      'PurchaseOrder',
      'ProcurementOrder',
      'ProcurementOrderItem',
      'SupplierQualification',
      'SupplierShipment',
      'SupplierShipmentItem',
      'SupplyCatalogMapping',
      'SupplyQuote',
      'SupplySettlement',
      'SupplySupplier',
      'Product',
    ],
    evidenceSourceModels: ['IndustrySupplyMappingRequest', 'IndustryProductTemplate'],
    aliases: ['供应商', '采购', '补货', '采购建议', '采购单'],
    description: '供应商、采购价、补货建议和采购订单对象。',
    queryableFields: ['id', 'name', 'productId', 'purchasePrice', 'leadTimeDays'],
    displayFields: {
      supplierName: '供应商',
      phone: '联系电话',
      productName: '商品名称',
      suggestedQuantity: '建议采购量',
      purchasePrice: '采购价',
      leadTimeDays: '交期天数',
      supplyPrice: '供货价',
      unitPrice: '单价',
      subtotal: '小计金额',
      price: '报价',
      netAmount: '实付金额',
      rebateRate: '返利比例',
      paymentTerms: '结算条款',
      status: '供应商状态',
      type: '资质类型',
      fileUrl: '资质文件',
      qualificationStatus: '资质状态',
      platformFeeRate: '平台服务费率',
      auditStatus: '审核状态',
      stockStatus: '库存状态',
      mappingStatus: '映射状态',
      sourceType: '来源类型',
      adjustmentAmount: '调整金额',
      orderCount: '订单数',
      totalAmount: '订单总额',
      rebateAmount: '返利金额',
      netPayable: '应付净额',
      settlementAmount: '结算金额',
      settlementStatus: '结算状态',
    },
    supportedActions: ['lookup', 'list', 'recommend', 'draft'],
  },
  {
    objectType: 'Terminal',
    displayName: '智能终端',
    sourceModels: ['TerminalDevice', 'TerminalConversation', 'AgentRun', 'PrintJob'],
    evidenceSourceModels: [
      'AgentApproval',
      'AgentDailyArchive',
      'AgentEvalRun',
      'AgentFeedback',
      'AgentMemory',
      'AgentMessage',
      'AgentRenderedBlock',
      'AgentStep',
      'AgentToolCall',
      'AiAuditLog',
    ],
    aliases: ['终端', '设备', 'Ami Aura', '打印机', '扫码器', '对话失败'],
    description: '终端设备在线状态、外设、会话和高频失败问题。',
    queryableFields: ['id', 'deviceCode', 'status', 'lastHeartbeatAt'],
    displayFields: {
      deviceCode: '设备编号',
      status: '设备状态',
      sourceType: '来源类型',
      printerStatus: '打印机状态',
      scannerStatus: '扫码器状态',
      networkStatus: '网络状态',
      cameraStatus: '摄像头状态',
      lastHeartbeatAt: '最后心跳',
      messageCount: '消息数',
      toolName: '工具名称',
      feedbackType: '反馈类型',
      latencyMs: '耗时',
    },
    supportedActions: ['lookup', 'summary', 'diagnose'],
    governanceNote: 'AgentFeedback、AgentToolCall、AiAuditLog 仅用于 Agent 质量、执行链路和失败原因证据，不进入门店普通业务主查询。',
  },
  {
    objectType: 'Automation',
    displayName: '自动化任务',
    sourceModels: ['AgentAutomationDefinition', 'AgentAutomationRun', 'MarketingAutomationTouch'],
    evidenceSourceModels: ['AgentAutomationEffect', 'PredictionRun'],
    aliases: ['自动化', '自动触达', '自动任务', '执行复盘'],
    description: 'Agent 自动化定义、执行、触达、转化和归因收入。',
    queryableFields: ['id', 'name', 'status', 'triggerType', 'lastTriggeredAt'],
    displayFields: {
      name: '自动化名称',
      status: '状态',
      triggerType: '触发类型',
      strategyId: '策略ID',
      predictedRevenue: '预计收入',
      actualRevenue: '实际收入',
      conversionType: '转化类型',
      runCount: '执行次数',
      attributedRevenue: '归因收入',
    },
    supportedActions: ['lookup', 'summary', 'analyze', 'diagnose'],
  },
  {
    objectType: 'FinanceMetric',
    displayName: '财务指标',
    sourceModels: [
      'PaymentRecord',
      'RefundRecord',
      'OrderItem',
      'OperationCost',
      'OperatingCost',
      'CashierShift',
      'DailySettlement',
      'SupplySettlement',
      'AmiMonthlyBill',
      'AmiPerformanceRecord',
    ],
    aliases: ['利润', '毛利', '现金流', '实收', '退款', '费用', '成本'],
    description: '收入、现金流、退款、结算、毛利和费用类财务指标。',
    queryableFields: ['paidAmount', 'refundAmount', 'grossProfit', 'grossMarginRate', 'costAmount'],
    displayFields: {
      paidAmount: '实收金额',
      refundAmount: '退款金额',
      totalRevenue: '营业收入',
      cashRevenue: '现金收入',
      wechatRevenue: '微信收入',
      alipayRevenue: '支付宝收入',
      cardRevenue: '卡项收入',
      balanceRevenue: '余额支付收入',
      rechargeIncome: '充值收入',
      orderCount: '订单数',
      customerCount: '客户数',
      materialCost: '耗材成本',
      grossProfit: '毛利',
      grossMargin: '毛利',
      grossMarginRate: '毛利率',
      commissionTotal: '提成合计',
      costAmount: '成本费用',
      costDate: '费用日期',
      amount: '费用金额',
      allocationType: '分摊方式',
      revenueAmount: '贡献收入',
      commissionRate: '分成比例',
      commissionAmount: '分成金额',
      commissionFee: 'Ami 分成费用',
      totalFee: '费用合计',
      revenueGenerated: '带来收入',
      triggerType: '触发类型',
      cashIncome: '现金收入',
      operatorType: '操作人类型',
      status: '结算状态',
      settlementAmount: '结算金额',
      shiftStatus: '班次状态',
    },
    supportedActions: ['summary', 'analyze', 'diagnose', 'compare'],
  },
  {
    objectType: 'BusinessOverview',
    displayName: '经营概览',
    sourceModels: ['Store', 'Order', 'Reservation', 'Customer', 'Product', 'AgentAutomationRun'],
    evidenceSourceModels: [
      'User',
      'UserStore',
      'IndustryAdoptionRecord',
      'IndustryEvidence',
      'IndustryKnowledgeItem',
      'IndustrySalaryBenchmark',
    ],
    aliases: ['经营概览', '今日经营', '经营驾驶舱', '重点关注', '经营异常'],
    description: '门店收入、预约、客户、库存和自动化的综合经营摘要。',
    queryableFields: ['dateRange', 'storeId'],
    displayFields: {
      revenue: '营业收入',
      phone: '联系电话',
      status: '状态',
      reservationCount: '预约数',
      customerCount: '客户数',
      alertCount: '风险数',
    },
    supportedActions: ['summary', 'diagnose', 'recommend'],
  },
];

export const FIELD_DISPLAY_NAME_MAP = BUSINESS_OBJECT_CATALOG.reduce<Record<string, string>>((map, item) => {
  for (const [field, label] of Object.entries(item.displayFields)) map[field] = label;
  return map;
}, {});

export function getBusinessObjectDefinition(objectType: string) {
  return BUSINESS_OBJECT_CATALOG.find((item) => item.objectType === objectType);
}
