import type { BusinessObjectDefinition } from './knowledge.types.js';

export const BUSINESS_OBJECT_CATALOG: BusinessObjectDefinition[] = [
  {
    objectType: 'Order',
    displayName: '订单',
    sourceModels: ['ProductOrder', 'OrderItem', 'PaymentRecord', 'RefundRecord'],
    aliases: ['订单', '流水', '收银单', '消费单', '核销单', '办卡订单', '充值订单', '退款单'],
    description: '门店收银、核销、办卡、充值、退款等交易记录。',
    queryableFields: ['id', 'orderNo', 'checkoutGroupNo', 'customerName', 'totalAmount', 'netAmount', 'status', 'payMethod'],
    displayFields: {
      orderNo: '订单号',
      checkoutGroupNo: '收银组号',
      customerName: '客户姓名',
      totalAmount: '订单金额',
      netAmount: '实收金额',
      status: '订单状态',
      payMethod: '支付方式',
    },
    supportedActions: ['lookup', 'list', 'summary', 'print'],
  },
  {
    objectType: 'MemberCard',
    displayName: '客户卡项',
    sourceModels: ['CustomerCard', 'CardUsageRecord'],
    aliases: ['卡项', '会员卡', '次卡', '疗程卡', '权益卡', '剩余次数'],
    description: '客户持有卡项、权益、剩余次数、到期和核销记录。',
    queryableFields: ['id', 'cardName', 'remainingTimes', 'expiryDate', 'status'],
    displayFields: {
      cardName: '卡项名称',
      remainingTimes: '剩余次数',
      expiryDate: '到期时间',
      status: '卡项状态',
    },
    supportedActions: ['lookup', 'summary', 'list', 'diagnose'],
  },
  {
    objectType: 'MarketingActivity',
    displayName: '营销活动',
    sourceModels: ['MarketingActivity', 'MarketingPage'],
    aliases: ['活动', '营销活动', '推广活动', '优惠活动', '召回活动', '回店礼', '护理礼'],
    description: '门店营销活动、回店活动、优惠活动及其推广页。',
    queryableFields: ['id', 'title', 'status', 'publishStatus', 'startDate', 'endDate', 'publishedAt'],
    displayFields: {
      id: '活动ID',
      title: '活动名称',
      status: '活动状态',
      publishStatus: '发布状态',
      startDate: '开始时间',
      endDate: '结束时间',
      shareUrl: '活动链接',
      miniappPath: '小程序路径',
      qrCodeUrl: '二维码',
    },
    supportedActions: ['lookup', 'list', 'get_link', 'analyze', 'recommend', 'draft'],
  },
  {
    objectType: 'MarketingPage',
    displayName: '营销推广页',
    sourceModels: ['MarketingPage'],
    aliases: ['推广页', '活动页', 'H5', '活动链接', '二维码', '小程序路径'],
    description: '营销活动对应的 H5、分享链接、小程序路径和二维码。',
    queryableFields: ['id', 'title', 'slug', 'shareUrl', 'miniappPath', 'qrCodeUrl', 'status'],
    displayFields: {
      title: '页面标题',
      slug: '页面标识',
      shareUrl: '活动链接',
      miniappPath: '小程序路径',
      qrCodeUrl: '二维码',
      status: '页面状态',
    },
    supportedActions: ['lookup', 'get_link'],
  },
  {
    objectType: 'Customer',
    displayName: '客户',
    sourceModels: ['Customer'],
    aliases: ['客户', '会员', '顾客', '老客', '新客'],
    description: '门店客户、会员资料、消费和预约关联对象。',
    queryableFields: ['id', 'name', 'phone', 'memberNo', 'levelName'],
    displayFields: {
      name: '客户姓名',
      phone: '手机号',
      memberNo: '会员号',
      levelName: '会员等级',
    },
    supportedActions: ['lookup', 'list', 'recommend', 'diagnose'],
  },
  {
    objectType: 'InventoryProduct',
    displayName: '库存商品',
    sourceModels: ['Product'],
    aliases: ['商品', '产品', '库存商品', 'SKU', '耗材'],
    description: '门店商品、SKU、库存和耗材对象。',
    queryableFields: ['id', 'name', 'sku', 'brand'],
    displayFields: {
      name: '商品名称',
      sku: 'SKU',
      brand: '品牌',
    },
    supportedActions: ['lookup', 'list', 'diagnose', 'recommend'],
  },
  {
    objectType: 'Project',
    displayName: '护理项目',
    sourceModels: ['Project'],
    aliases: ['项目', '护理项目', '服务项目', '疗程', '加项'],
    description: '门店护理服务项目、疗程和项目经营分析对象。',
    queryableFields: ['id', 'name', 'typeId'],
    displayFields: {
      name: '项目名称',
      typeName: '项目分类',
    },
    supportedActions: ['lookup', 'list', 'analyze', 'diagnose'],
  },
  {
    objectType: 'Beautician',
    displayName: '美容师',
    sourceModels: ['Beautician'],
    aliases: ['美容师', '员工', '店员', '顾问', '技师'],
    description: '门店服务人员、排班和绩效对象。',
    queryableFields: ['id', 'name', 'levelName', 'status'],
    displayFields: {
      name: '员工姓名',
      levelName: '级别',
      status: '状态',
    },
    supportedActions: ['lookup', 'list', 'summary', 'diagnose'],
  },
  {
    objectType: 'Reservation',
    displayName: '预约',
    sourceModels: ['Reservation', 'CheckInRecord'],
    aliases: ['预约', '到店', '未到店', '今日预约', '预约客户'],
    description: '门店预约、到店、未到店和预约状态对象。',
    queryableFields: ['id', 'customerId', 'beauticianId', 'projectId', 'date', 'startTime', 'status'],
    displayFields: {
      customerName: '客户姓名',
      beauticianName: '美容师',
      projectName: '预约项目',
      date: '预约日期',
      startTime: '开始时间',
      status: '预约状态',
    },
    supportedActions: ['lookup', 'list', 'summary', 'diagnose'],
  },
  {
    objectType: 'Schedule',
    displayName: '排班',
    sourceModels: ['BeauticianSchedule', 'Reservation'],
    aliases: ['排班', '班表', '空档', '忙闲', '可用时段', '占用率'],
    description: '美容师排班、忙闲、空档、请假和时段占用情况。',
    queryableFields: ['beauticianId', 'date', 'startTime', 'endTime', 'status'],
    displayFields: {
      beauticianName: '美容师',
      date: '日期',
      startTime: '开始时间',
      endTime: '结束时间',
      utilizationRate: '利用率',
      status: '排班状态',
    },
    supportedActions: ['lookup', 'list', 'summary', 'analyze', 'diagnose'],
  },
  {
    objectType: 'Supplier',
    displayName: '供应商采购',
    sourceModels: ['Supplier', 'PurchaseOrder', 'Product'],
    aliases: ['供应商', '采购', '补货', '采购建议', '采购单'],
    description: '供应商、采购价、补货建议和采购订单对象。',
    queryableFields: ['id', 'name', 'productId', 'purchasePrice', 'leadTimeDays'],
    displayFields: {
      supplierName: '供应商',
      productName: '商品名称',
      suggestedQuantity: '建议采购量',
      purchasePrice: '采购价',
      leadTimeDays: '交期天数',
    },
    supportedActions: ['lookup', 'list', 'recommend', 'draft'],
  },
  {
    objectType: 'Terminal',
    displayName: '智能终端',
    sourceModels: ['TerminalDevice', 'TerminalConversation', 'AgentRun'],
    aliases: ['终端', '设备', 'Ami Aura', '打印机', '扫码器', '对话失败'],
    description: '终端设备在线状态、外设、会话和高频失败问题。',
    queryableFields: ['id', 'deviceCode', 'status', 'lastHeartbeatAt'],
    displayFields: {
      deviceCode: '设备编号',
      status: '设备状态',
      printerStatus: '打印机状态',
      scannerStatus: '扫码器状态',
      lastHeartbeatAt: '最后心跳',
    },
    supportedActions: ['lookup', 'summary', 'diagnose'],
  },
  {
    objectType: 'Automation',
    displayName: '自动化任务',
    sourceModels: ['AgentAutomationDefinition', 'AgentAutomationRun', 'MarketingAutomationTouch'],
    aliases: ['自动化', '自动触达', '自动任务', '执行复盘'],
    description: 'Agent 自动化定义、执行、触达、转化和归因收入。',
    queryableFields: ['id', 'name', 'status', 'triggerType', 'lastTriggeredAt'],
    displayFields: {
      name: '自动化名称',
      status: '状态',
      triggerType: '触发类型',
      runCount: '执行次数',
      attributedRevenue: '归因收入',
    },
    supportedActions: ['lookup', 'summary', 'analyze', 'diagnose'],
  },
  {
    objectType: 'FinanceMetric',
    displayName: '财务指标',
    sourceModels: ['PaymentRecord', 'RefundRecord', 'OrderItem', 'OperationCost'],
    aliases: ['利润', '毛利', '现金流', '实收', '退款', '费用', '成本'],
    description: '收入、现金流、退款、结算、毛利和费用类财务指标。',
    queryableFields: ['paidAmount', 'refundAmount', 'grossProfit', 'grossMarginRate', 'costAmount'],
    displayFields: {
      paidAmount: '实收金额',
      refundAmount: '退款金额',
      grossProfit: '毛利',
      grossMarginRate: '毛利率',
      costAmount: '成本费用',
    },
    supportedActions: ['summary', 'analyze', 'diagnose', 'compare'],
  },
  {
    objectType: 'BusinessOverview',
    displayName: '经营概览',
    sourceModels: ['Order', 'Reservation', 'Customer', 'Product', 'AgentAutomationRun'],
    aliases: ['经营概览', '今日经营', '经营驾驶舱', '重点关注', '经营异常'],
    description: '门店收入、预约、客户、库存和自动化的综合经营摘要。',
    queryableFields: ['dateRange', 'storeId'],
    displayFields: {
      revenue: '营业收入',
      reservationCount: '预约数',
      customerCount: '客户数',
      alertCount: '风险数',
    },
    supportedActions: ['summary', 'diagnose', 'recommend'],
  },
];

export const FIELD_DISPLAY_NAME_MAP = BUSINESS_OBJECT_CATALOG.reduce<Record<string, string>>((map, item) => {
  for (const [field, label] of Object.entries(item.displayFields)) map[field] = label;
  return map;
}, {});

export function getBusinessObjectDefinition(objectType: string) {
  return BUSINESS_OBJECT_CATALOG.find((item) => item.objectType === objectType);
}
