import type { CanonicalMetricPayload } from './brain-metric-candidate.types.js';

export const AMI_CORE_RUNTIME_QUERY_EXECUTOR = 'BusinessDefinitionRuntimeQueryExecutor.execute';
export const AVERAGE_ORDER_VALUE_QUESTION_PATTERN =
  /(?:客单价|平均每单|订单平均金额|每(?:笔|单)(?:订单)?平均(?:收(?:款|了多少钱)?|金额)|平均每(?:笔|单)(?:订单)?(?:收(?:款|了多少钱)?|金额))/;
export const MATERIAL_COST_RATE_QUESTION_PATTERN =
  /(?:耗材|物料|材料)成本.*(?:占|除以).*(?:服务)?(?:收入|营收).*(?:比例|占比|率)?|(?:耗材|物料|材料)成本率/;
export const STAFF_REVENUE_QUESTION_PATTERN =
  /(?:员工|美容师|技师|谁|哪位).*(?:业绩|服务收入|关联实收)|(?:业绩|服务收入|关联实收).*(?:员工|美容师|技师|谁|哪位)/;
export const STAFF_COMPLAINT_QUESTION_PATTERN =
  /(?:员工|美容师|技师|谁|哪个|哪位).*(?:投诉|客诉|差评|不满|负面反馈)|(?:投诉|客诉|差评|不满|负面反馈).*(?:员工|美容师|技师|谁|哪个|哪位)/;

export interface AmiCoreBusinessMetricContract {
  readonly metricKey: string;
  readonly name: string;
  readonly aliases: readonly string[];
  readonly domain: string;
  readonly capabilityKey: string;
  readonly executorSourcePath: string;
  readonly executorSymbol: string;
  readonly payload: CanonicalMetricPayload;
}

export interface AmiCoreBusinessDimensionContract {
  readonly dimensionKey: string;
  readonly name: string;
  readonly domain: string;
  readonly aliases: readonly string[];
  readonly source: { readonly model: string; readonly field: string };
  readonly derivation?: Readonly<Record<string, unknown>>;
  readonly capabilityKey: string;
  readonly capabilityKeys: readonly string[];
  readonly permissions: readonly string[];
}

const SEMANTIC_EXECUTOR_PATH =
  'packages/server-v2/src/brain/capability/executors/brain-semantic-query-capability.executor.ts';
const DOMAIN_EXECUTOR_PATH =
  'packages/server-v2/src/brain/capability/executors/brain-domain-service-capability.executor.ts';
const FOCUSED_EXECUTOR_PATH =
  'packages/server-v2/src/brain/capability/executors/brain-focused-business-capability.executor.ts';

export const AMI_CORE_BUSINESS_METRIC_CONTRACTS: readonly AmiCoreBusinessMetricContract[] = Object.freeze([
  metricContract({
    metricKey: 'product_sales_quantity',
    name: '商品销量',
    aliases: ['商品销量', '产品销量', '销售数量', '卖出数量'],
    domain: 'product',
    capabilityKey: 'product_sales_ranking',
    executorSymbol: 'BrainSemanticQueryCapabilityExecutor.productSalesRanking',
    description: '指定周期内当前门店已完成或已支付商品订单明细的销售数量。',
    valueType: 'count',
    measure: { aggregation: 'sum', model: 'OrderItem', field: 'quantity' },
    sourceModels: ['ProductOrder', 'OrderItem', 'Product'],
    joinPath: [{ fromModel: 'OrderItem', relationField: 'order', toModel: 'ProductOrder' }],
    filters: [
      { model: 'OrderItem', field: 'itemType', operator: 'eq', value: 'product' },
      { model: 'ProductOrder', field: 'status', operator: 'in', value: ['completed', 'paid'] },
    ],
    dimensions: ['productId', 'productName'],
    timeField: 'ProductOrder.createdAt',
    storeScope: {
      mode: 'current_store',
      model: 'OrderItem',
      field: 'storeId',
      joinPath: [{ fromModel: 'OrderItem', relationField: 'order', toModel: 'ProductOrder' }],
    },
    permission: 'core:order:products',
    template: 'template:product_sales',
    outputField: 'product_sales_quantity',
    exceptionPolicy: {
      cancelled: '仅统计 completed/paid 订单，取消订单不计入。',
      refunded: '整单退款状态不计入；部分退款数量需由退款明细口径另行扣减。',
      gifts: '赠品按实际出库数量计入销量，销售额指标单独处理。',
      fallback: '无法确认订单状态或商品类型时不计入并返回数据缺口。',
    },
    allowedTaskTypes: ['query', 'ranking'],
  }),
  metricContract({
    metricKey: 'product_sales_amount',
    name: '商品销售额',
    aliases: ['商品销售额', '产品销售额', '商品销售金额', '产品销售金额'],
    domain: 'product',
    capabilityKey: 'product_sales_ranking',
    executorSymbol: 'BrainSemanticQueryCapabilityExecutor.productSalesRanking',
    description: '指定周期内当前门店已完成或已支付商品订单明细的净销售金额。',
    valueType: 'money',
    measure: { aggregation: 'sum', model: 'OrderItem', field: 'netAmount' },
    sourceModels: ['ProductOrder', 'OrderItem', 'Product'],
    joinPath: [{ fromModel: 'OrderItem', relationField: 'order', toModel: 'ProductOrder' }],
    filters: [
      { model: 'OrderItem', field: 'itemType', operator: 'eq', value: 'product' },
      { model: 'ProductOrder', field: 'status', operator: 'in', value: ['completed', 'paid'] },
    ],
    dimensions: ['productId', 'productName'],
    timeField: 'ProductOrder.createdAt',
    storeScope: {
      mode: 'current_store',
      model: 'OrderItem',
      field: 'storeId',
      joinPath: [{ fromModel: 'OrderItem', relationField: 'order', toModel: 'ProductOrder' }],
    },
    permission: 'core:order:products',
    template: 'template:product_sales',
    outputField: 'product_sales_amount',
    exceptionPolicy: {
      cancelled: '仅统计 completed/paid 订单，取消订单不计入。',
      refunded: '整单退款状态不计入；部分退款按当前订单明细净额口径展示，专用退款分摊另行治理。',
      gifts: '零净额赠品销售额为 0，不虚增销售额。',
      fallback: '订单明细净额缺失或订单状态无法确认时不计入并返回数据缺口。',
    },
    allowedTaskTypes: ['query', 'ranking'],
  }),
  resolverMetricContract({
    metricKey: 'product_gross_margin_rate',
    name: '商品毛利率',
    aliases: ['商品毛利率', '产品毛利率', '商品利润率', '产品利润率'],
    domain: 'product',
    capabilityKey: 'finance_risk_overview',
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.financeRiskOverview',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    description: '指定周期内当前门店商品订单明细净收入扣除退款冲减和可用单位成本后的商品毛利率，按商品汇总。',
    sourceModels: ['ProductOrder', 'OrderItem', 'RefundRecord', 'RefundItem', 'Product'],
    dimensions: ['productId', 'productName'],
    permission: 'core:finance:view',
    template: 'template:product_sales',
    outputField: 'product_gross_margin_rate',
    valueType: 'percent',
    resolver: {
      kind: 'domain_service',
      key: 'product_margin_rows',
      dimensionFields: { productId: 'productId', productName: 'productName' },
      expression: { op: 'field', field: 'grossMarginRate' },
      overallAggregation: 'avg',
    },
    storeModel: 'Product',
    timeField: 'ProductOrder.createdAt',
    exceptionPolicy: {
      cancelled: '取消订单不计入。',
      refunded: '成功退款按退款明细冲减商品数量和净收入；整单退款状态不计入。',
      gifts: '赠品保留成本但净收入为 0，不作为低于成本成交判断。',
      fallback: '优先使用下单成本快照；缺失时明确标注商品主数据成本回退；无成本的部分不参与毛利率判断。',
    },
    allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
  }),
  financeResolverMetricContract({
    metricKey: 'gross_profit_amount',
    name: '毛利金额',
    aliases: ['毛利金额', '毛利是多少', '门店毛利', '经营毛利'],
    description: '指定周期内按上海营业日选择权威日结后汇总的毛利金额。',
    valueType: 'money',
    outputField: 'gross_profit_amount',
    template: 'template:finance_settlement_summary',
    sourceModels: ['DailySettlement'],
    storeModel: 'DailySettlement',
    resolverKey: 'finance_settlement_cost_analysis',
    expression: { op: 'field', field: 'grossProfit' },
    timeField: 'DailySettlement.settleDate',
    exceptionPolicy: {
      cancelled: '取消业务通过权威日结口径排除。',
      refunded: '退款影响以权威日结最终毛利为准。',
      gifts: '赠送业务产生的真实成本按日结口径计入。',
      fallback: '同一营业日存在多条日结时只选择 confirmed/passed 优先的权威记录。',
    },
  }),
  financeResolverMetricContract({
    metricKey: 'gross_margin_rate',
    name: '毛利率',
    aliases: ['毛利率', '毛利比例', '经营毛利率'],
    description: '指定周期权威日结毛利除以权威日结收入得到的毛利率。',
    valueType: 'percent',
    outputField: 'gross_margin_rate',
    template: 'template:finance_settlement_summary',
    sourceModels: ['DailySettlement'],
    storeModel: 'DailySettlement',
    resolverKey: 'finance_settlement_cost_analysis',
    expression: { op: 'field', field: 'grossMarginRate' },
    overallAggregation: 'avg',
    timeField: 'DailySettlement.settleDate',
    exceptionPolicy: {
      cancelled: '取消业务通过权威日结口径排除。',
      refunded: '退款影响以权威日结最终毛利和收入为准。',
      gifts: '赠送业务产生的真实成本按日结口径计入。',
      fallback: '收入为 0 时返回 0，不用其他收入指标替代分母。',
    },
  }),
  financeResolverMetricContract({
    metricKey: 'operating_profit_amount',
    name: '经营利润',
    aliases: ['经营利润', '运营利润', '门店经营利润'],
    description: '权威日结毛利减去有效提成和已登记经营费用后的经营利润。',
    valueType: 'money',
    outputField: 'operating_profit_amount',
    template: 'template:finance_settlement_summary',
    sourceModels: ['DailySettlement', 'OperatingCost', 'CommissionRecord'],
    storeModel: 'DailySettlement',
    resolverKey: 'finance_settlement_cost_analysis',
    expression: { op: 'field', field: 'operatingProfit' },
    timeField: 'DailySettlement.settleDate',
    exceptionPolicy: {
      cancelled: '已取消或拒绝的提成不计入。',
      refunded: '退款影响以权威日结毛利为准。',
      gifts: '赠送业务的真实成本和提成按正式记录计入。',
      fallback: '经营利润只使用已发布的日结、提成和经营费用口径，不等同于净利润。',
    },
  }),
  financeResolverMetricContract({
    metricKey: 'cost_income_ratio',
    name: '成本收入比',
    aliases: ['成本收入比', '成本占收入比例', '成本占营收比例'],
    description: '耗材成本、有效提成与经营费用之和除以权威日结收入。',
    valueType: 'percent',
    outputField: 'cost_income_ratio',
    template: 'template:finance_settlement_summary',
    sourceModels: ['DailySettlement', 'OperatingCost', 'CommissionRecord'],
    storeModel: 'DailySettlement',
    resolverKey: 'finance_settlement_cost_analysis',
    expression: { op: 'field', field: 'costIncomeRatio' },
    overallAggregation: 'avg',
    timeField: 'DailySettlement.settleDate',
    exceptionPolicy: {
      cancelled: '已取消或拒绝的提成不计入。',
      refunded: '退款影响以权威日结收入和毛利口径为准。',
      gifts: '赠送业务的真实成本按正式记录计入。',
      fallback: '收入为 0 时返回 0，并明确分母缺失。',
    },
  }),
  financeResolverMetricContract({
    metricKey: 'cash_shift_reconciliation_rate',
    name: '收银对平率',
    aliases: ['收银对平率', '收银班次是否对平', '日结是否对平', '对平了吗'],
    description: '指定周期内权威日结同时为 confirmed 且 reconciliationStatus=passed 的营业日占比。',
    valueType: 'percent',
    outputField: 'cash_shift_reconciliation_rate',
    template: 'template:finance_settlement_summary',
    sourceModels: ['DailySettlement'],
    storeModel: 'DailySettlement',
    resolverKey: 'finance_settlement_cost_analysis',
    expression: { op: 'field', field: 'cashShiftReconciliationRate' },
    overallAggregation: 'avg',
    timeField: 'DailySettlement.settleDate',
    exceptionPolicy: {
      cancelled: '取消业务不改变日结记录的对平状态。',
      refunded: '退款应进入日结对账，不在查询时跳过。',
      gifts: '赠送业务应按正式日结记录参与对账。',
      fallback: '没有权威日结时返回未对平，不把缺失记录视为通过。',
    },
  }),
  financeResolverMetricContract({
    metricKey: 'stored_value_liability',
    name: '储值负债',
    aliases: ['储值负债', '储值余额负债', '会员余额负债', '储值负债总额'],
    description: '截至查询时点当前门店有效储值账户现金余额与赠送余额合计。',
    valueType: 'money',
    outputField: 'stored_value_liability',
    template: 'template:finance_settlement_summary',
    sourceModels: ['CustomerBalanceAccount'],
    storeModel: 'CustomerBalanceAccount',
    resolverKey: 'finance_stored_value_liability_summary',
    expression: { op: 'field', field: 'storedValueLiability' },
    timePolicy: { mode: 'as_of_snapshot', boundary: 'as_of', timezone: 'Asia/Shanghai' },
    exceptionPolicy: {
      cancelled: '已停用账户不计入。',
      refunded: '退款恢复后的余额以账户当前余额为准。',
      gifts: '赠送余额属于门店履约义务，计入储值负债。',
      fallback: '只汇总 active CustomerBalanceAccount，不用次卡剩余价值替代。',
    },
  }),
  financeResolverMetricContract({
    metricKey: 'unfulfilled_card_liability',
    name: '次卡未履约负债',
    aliases: ['次卡未履约负债', '套餐卡未履约负债', '次卡剩余负债'],
    description: '截至查询时点有效次卡剩余次数乘以确认单次价值形成的未履约负债。',
    valueType: 'money',
    outputField: 'unfulfilled_card_liability',
    template: 'template:finance_settlement_summary',
    sourceModels: ['CustomerCard', 'Customer'],
    storeModel: 'Customer',
    resolverKey: 'finance_unfulfilled_card_liability_summary',
    expression: { op: 'field', field: 'unfulfilledCardLiability' },
    timePolicy: { mode: 'as_of_snapshot', boundary: 'as_of', timezone: 'Asia/Shanghai' },
    exceptionPolicy: {
      cancelled: '已终止或非 active 次卡不计入。',
      refunded: '退款后的剩余次数与单次价值以当前卡账户为准。',
      gifts: '赠送次数如仍可履约，按正式 recognizedUnitValue 计入。',
      fallback: 'recognizedUnitValue 缺失时按 0 并披露数据缺口，不使用卡售价临时估算。',
    },
  }),
  financeResolverMetricContract({
    metricKey: 'card_recognized_revenue_amount',
    name: '次卡核销确认收入',
    aliases: ['次卡核销确认收入', '次卡确认收入', '套餐卡核销收入', '卡项收入确认'],
    description: '指定周期内次卡核销优先汇总 recognizedAmount，缺失时使用 recognizedUnitValue 乘以核销次数。',
    valueType: 'money',
    outputField: 'card_recognized_revenue_amount',
    template: 'template:finance_card_recognition',
    sourceModels: ['CardUsageRecord'],
    storeModel: 'CardUsageRecord',
    resolverKey: 'finance_card_recognition_rows',
    expression: { op: 'field', field: 'recognizedAmount' },
    timeField: 'CardUsageRecord.verifiedAt',
    exceptionPolicy: {
      cancelled: '未形成有效核销记录的不确认收入。',
      refunded: '核销撤销或退款必须通过正式冲销记录处理。',
      gifts: '赠送次数按正式单次确认价值确认，不按卡售价估算。',
      fallback: 'recognizedAmount 为 0 时才使用 recognizedUnitValue×times。',
    },
  }),
  financeResolverMetricContract({
    metricKey: 'order_gross_profit_amount',
    name: '订单毛利',
    aliases: ['订单毛利', '每张订单毛利', '订单利润', '订单毛利金额'],
    description: '订单商品或项目履约净收入扣除退款分摊、成本和有效提成后的毛利。',
    valueType: 'money',
    outputField: 'order_gross_profit_amount',
    template: 'template:finance_order_profit_rows',
    sourceModels: ['ProductOrder', 'OrderItem', 'Product', 'ProjectBomItem', 'StockMovement', 'CommissionRecord'],
    storeModel: 'ProductOrder',
    resolverKey: 'finance_order_profit_rows',
    expression: { op: 'field', field: 'grossProfit' },
    dimensions: ['orderId'],
    dimensionFields: { orderId: 'orderId' },
    timeField: 'ProductOrder.createdAt',
    allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
    exceptionPolicy: {
      cancelled: '取消和整单退款订单不计入。',
      refunded: '有效退款按订单明细净收入比例分摊扣减。',
      gifts: '赠送商品或项目无收入但保留真实成本和提成影响。',
      fallback: '开卡和充值预收在收款时不确认经营毛利。',
    },
  }),
  financeResolverMetricContract({
    metricKey: 'order_total_cost_amount',
    name: '订单总成本',
    aliases: ['订单总成本', '每张订单成本', '订单成本金额'],
    description: '订单商品成本、项目耗材成本和有效提成合计。',
    valueType: 'money',
    outputField: 'order_total_cost_amount',
    template: 'template:finance_order_profit_rows',
    sourceModels: ['ProductOrder', 'OrderItem', 'Product', 'ProjectBomItem', 'StockMovement', 'CommissionRecord'],
    storeModel: 'ProductOrder',
    resolverKey: 'finance_order_profit_rows',
    expression: { op: 'field', field: 'totalCost' },
    dimensions: ['orderId'],
    dimensionFields: { orderId: 'orderId' },
    timeField: 'ProductOrder.createdAt',
    exceptionPolicy: {
      cancelled: '取消和整单退款订单不计入。',
      refunded: '退款不虚构成本回转，使用正式库存和提成记录。',
      gifts: '赠送商品或项目的真实成本仍计入。',
      fallback: '优先使用库存批次或订单成本快照，缺失时才使用商品主数据或项目 BOM。',
    },
  }),
  financeResolverMetricContract({
    metricKey: 'negative_margin_order_count',
    name: '负毛利订单数',
    aliases: ['负毛利订单', '哪些订单毛利为负', '亏损订单', '毛利小于零的订单'],
    description: '订单毛利小于 0 的有效订单数量，可按订单 ID 返回明细。',
    valueType: 'count',
    outputField: 'negative_margin_order_count',
    template: 'template:finance_order_profit_rows',
    sourceModels: ['ProductOrder', 'OrderItem', 'Product', 'ProjectBomItem', 'StockMovement', 'CommissionRecord'],
    storeModel: 'ProductOrder',
    resolverKey: 'finance_order_profit_rows',
    expression: { op: 'field', field: 'negativeMarginFlag' },
    dimensions: ['orderId'],
    dimensionFields: { orderId: 'orderId' },
    timeField: 'ProductOrder.createdAt',
    allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
    exceptionPolicy: {
      cancelled: '取消和整单退款订单不计入。',
      refunded: '有效退款分摊后重新判断订单毛利。',
      gifts: '赠送业务保留真实成本，可能形成负毛利。',
      fallback: '只有完整计算后的 grossProfit<0 才标记，不按订单金额猜测。',
    },
  }),
  financeResolverMetricContract({
    metricKey: 'prepaid_order_gross_profit_amount',
    name: '开卡订单经营毛利',
    aliases: ['开卡订单利润', '办卡订单利润', '卡销售订单毛利', '预收订单毛利'],
    description: '开卡、办卡和充值属于预收，收款时不确认经营收入和经营毛利。',
    valueType: 'money',
    outputField: 'prepaid_order_gross_profit_amount',
    template: 'template:finance_order_profit_summary',
    sourceModels: ['ProductOrder', 'OrderItem'],
    storeModel: 'ProductOrder',
    resolverKey: 'finance_prepaid_order_profit_rows',
    expression: { op: 'field', field: 'grossProfit' },
    timeField: 'ProductOrder.createdAt',
    exceptionPolicy: {
      cancelled: '取消的预收订单不计入。',
      refunded: '退款通过预收负债冲减处理，不在收款时确认经营利润。',
      gifts: '赠送次数属于后续履约义务，不在开卡时确认收入。',
      fallback: '卡销售项和 member_card_open 订单统一按预收处理。',
    },
  }),
  financeResolverMetricContract({
    metricKey: 'product_order_total_cost_amount',
    name: '商品订单总成本',
    aliases: ['产品订单成本', '商品订单成本', '产品销售成本'],
    description: '商品订单中商品成本和有效提成合计。',
    valueType: 'money',
    outputField: 'product_order_total_cost_amount',
    template: 'template:finance_order_profit_summary',
    sourceModels: ['ProductOrder', 'OrderItem', 'Product', 'StockMovement', 'CommissionRecord'],
    storeModel: 'ProductOrder',
    resolverKey: 'finance_product_order_profit_rows',
    expression: { op: 'field', field: 'totalCost' },
    timeField: 'ProductOrder.createdAt',
    exceptionPolicy: {
      cancelled: '取消和整单退款订单不计入。',
      refunded: '退款不虚构成本回转，按正式库存和提成记录核算。',
      gifts: '赠送商品的真实成本仍计入。',
      fallback: '优先使用库存或订单成本快照，缺失时使用商品主数据成本并披露。',
    },
  }),
  financeResolverMetricContract({
    metricKey: 'product_order_gross_profit_amount',
    name: '商品订单毛利',
    aliases: ['产品订单毛利', '商品订单毛利', '产品订单利润'],
    description: '商品订单净收入扣除退款分摊、商品成本和有效提成后的毛利。',
    valueType: 'money',
    outputField: 'product_order_gross_profit_amount',
    template: 'template:finance_order_profit_summary',
    sourceModels: ['ProductOrder', 'OrderItem', 'Product', 'StockMovement', 'CommissionRecord'],
    storeModel: 'ProductOrder',
    resolverKey: 'finance_product_order_profit_rows',
    expression: { op: 'field', field: 'grossProfit' },
    timeField: 'ProductOrder.createdAt',
    exceptionPolicy: {
      cancelled: '取消和整单退款订单不计入。',
      refunded: '有效退款按订单明细净收入比例分摊扣减。',
      gifts: '赠送商品无收入但保留真实成本和提成影响。',
      fallback: '只识别 itemType=product/goods，不直接信任 ProductOrder.orderKind。',
    },
  }),
  financeResolverMetricContract({
    metricKey: 'staff_commission_component_amount',
    name: '员工提成构成金额',
    aliases: ['提成构成', '提成组成', '员工提成分类', '美容师提成构成'],
    description: '指定周期内按美容师和 CommissionRecord.type 汇总有效提成金额。',
    valueType: 'money',
    outputField: 'staff_commission_component_amount',
    template: 'template:finance_staff_commission',
    sourceModels: ['CommissionRecord', 'Beautician'],
    storeModel: 'CommissionRecord',
    resolverKey: 'finance_staff_commission_rows',
    expression: { op: 'field', field: 'amount' },
    dimensions: ['commissionType'],
    dimensionFields: { commissionType: 'commissionType' },
    timeField: 'CommissionRecord.createdAt',
    allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
    exceptionPolicy: {
      cancelled: '已取消或拒绝的提成记录不计入。',
      refunded: '退款调整以最终有效提成记录为准。',
      gifts: '没有形成有效提成记录的赠送业务不产生提成。',
      fallback: '必须使用受控美容师实体 ID 和当前门店范围，不按姓名文本直接查询。',
    },
  }),
  resolverMetricContract({
    metricKey: 'product_below_cost_sale_count',
    name: '低于成本销售笔数',
    aliases: ['低于成本销售', '低价亏损销售', '成交价低于成本', '亏本商品订单'],
    domain: 'product',
    capabilityKey: 'finance_risk_overview',
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.financeRiskOverview',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    description: '指定周期内当前门店非赠品商品成交单价低于可用单位成本的订单明细笔数，按商品汇总。',
    sourceModels: ['ProductOrder', 'OrderItem', 'RefundRecord', 'RefundItem', 'Product'],
    dimensions: ['productId', 'productName'],
    permission: 'core:finance:view',
    template: 'template:product_sales',
    outputField: 'product_below_cost_sale_count',
    valueType: 'count',
    resolver: {
      kind: 'domain_service',
      key: 'product_margin_rows',
      dimensionFields: { productId: 'productId', productName: 'productName' },
      expression: { op: 'field', field: 'belowCostSaleCount' },
      overallAggregation: 'sum',
    },
    storeModel: 'Product',
    timeField: 'ProductOrder.createdAt',
    exceptionPolicy: {
      cancelled: '取消订单不计入。',
      refunded: '成功退款按退款明细冲减数量和净收入；已无剩余成交数量的明细不计入。',
      gifts: '赠品不判定为低于成本成交。',
      fallback: '成本缺失的订单明细不判定为低于成本，并披露成本覆盖缺口。',
    },
    allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
  }),
  metricContract({
    metricKey: 'project_service_count',
    name: '项目服务次数',
    aliases: ['项目服务次数', '项目次数', '护理项目次数'],
    domain: 'project',
    capabilityKey: 'project_service_ranking',
    capabilityKeys: ['store_operations_overview'],
    executorSymbol: 'BrainSemanticQueryCapabilityExecutor.projectServiceRanking',
    description: '指定周期内当前门店已完成或已支付项目订单明细的服务数量；次卡核销另列口径。',
    valueType: 'count',
    measure: { aggregation: 'sum', model: 'OrderItem', field: 'quantity' },
    sourceModels: ['ProductOrder', 'OrderItem', 'Project', 'CardUsageRecord'],
    joinPath: [{ fromModel: 'OrderItem', relationField: 'order', toModel: 'ProductOrder' }],
    filters: [
      { model: 'OrderItem', field: 'itemType', operator: 'eq', value: 'project' },
      { model: 'ProductOrder', field: 'status', operator: 'in', value: ['completed', 'paid'] },
    ],
    dimensions: ['projectId', 'projectName'],
    timeField: 'ProductOrder.createdAt',
    storeScope: {
      mode: 'current_store',
      model: 'OrderItem',
      field: 'storeId',
      joinPath: [{ fromModel: 'OrderItem', relationField: 'order', toModel: 'ProductOrder' }],
    },
    permission: 'core:project-order-profit:view',
    template: 'template:project_service',
    outputField: 'project_service_count',
    exceptionPolicy: {
      cancelled: '仅统计 completed/paid 订单，取消订单不计入。',
      refunded: '整单退款状态不计入；部分退款数量需由退款明细口径另行扣减。',
      gifts: '赠送项目按实际订单数量计入服务次数并在销售额指标中单独处理。',
      fallback: '次卡核销尚未并入口径时明确标注订单项目服务次数，不混算。',
    },
    allowedTaskTypes: ['query', 'ranking'],
  }),
  metricContract({
    metricKey: 'paid_amount',
    name: '实收金额',
    aliases: ['实收金额', '实收', '营业额', '营收', '流水', 'paid_revenue'],
    domain: 'finance',
    capabilityKey: 'order_revenue_analysis',
    capabilityKeys: ['finance_payment_breakdown', 'finance_risk_overview', 'store_operations_overview'],
    executorSymbol: 'BrainSemanticQueryCapabilityExecutor.orderRevenueAnalysis',
    description: '指定周期内当前门店支付成功记录的实收金额。',
    valueType: 'money',
    measure: { aggregation: 'sum', model: 'PaymentRecord', field: 'amount' },
    sourceModels: ['ProductOrder', 'PaymentRecord', 'RefundRecord'],
    joinPath: [{ fromModel: 'PaymentRecord', relationField: 'order', toModel: 'ProductOrder' }],
    filters: [{ model: 'PaymentRecord', field: 'status', operator: 'in', value: ['paid', 'success', 'completed'] }],
    dimensions: ['paymentMethod'],
    timeField: 'PaymentRecord.paidAt',
    storeScope: {
      mode: 'current_store',
      model: 'PaymentRecord',
      field: 'storeId',
      joinPath: [{ fromModel: 'PaymentRecord', relationField: 'order', toModel: 'ProductOrder' }],
    },
    permission: 'core:finance:view',
    template: 'template:order_revenue',
    outputField: 'paid_amount',
    exceptionPolicy: {
      cancelled: '未支付和取消支付记录不计入。',
      refunded: '实收为支付成功金额，退款金额由退款指标单独展示，不在本指标中静默抵扣。',
      gifts: '赠品不直接改变支付记录金额。',
      fallback: 'paidAt 为空的有效支付记录按 createdAt 口径另行治理，当前不纳入。',
    },
    allowedTaskTypes: ['query'],
  }),
  resolverMetricContract({
    metricKey: 'average_order_value',
    name: '客单价',
    aliases: [
      '客单价',
      '平均客单价',
      '日均客单价',
      '订单平均金额',
      '每笔订单平均收款',
      '每单平均收款',
      'customer_unit_price',
      'average_order_value',
    ],
    domain: 'finance',
    capabilityKey: 'order_revenue_analysis',
    capabilityKeys: ['store_operations_overview'],
    executorSymbol: 'BrainSemanticQueryCapabilityExecutor.orderRevenueAnalysis',
    description: '指定周期内当前门店有效订单实收金额除以有效订单数得到的平均每单金额。',
    sourceModels: ['ProductOrder', 'PaymentRecord'],
    dimensions: [],
    permission: 'core:finance:view',
    template: 'template:order_revenue',
    outputField: 'average_order_value',
    valueType: 'money',
    resolver: {
      kind: 'domain_service',
      key: 'manager_operations_analysis',
      dimensionFields: {},
      expression: { op: 'field', field: 'avgTransaction' },
      overallAggregation: 'avg',
    },
    storeModel: 'ProductOrder',
    timeField: 'ProductOrder.createdAt',
    exceptionPolicy: {
      cancelled: '取消和未完成订单不进入有效订单数。',
      refunded: '整单退款订单不计入；部分退款仍按后台经营分析统一口径处理。',
      gifts: '零金额赠送订单不进入客单价分母。',
      fallback: '有效订单数为 0 时返回 0 并明确分母为 0，不用实收金额替代客单价。',
    },
    allowedTaskTypes: ['query', 'diagnosis'],
  }),
  resolverMetricContract({
    metricKey: 'material_cost_rate',
    name: '耗材成本率',
    aliases: ['耗材成本率', '物料成本率', '材料成本率', '耗材成本占收入比例', '耗材成本占服务收入比例'],
    domain: 'finance',
    capabilityKey: 'finance_material_cost_summary',
    executorSourcePath: FOCUSED_EXECUTOR_PATH,
    executorSymbol: 'BrainFocusedBusinessCapabilityExecutor.financeMaterialCostSummary',
    description: '指定周期内当前门店耗材成本除以已接入服务收入得到的比例。',
    sourceModels: ['DailySettlement', 'OperatingCost', 'CommissionRecord'],
    dimensions: [],
    permission: 'core:finance:view',
    template: 'template:finance_settlement_summary',
    outputField: 'material_cost_rate',
    valueType: 'percent',
    resolver: {
      kind: 'domain_service',
      key: 'finance_settlement_cost_analysis',
      dimensionFields: {},
      expression: {
        op: 'divide',
        numerator: { op: 'field', field: 'materialCost' },
        denominator: { op: 'field', field: 'revenue' },
        zero: 'zero',
      },
      overallAggregation: 'avg',
    },
    storeModel: 'DailySettlement',
    timeField: 'DailySettlement.settleDate',
    exceptionPolicy: {
      cancelled: '取消和未完成服务不进入收入与耗材成本。',
      refunded: '退款与收入冲减按后台财务成本分析统一口径处理。',
      gifts: '赠送服务有真实耗材记录时计入耗材成本，但零收入会明确影响分母。',
      fallback: '收入为 0 时返回 0 并披露无法形成有效比例，不用项目耗材排行替代。',
    },
    allowedTaskTypes: ['query', 'diagnosis'],
  }),
  metricContract({
    metricKey: 'refund_amount',
    name: '退款金额',
    aliases: ['退款金额', '退款', '退回金额', '售后退款'],
    domain: 'finance',
    capabilityKey: 'finance_risk_overview',
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.financeRiskOverview',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    description: '指定周期内当前门店已完成退款记录的退款金额。',
    valueType: 'money',
    measure: { aggregation: 'sum', model: 'RefundRecord', field: 'amount' },
    sourceModels: ['RefundRecord', 'ProductOrder'],
    joinPath: [{ fromModel: 'RefundRecord', relationField: 'order', toModel: 'ProductOrder' }],
    filters: [{ model: 'RefundRecord', field: 'status', operator: 'in', value: ['refunded', 'success', 'completed'] }],
    dimensions: [],
    timeField: 'RefundRecord.refundedAt',
    storeScope: {
      mode: 'current_store',
      model: 'RefundRecord',
      field: 'storeId',
      joinPath: [{ fromModel: 'RefundRecord', relationField: 'order', toModel: 'ProductOrder' }],
    },
    permission: 'core:finance:view',
    template: 'template:finance_risk',
    outputField: 'refund_amount',
    exceptionPolicy: {
      cancelled: '申请中、失败或已取消的退款不计入。',
      refunded: '仅统计状态为 refunded/success/completed 的真实退款记录。',
      gifts: '赠品没有支付金额时不产生退款金额。',
      fallback: 'refundedAt 为空或无法关联原订单门店时不计入并返回数据缺口。',
    },
    allowedTaskTypes: ['query', 'diagnosis'],
    sensitive: true,
  }),
  metricContract({
    metricKey: 'refund_count',
    name: '退款笔数',
    aliases: ['退款笔数', '退款几笔', '退款次数'],
    domain: 'finance',
    capabilityKey: 'finance_risk_overview',
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.financeRiskOverview',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    description: '指定周期内当前门店已完成退款记录的笔数。',
    valueType: 'count',
    measure: { aggregation: 'count', model: 'RefundRecord', field: 'id' },
    sourceModels: ['RefundRecord', 'ProductOrder'],
    joinPath: [{ fromModel: 'RefundRecord', relationField: 'order', toModel: 'ProductOrder' }],
    filters: [{ model: 'RefundRecord', field: 'status', operator: 'in', value: ['refunded', 'success', 'completed'] }],
    dimensions: [],
    timeField: 'RefundRecord.refundedAt',
    storeScope: {
      mode: 'current_store',
      model: 'RefundRecord',
      field: 'storeId',
      joinPath: [{ fromModel: 'RefundRecord', relationField: 'order', toModel: 'ProductOrder' }],
    },
    permission: 'core:finance:view',
    template: 'template:finance_risk',
    outputField: 'refund_count',
    exceptionPolicy: {
      cancelled: '申请中、失败或已取消的退款不计入。',
      refunded: '仅统计状态为 refunded/success/completed 的真实退款记录。',
      gifts: '赠品没有退款记录时不产生退款笔数。',
      fallback: 'refundedAt 为空或无法关联原订单门店时不计入并返回数据缺口。',
    },
    allowedTaskTypes: ['query', 'diagnosis'],
    sensitive: true,
  }),
  metricContract({
    metricKey: 'discount_amount',
    name: '优惠金额',
    aliases: ['优惠金额', '折扣金额', '折扣优惠', '让利金额'],
    domain: 'finance',
    capabilityKey: 'finance_risk_overview',
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.financeRiskOverview',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    description: '指定周期内当前门店有效订单已记录的优惠金额合计。',
    valueType: 'money',
    measure: { aggregation: 'sum', model: 'ProductOrder', field: 'totalDiscountAmount' },
    sourceModels: ['ProductOrder'],
    joinPath: [],
    filters: [
      {
        model: 'ProductOrder',
        field: 'status',
        operator: 'notIn',
        value: ['cancelled', 'canceled', 'refunded', '已取消'],
      },
    ],
    dimensions: [],
    timeField: 'ProductOrder.createdAt',
    storeScope: { mode: 'current_store', model: 'ProductOrder', field: 'storeId', joinPath: [] },
    permission: 'core:finance:view',
    template: 'template:finance_risk',
    outputField: 'discount_amount',
    exceptionPolicy: {
      cancelled: '取消或整单退款订单不计入优惠金额。',
      refunded: '部分退款不自动重算原订单优惠，需由退款分摊口径另行治理。',
      gifts: '赠品价值不等同于订单优惠金额，未记录在 totalDiscountAmount 时不估算。',
      fallback: '订单未记录优惠金额时按 0 处理，不从原价与成交价反推。',
    },
    allowedTaskTypes: ['query', 'diagnosis'],
    sensitive: true,
  }),
  metricContract({
    metricKey: 'operating_cost_amount',
    name: '经营成本',
    aliases: ['经营成本', '运营成本', '成本支出', '门店成本'],
    domain: 'finance',
    capabilityKey: 'finance_risk_overview',
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.financeRiskOverview',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    description: '指定周期内当前门店经营成本记录的金额合计，可按成本类别拆分。',
    valueType: 'money',
    measure: { aggregation: 'sum', model: 'OperatingCost', field: 'amount' },
    sourceModels: ['OperatingCost'],
    joinPath: [],
    filters: [],
    dimensions: ['costCategory'],
    timeField: 'OperatingCost.costDate',
    storeScope: { mode: 'current_store', model: 'OperatingCost', field: 'storeId', joinPath: [] },
    permission: 'core:finance:view',
    template: 'template:finance_cost',
    outputField: 'operating_cost_amount',
    exceptionPolicy: {
      cancelled: '已删除或冲销成本必须通过业务记录调整，不在查询时静默修正。',
      refunded: '退款使用独立退款指标，不与经营成本混算。',
      gifts: '赠送活动产生的真实成本按已登记成本类别计入。',
      fallback: '缺少成本日期或类别时保留在未分类数据缺口，不自动归类。',
    },
    allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
  }),
  resolverMetricContract({
    metricKey: 'staff_service_count',
    name: '员工服务次数',
    aliases: ['员工服务次数', '美容师服务次数', '美容师接客次数', '员工接客数'],
    domain: 'staff',
    capabilityKey: 'manager_staff_overview',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.managerStaffOverview',
    description: '指定周期内当前门店按美容师归属统计的有效服务任务数量。',
    sourceModels: ['Beautician', 'ServiceTask'],
    dimensions: ['beauticianId', 'beauticianName'],
    permission: 'core:beautician-performance:view',
    additionalPermissions: ['core:store:reservations'],
    template: 'template:staff_performance',
    outputField: 'staff_service_count',
    valueType: 'count',
    resolver: {
      kind: 'domain_service',
      key: 'manager_staff_analysis',
      dimensionFields: { beauticianId: 'beauticianId', beauticianName: 'name' },
      expression: { op: 'field', field: 'serviceCount' },
      overallAggregation: 'sum',
    },
    storeModel: 'Beautician',
    exceptionPolicy: {
      cancelled: '已取消服务任务不计入员工服务次数。',
      refunded: '退款不反向推断服务是否发生，以服务任务状态为准。',
      gifts: '赠送服务如形成有效服务任务，计入员工服务次数。',
      fallback: '缺少美容师归属的服务任务不计入个人排行，并在结果中提示未归属数据。',
    },
    allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
  }),
  resolverMetricContract({
    metricKey: 'staff_unique_customer_count',
    name: '员工服务客户数',
    aliases: ['员工服务客户数', '美容师接待客户数', '美容师接客人数', '员工接客人数'],
    domain: 'staff',
    capabilityKey: 'manager_staff_overview',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.managerStaffOverview',
    description: '指定周期内当前门店按美容师归属去重统计的已服务客户数量。',
    sourceModels: ['Beautician', 'ServiceTask', 'Customer'],
    dimensions: ['beauticianId', 'beauticianName'],
    permission: 'core:beautician-performance:view',
    additionalPermissions: ['core:store:reservations'],
    template: 'template:staff_performance',
    outputField: 'staff_unique_customer_count',
    valueType: 'count',
    resolver: {
      kind: 'domain_service',
      key: 'manager_staff_analysis',
      dimensionFields: { beauticianId: 'beauticianId', beauticianName: 'name' },
      expression: { op: 'field', field: 'uniqueCustomerCount' },
      overallAggregation: 'sum',
    },
    storeModel: 'Beautician',
    exceptionPolicy: {
      cancelled: '已取消服务任务不计入员工服务客户数。',
      refunded: '退款不反向推断客户是否已接受服务，以服务任务状态为准。',
      gifts: '赠送服务如形成有效服务任务，对应客户计入员工服务客户数。',
      fallback: '缺少美容师或客户归属的服务任务不计入个人排行，并在结果中提示未归属数据。',
    },
    allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
  }),
  resolverMetricContract({
    metricKey: 'staff_customer_repurchase_rate',
    name: '员工客户复购率',
    aliases: ['员工客户复购率', '美容师客户复购率', '谁的客户复购率最高'],
    domain: 'staff',
    capabilityKey: 'manager_staff_overview',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.managerStaffOverview',
    description: '指定周期内当前门店按美容师统计的重复服务客户数除以独立服务客户数。',
    sourceModels: ['Beautician', 'ServiceTask', 'Customer'],
    dimensions: ['beauticianId', 'beauticianName'],
    permission: 'core:beautician-performance:view',
    additionalPermissions: ['core:store:reservations'],
    template: 'template:staff_performance',
    outputField: 'staff_customer_repurchase_rate',
    valueType: 'percent',
    resolver: {
      kind: 'domain_service',
      key: 'manager_staff_analysis',
      dimensionFields: { beauticianId: 'beauticianId', beauticianName: 'name' },
      expression: {
        op: 'divide',
        numerator: { op: 'field', field: 'repeatCustomerCount' },
        denominator: { op: 'field', field: 'uniqueCustomerCount' },
        zero: 'zero',
      },
      overallAggregation: 'avg',
    },
    storeModel: 'Beautician',
    exceptionPolicy: {
      cancelled: '已取消服务任务不计入客户数与复购客户数。',
      refunded: '退款不反向推断服务是否发生，以有效服务任务为准。',
      gifts: '赠送服务如形成有效服务任务，计入服务客户与复购客户判断。',
      fallback: '独立服务客户数为 0 时复购率为 0，并明确显示样本量。',
    },
    allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
    sensitive: true,
  }),
  resolverMetricContract({
    metricKey: 'staff_commission_amount',
    name: '员工提成金额',
    aliases: ['员工提成', '美容师提成', '提成金额', '谁提成最高'],
    domain: 'staff',
    capabilityKey: 'manager_staff_overview',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.managerStaffOverview',
    description: '指定周期内当前门店按美容师汇总的有效提成记录金额。',
    sourceModels: ['Beautician', 'CommissionRecord'],
    dimensions: ['beauticianId', 'beauticianName'],
    permission: 'core:beautician-performance:view',
    additionalPermissions: ['core:store:reservations'],
    template: 'template:staff_performance',
    outputField: 'staff_commission_amount',
    valueType: 'money',
    resolver: {
      kind: 'domain_service',
      key: 'manager_staff_analysis',
      dimensionFields: { beauticianId: 'beauticianId', beauticianName: 'name' },
      expression: { op: 'field', field: 'commissionAmount' },
      overallAggregation: 'sum',
    },
    storeModel: 'Beautician',
    exceptionPolicy: {
      cancelled: '已取消或拒绝的提成记录不计入。',
      refunded: '退款调整以后端提成记录最终金额为准，不在查询时二次估算。',
      gifts: '没有形成有效提成记录的赠送服务不产生提成金额。',
      fallback: '缺少美容师归属的提成记录不计入个人排行并返回数据缺口。',
    },
    allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
    sensitive: true,
  }),
  resolverMetricContract({
    metricKey: 'staff_service_revenue',
    name: '员工关联业绩实收',
    aliases: ['员工业绩', '美容师业绩', '员工服务收入', '美容师服务收入', '谁的业绩最好', '业绩实收'],
    domain: 'staff',
    capabilityKey: 'manager_staff_overview',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.managerStaffOverview',
    description: '指定周期内当前门店按美容师汇总的已生成有效提成记录对应业务实收金额。',
    sourceModels: ['Beautician', 'CommissionRecord'],
    dimensions: ['beauticianId', 'beauticianName'],
    permission: 'core:beautician-performance:view',
    additionalPermissions: ['core:store:reservations'],
    template: 'template:staff_performance',
    outputField: 'staff_service_revenue',
    valueType: 'money',
    resolver: {
      kind: 'domain_service',
      key: 'manager_staff_analysis',
      dimensionFields: { beauticianId: 'beauticianId', beauticianName: 'name' },
      expression: { op: 'field', field: 'revenueAmount' },
      overallAggregation: 'sum',
    },
    storeModel: 'Beautician',
    exceptionPolicy: {
      cancelled: '已取消或拒绝的提成记录不计入员工关联业绩。',
      refunded: '退款调整以后端提成记录最终 sourceAmount 为准，不在查询时二次估算。',
      gifts: '没有形成有效提成记录的赠送服务不产生员工关联业绩。',
      fallback: '缺少美容师归属的有效记录不计入个人排行并返回数据缺口。',
    },
    allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
    sensitive: true,
  }),
  resolverMetricContract({
    metricKey: 'staff_performance_score',
    name: '员工表现评分',
    aliases: ['员工表现评分', '员工综合表现', '美容师表现评分', '综合表现分'],
    domain: 'staff',
    capabilityKey: 'staff_performance_ranking',
    capabilityKeys: ['beautician_service_overview', 'store_operations_overview', 'manager_staff_overview'],
    executorSymbol: 'BrainSemanticQueryCapabilityExecutor.staffPerformanceRanking',
    description: '按服务次数、实收贡献和复购客户数计算的员工综合表现评分。',
    sourceModels: ['Beautician', 'ServiceTask', 'CommissionRecord', 'BeauticianTimeOff'],
    dimensions: ['beauticianId', 'beauticianName'],
    permission: 'core:beautician-performance:view',
    template: 'template:staff_performance',
    outputField: 'staff_performance_score',
    resolver: {
      kind: 'domain_service',
      key: 'manager_staff_analysis',
      dimensionFields: { beauticianId: 'beauticianId', beauticianName: 'name' },
      expression: {
        op: 'multiply',
        left: {
          op: 'add',
          operands: [
            weightedRatio('serviceCount', 10, 0.5),
            weightedRatio('revenueAmount', 5000, 0.3),
            weightedRatio('repeatCustomerCount', 5, 0.2),
          ],
        },
        right: { op: 'constant', value: 100 },
      },
      overallAggregation: 'avg',
    },
    storeModel: 'Beautician',
    exceptionPolicy: {
      cancelled: '已取消服务任务不计入服务次数；已取消或拒绝的佣金记录不计入业绩贡献。',
      refunded: '退款不由评分公式自行推断，以佣金记录中已调整后的 sourceAmount 为准。',
      gifts: '赠送服务如已形成有效服务任务则计入服务次数；没有佣金记录时不产生业绩贡献。',
      fallback: '缺少员工归属的数据不参与个人排名，并在结果中提示未归属数据。',
    },
  }),
  resolverMetricContract({
    metricKey: 'new_customer_count',
    name: '周期新增客户数',
    aliases: ['新增客户数', '新客数', '新来了多少新客'],
    domain: 'customer',
    capabilityKey: 'customer_facts',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.customerFactsLookup',
    description: '指定周期内当前门店创建客户档案的去重客户数。',
    sourceModels: ['Customer', 'ProductOrder'],
    dimensions: [],
    permission: 'core:customer:view',
    template: 'template:customer_acquisition',
    outputField: 'new_customer_count',
    valueType: 'count',
    resolver: {
      kind: 'domain_service',
      key: 'customer_acquisition_conversion_summary',
      dimensionFields: {},
      expression: { op: 'field', field: 'newCustomerCount' },
      overallAggregation: 'sum',
    },
    storeModel: 'Customer',
    exceptionPolicy: {
      cancelled: '客户档案未软删除即计入周期新增客户，订单取消不影响新增客户数。',
      refunded: '退款不影响客户建档事实。',
      gifts: '赠送不影响客户建档事实。',
      fallback: '客户档案缺少来源不影响新客计数，但渠道分析需单独显示未记录。',
    },
    allowedTaskTypes: ['query', 'diagnosis'],
  }),
  resolverMetricContract({
    metricKey: 'new_customer_conversion_count',
    name: '周期新客转化数',
    aliases: ['新客转化数', '新客成交数', '新客首单人数', '转化了多少新客'],
    domain: 'customer',
    capabilityKey: 'customer_facts',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.customerFactsLookup',
    description: '指定周期新增客户中，在建档后且周期结束前完成至少一笔有效正金额订单的去重客户数。',
    sourceModels: ['Customer', 'ProductOrder'],
    dimensions: [],
    permission: 'core:customer:view',
    template: 'template:customer_acquisition',
    outputField: 'new_customer_conversion_count',
    valueType: 'count',
    resolver: {
      kind: 'domain_service',
      key: 'customer_acquisition_conversion_summary',
      dimensionFields: {},
      expression: { op: 'field', field: 'convertedCustomerCount' },
      overallAggregation: 'sum',
    },
    storeModel: 'Customer',
    exceptionPolicy: {
      cancelled: '取消、已取消或整单退款订单不计为转化。',
      refunded: '整单退款订单不计为转化；部分退款但仍保留正净额的订单继续视为有效消费。',
      gifts: '净额为 0 的赠送订单不计为转化。',
      fallback: '只统计建档后至周期结束的有效订单，不用预约或卡项创建替代首单转化。',
    },
    allowedTaskTypes: ['query', 'diagnosis'],
  }),
  resolverMetricContract({
    metricKey: 'new_customer_conversion_rate',
    name: '周期新客转化率',
    aliases: ['新客转化率', '新客成交率', '首单转化率'],
    domain: 'customer',
    capabilityKey: 'customer_facts',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.customerFactsLookup',
    description: '周期新客转化数除以周期新增客户数。',
    sourceModels: ['Customer', 'ProductOrder'],
    dimensions: [],
    permission: 'core:customer:view',
    template: 'template:customer_acquisition',
    outputField: 'new_customer_conversion_rate',
    valueType: 'percent',
    resolver: {
      kind: 'domain_service',
      key: 'customer_acquisition_conversion_summary',
      dimensionFields: {},
      expression: {
        op: 'divide',
        numerator: { op: 'field', field: 'convertedCustomerCount' },
        denominator: { op: 'field', field: 'newCustomerCount' },
        zero: 'zero',
      },
      overallAggregation: 'avg',
    },
    storeModel: 'Customer',
    exceptionPolicy: {
      cancelled: '沿用周期新客转化数的订单状态规则。',
      refunded: '沿用周期新客转化数的退款规则。',
      gifts: '沿用周期新客转化数的零金额赠送规则。',
      fallback: '周期新增客户数为 0 时转化率返回 0，并同时展示样本量。',
    },
    allowedTaskTypes: ['query', 'diagnosis'],
  }),
  resolverMetricContract({
    metricKey: 'dormant_reactivation_customer_count',
    name: '沉睡客户唤醒迹象人数',
    aliases: ['沉睡客户唤醒迹象', '沉睡客户回流信号', '触达后预约客户', '触达后到店客户', '触达后消费客户'],
    domain: 'customer',
    capabilityKey: 'customer_facts',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.customerFactsLookup',
    description:
      '指定触达周期内，触达前满足沉睡证据且在触达后的有效观察窗口内出现预约、实际到店、有效正金额消费、点击或回复信号的去重客户数。',
    sourceModels: [
      'Customer',
      'MarketingAutomationTouch',
      'MarketingAttribution',
      'Reservation',
      'ProductOrder',
      'CustomerPredictionSnapshot',
      'CustomerOpportunity',
    ],
    dimensions: ['customerId', 'customerName'],
    permission: 'core:customer:view',
    template: 'template:customer_reactivation',
    outputField: 'dormant_reactivation_customer_count',
    valueType: 'count',
    resolver: {
      kind: 'domain_service',
      key: 'customer_dormant_reactivation_rows',
      dimensionFields: { customerId: 'customerId', customerName: 'customerName' },
      expression: { op: 'field', field: 'reactivationSignal' },
      overallAggregation: 'sum',
    },
    storeModel: 'Customer',
    timeField: 'MarketingAutomationTouch.touchedAt',
    exceptionPolicy: {
      cancelled: '取消或爽约预约不计为唤醒信号；仅实际到店、有效预约、有效消费或客户互动进入证据。',
      refunded: '整单退款订单不计为有效消费信号；营销归因收入以现有归因记录为准。',
      gifts: '零金额赠送订单不计为有效消费，但实际到店和有效预约仍可独立构成唤醒迹象。',
      fallback: '发送、送达或触达成功本身不计为唤醒；没有显式归因时只标记时间关联，禁止宣称触达造成转化。',
    },
    allowedTaskTypes: ['query', 'diagnosis'],
    sensitive: true,
  }),
  resolverMetricContract({
    metricKey: 'customer_complaint_count',
    name: '客户投诉数',
    aliases: ['客户投诉数', '客户投诉', '客诉数', '客户不满', '负面反馈'],
    domain: 'customer_service',
    capabilityKey: 'customer_feedback_overview',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.customerFeedbackOverview',
    description: '指定周期内当前门店统一客户反馈事实中 feedbackType 为 complaint 的记录数。',
    sourceModels: ['CustomerServiceFeedback', 'ServiceTask'],
    dimensions: [],
    permission: 'core:customer:view',
    template: 'template:customer_feedback',
    outputField: 'customer_complaint_count',
    valueType: 'count',
    resolver: {
      kind: 'domain_service',
      key: 'customer_service_feedback_summary',
      dimensionFields: {},
      expression: { op: 'field', field: 'complaintCount' },
      overallAggregation: 'sum',
    },
    storeModel: 'CustomerServiceFeedback',
    timeField: 'CustomerServiceFeedback.occurredAt',
    exceptionPolicy: {
      cancelled: '客户投诉事实不随订单或预约取消自动删除，必须通过反馈处理状态保留审计。',
      refunded: '退款记录不能替代投诉事实；只有已录入的 complaint 反馈计入。',
      gifts: '赠送或补偿不改变投诉计数，处理结果记录在反馈解决信息中。',
      fallback: '没有投诉记录时必须同时披露评价采集覆盖率，未采集不等于没有投诉。',
    },
    allowedTaskTypes: ['query', 'diagnosis'],
  }),
  resolverMetricContract({
    metricKey: 'customer_unresolved_complaint_count',
    name: '未解决客户投诉数',
    aliases: ['未解决投诉', '待处理客诉', '还有多少投诉没解决', '尚未解决的客户不满'],
    domain: 'customer_service',
    capabilityKey: 'customer_feedback_overview',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.customerFeedbackOverview',
    description: '指定周期内当前门店投诉反馈中状态为 open 或 in_progress 的记录数。',
    sourceModels: ['CustomerServiceFeedback', 'ServiceTask'],
    dimensions: [],
    permission: 'core:customer:view',
    template: 'template:customer_feedback',
    outputField: 'customer_unresolved_complaint_count',
    valueType: 'count',
    resolver: {
      kind: 'domain_service',
      key: 'customer_service_feedback_summary',
      dimensionFields: {},
      expression: { op: 'field', field: 'unresolvedComplaintCount' },
      overallAggregation: 'sum',
    },
    storeModel: 'CustomerServiceFeedback',
    timeField: 'CustomerServiceFeedback.occurredAt',
    exceptionPolicy: {
      cancelled: '反馈只有进入 resolved 或 closed 才不再计入未解决投诉。',
      refunded: '发生退款不自动视为投诉已解决，必须记录处理状态。',
      gifts: '补偿赠送不自动关闭投诉，必须保留处理结果。',
      fallback: '缺少处理状态的历史导入记录按 open 治理并进入数据质量清单。',
    },
    allowedTaskTypes: ['query', 'diagnosis'],
  }),
  resolverMetricContract({
    metricKey: 'customer_average_satisfaction_rating',
    name: '客户平均满意度',
    aliases: ['客户满意度', '平均满意度', '满意评分', '服务评分', '星级评价'],
    domain: 'customer_service',
    capabilityKey: 'customer_feedback_overview',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.customerFeedbackOverview',
    description: '指定周期内当前门店已采集 1-5 星客户反馈的评分总和除以有效评分数。',
    sourceModels: ['CustomerServiceFeedback', 'ServiceTask'],
    dimensions: [],
    permission: 'core:customer:view',
    template: 'template:customer_feedback',
    outputField: 'customer_average_satisfaction_rating',
    valueType: 'score',
    resolver: {
      kind: 'domain_service',
      key: 'customer_service_feedback_summary',
      dimensionFields: {},
      expression: {
        op: 'divide',
        numerator: { op: 'field', field: 'ratingTotal' },
        denominator: { op: 'field', field: 'ratedFeedbackCount' },
        zero: 'zero',
      },
      overallAggregation: 'avg',
    },
    storeModel: 'CustomerServiceFeedback',
    timeField: 'CustomerServiceFeedback.occurredAt',
    exceptionPolicy: {
      cancelled: '反馈评分不随关联订单或预约取消自动移除。',
      refunded: '退款不自动改变客户原始评分。',
      gifts: '赠送补偿不自动修改原始评分，后续回访可新增独立反馈。',
      fallback: '有效评分数为 0 时产品回答必须显示未采集，不得向用户展示为 0 分。',
    },
    allowedTaskTypes: ['query', 'diagnosis'],
  }),
  resolverMetricContract({
    metricKey: 'customer_feedback_collection_coverage_rate',
    name: '客户评价采集覆盖率',
    aliases: ['评价采集覆盖率', '反馈覆盖率', '满意度采集率', '服务评价覆盖率'],
    domain: 'customer_service',
    capabilityKey: 'customer_feedback_overview',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.customerFeedbackOverview',
    description: '指定周期内关联到反馈的去重已完成服务任务数除以已完成服务任务总数。',
    sourceModels: ['CustomerServiceFeedback', 'ServiceTask'],
    dimensions: [],
    permission: 'core:customer:view',
    template: 'template:customer_feedback',
    outputField: 'customer_feedback_collection_coverage_rate',
    valueType: 'percent',
    resolver: {
      kind: 'domain_service',
      key: 'customer_service_feedback_summary',
      dimensionFields: {},
      expression: {
        op: 'divide',
        numerator: { op: 'field', field: 'linkedServiceTaskCount' },
        denominator: { op: 'field', field: 'completedServiceTaskCount' },
        zero: 'zero',
      },
      overallAggregation: 'avg',
    },
    storeModel: 'CustomerServiceFeedback',
    timeField: 'CustomerServiceFeedback.occurredAt',
    exceptionPolicy: {
      cancelled: '取消服务不进入已完成服务任务分母。',
      refunded: '退款不影响服务评价采集覆盖率。',
      gifts: '赠送服务只要形成已完成服务任务就进入分母。',
      fallback: '已完成服务任务为 0 时覆盖率返回 0，并明确显示分母为 0。',
    },
    allowedTaskTypes: ['query', 'diagnosis'],
  }),
  resolverMetricContract({
    metricKey: 'staff_customer_complaint_count',
    name: '员工客户投诉数',
    aliases: ['员工客诉数', '美容师投诉数', '谁的客诉最多', '美容师客诉排行'],
    domain: 'customer_service',
    capabilityKey: 'customer_feedback_overview',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.customerFeedbackOverview',
    description: '指定周期内当前门店按关联美容师汇总的客户投诉记录数。',
    sourceModels: ['CustomerServiceFeedback', 'Beautician'],
    dimensions: ['beauticianId', 'beauticianName'],
    permission: 'core:customer:view',
    template: 'template:customer_feedback_staff',
    outputField: 'staff_customer_complaint_count',
    valueType: 'count',
    resolver: {
      kind: 'domain_service',
      key: 'customer_service_feedback_by_staff',
      dimensionFields: { beauticianId: 'beauticianId', beauticianName: 'beauticianName' },
      expression: { op: 'field', field: 'complaintCount' },
      overallAggregation: 'sum',
    },
    storeModel: 'CustomerServiceFeedback',
    timeField: 'CustomerServiceFeedback.occurredAt',
    exceptionPolicy: {
      cancelled: '投诉记录不随关联业务取消而删除。',
      refunded: '退款不自动生成或关闭员工客诉。',
      gifts: '补偿赠送不改变原员工客诉归属。',
      fallback: '未关联美容师的投诉不进入个人排行，但保留在门店投诉总数并提示未归属数量。',
    },
    allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
    sensitive: true,
  }),
  resolverMetricContract({
    metricKey: 'customer_long_wait_departure_count',
    name: '等待过久离店客户数',
    aliases: ['等待过久离店', '等太久走了', '等待流失', '排队离店客户数'],
    domain: 'reservation',
    capabilityKey: 'customer_waiting_loss_overview',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.customerWaitingLossOverview',
    description: '指定周期内当前门店等待记录 outcome 为 left 且 leaveReasonCode 为 wait_too_long 的客户等待次数。',
    sourceModels: ['CustomerWaitingEpisode', 'Reservation', 'Customer'],
    dimensions: [],
    permission: 'core:store:reservations',
    template: 'template:customer_waiting',
    outputField: 'customer_long_wait_departure_count',
    valueType: 'count',
    resolver: {
      kind: 'domain_service',
      key: 'customer_waiting_summary',
      dimensionFields: {},
      expression: { op: 'field', field: 'longWaitDepartureCount' },
      overallAggregation: 'sum',
    },
    storeModel: 'CustomerWaitingEpisode',
    timeField: 'CustomerWaitingEpisode.startedAt',
    exceptionPolicy: {
      cancelled: '预约取消和爽约不能替代等待流失；只有到店后形成等待记录并明确选择等待过久离店才计入。',
      refunded: '退款与等待流失是独立事实，退款不会自动生成等待过久离店。',
      gifts: '补偿赠送不改变原离店原因，后续处理单独留痕。',
      fallback: '没有等待过久离店记录时必须同时披露等待记录覆盖率，未采集不等于没有流失。',
    },
    allowedTaskTypes: ['query', 'diagnosis'],
    sensitive: true,
  }),
  resolverMetricContract({
    metricKey: 'customer_waiting_collection_coverage_rate',
    name: '客户等待记录覆盖率',
    aliases: ['等待记录覆盖率', '排队记录采集率', '到店等待覆盖率'],
    domain: 'reservation',
    capabilityKey: 'customer_waiting_loss_overview',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.customerWaitingLossOverview',
    description: '指定周期内关联等待记录的去重到店预约数除以全部已签到预约数。',
    sourceModels: ['CustomerWaitingEpisode', 'Reservation'],
    dimensions: [],
    permission: 'core:store:reservations',
    template: 'template:customer_waiting',
    outputField: 'customer_waiting_collection_coverage_rate',
    valueType: 'percent',
    resolver: {
      kind: 'domain_service',
      key: 'customer_waiting_summary',
      dimensionFields: {},
      expression: {
        op: 'divide',
        numerator: { op: 'field', field: 'linkedReservationCount' },
        denominator: { op: 'field', field: 'checkedInReservationCount' },
        zero: 'zero',
      },
      overallAggregation: 'avg',
    },
    storeModel: 'CustomerWaitingEpisode',
    timeField: 'CustomerWaitingEpisode.startedAt',
    exceptionPolicy: {
      cancelled: '未到店的取消或爽约预约不进入已签到预约分母。',
      refunded: '退款不影响等待记录覆盖率。',
      gifts: '赠送服务只要客户到店并签到就进入覆盖率分母。',
      fallback: '已签到预约数为 0 时覆盖率返回 0，并明确显示分母为 0。',
    },
    allowedTaskTypes: ['query', 'diagnosis'],
  }),
  resolverMetricContract({
    metricKey: 'average_return_interval_days',
    name: '客户平均回访间隔',
    aliases: ['平均回访间隔', '平均多久回来一次', '老客回店间隔'],
    domain: 'customer',
    capabilityKey: 'customer_facts',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.customerFactsLookup',
    description: '统计周期内重复消费客户相邻两次有效消费时间间隔的平均天数。',
    sourceModels: ['Customer', 'ProductOrder'],
    dimensions: [],
    permission: 'core:customer:view',
    template: 'template:customer_retention',
    outputField: 'average_return_interval_days',
    valueType: 'duration',
    resolver: {
      kind: 'domain_service',
      key: 'customer_retention_summary',
      dimensionFields: {},
      expression: { op: 'field', field: 'averageReturnIntervalDays' },
      overallAggregation: 'avg',
    },
    storeModel: 'Customer',
    exceptionPolicy: {
      cancelled: '取消和整单退款订单不计入间隔。',
      refunded: '部分退款订单仍保留消费时间点，退款金额不影响间隔天数。',
      gifts: '零金额赠送订单不计入有效消费间隔。',
      fallback: '未指定时间时统一使用最近 180 天；没有重复消费样本时返回无可计算样本。',
    },
    allowedTaskTypes: ['query', 'diagnosis'],
  }),
  resolverMetricContract({
    metricKey: 'stock_risk_score',
    name: '库存风险评分',
    aliases: ['库存风险评分', '库存风险', '缺货风险'],
    domain: 'inventory',
    capabilityKey: 'inventory_risk_ranking',
    capabilityKeys: ['inventory_operations_overview', 'inventory_procurement_advice'],
    executorSymbol: 'BrainSemanticQueryCapabilityExecutor.inventoryRiskRanking',
    description: '当前库存低于安全库存的缺口数量，数值越高风险越高。',
    sourceModels: ['Product'],
    dimensions: ['productId', 'productName'],
    permission: 'core:inventory:stock',
    template: 'template:inventory_risk',
    outputField: 'stock_risk_score',
    resolver: {
      kind: 'domain_service',
      key: 'inventory_risk_summary',
      dimensionFields: { productId: 'productId', productName: 'name' },
      expression: {
        op: 'clamp',
        value: {
          op: 'subtract',
          left: { op: 'field', field: 'safetyStock' },
          right: { op: 'field', field: 'currentStock' },
        },
        min: 0,
        max: 1000000,
      },
      overallAggregation: 'sum',
    },
    storeModel: 'Product',
    exceptionPolicy: {
      cancelled: '不适用。',
      refunded: '退货入库应先形成库存流水，再影响当前库存。',
      gifts: '赠品出库应计入当前库存。',
      fallback: '安全库存缺失时不生成风险分数，并返回商品配置缺口。',
    },
  }),
  resolverMetricContract({
    metricKey: 'inventory_consumption_quantity',
    name: '库存消耗数量',
    aliases: ['库存消耗数量', '耗材消耗量', '物料消耗量', '产品出库量', '耗材消耗速度'],
    domain: 'inventory',
    capabilityKey: 'inventory_operations_overview',
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.inventoryOperationsOverview',
    description: '指定周期内当前门店商品库存流水中出库、消耗、销售、核销类流水的绝对数量，按商品汇总。',
    sourceModels: ['Product', 'StockMovement'],
    dimensions: ['productId', 'productName'],
    permission: 'core:inventory:stock',
    template: 'template:inventory_risk',
    outputField: 'inventory_consumption_quantity',
    valueType: 'count',
    resolver: {
      kind: 'domain_service',
      key: 'inventory_consumption_rows',
      dimensionFields: { productId: 'productId', productName: 'name' },
      expression: { op: 'field', field: 'outboundQty' },
      overallAggregation: 'sum',
    },
    storeModel: 'Product',
    timeField: 'StockMovement.occurredAt',
    exceptionPolicy: {
      cancelled: '取消且未形成库存流水的业务不计入；已冲销流水按实际反向流水影响数量。',
      refunded: '退货入库属于反向入库，不计入出库消耗量。',
      gifts: '赠品形成真实出库流水时计入库存消耗量。',
      fallback: '没有结构化库存流水时返回无数据，不使用当前库存差额倒推历史消耗。',
    },
    allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
  }),
  resolverMetricContract({
    metricKey: 'inventory_operational_turnover_ratio',
    name: '运营库存周转率',
    aliases: ['运营库存周转率', '库存周转率', '库存周转速度'],
    domain: 'inventory',
    capabilityKey: 'inventory_operations_overview',
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.inventoryOperationsOverview',
    description:
      '指定周期内当前门店库存出库数量除以库存流水事件前后量形成的事件加权平均库存。该运营口径用于门店库存诊断，不等同财务会计存货周转率。',
    sourceModels: ['Product', 'StockMovement'],
    dimensions: [],
    permission: 'core:inventory:stock',
    template: 'template:inventory_risk',
    outputField: 'inventory_operational_turnover_ratio',
    valueType: 'score',
    resolver: {
      kind: 'domain_service',
      key: 'inventory_turnover_summary',
      dimensionFields: {},
      expression: { op: 'field', field: 'operationalTurnoverRatio' },
      overallAggregation: 'avg',
    },
    storeModel: 'Product',
    timeField: 'StockMovement.occurredAt',
    exceptionPolicy: {
      cancelled: '取消且未形成库存流水的业务不计入；已冲销流水按真实反向流水处理。',
      refunded: '退货入库属于反向入库，不计入出库数量。',
      gifts: '赠品形成真实出库流水时计入出库数量。',
      fallback: '没有库存流水前后量样本或事件加权平均库存为零时返回无数据，不用当前库存差额倒推。',
    },
    allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
  }),
  resolverMetricContract({
    metricKey: 'inventory_consumption_occupancy_ratio',
    name: '库存耗占比',
    aliases: ['库存耗占比', '耗占比', '库存消耗占用比'],
    domain: 'inventory',
    capabilityKey: 'inventory_operations_overview',
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.inventoryOperationsOverview',
    description:
      '指定周期内当前门店估算出库成本除以库存流水事件前后量形成的事件加权平均库存金额。该运营估算用于库存诊断，不等同物料成本率或财务会计成本率。',
    sourceModels: ['Product', 'StockMovement'],
    dimensions: [],
    permission: 'core:inventory:stock',
    template: 'template:inventory_risk',
    outputField: 'inventory_consumption_occupancy_ratio',
    valueType: 'percent',
    resolver: {
      kind: 'domain_service',
      key: 'inventory_turnover_summary',
      dimensionFields: {},
      expression: { op: 'field', field: 'consumptionOccupancyRatio' },
      overallAggregation: 'avg',
    },
    storeModel: 'Product',
    timeField: 'StockMovement.occurredAt',
    exceptionPolicy: {
      cancelled: '取消且未形成库存流水的业务不计入；已冲销流水按真实反向流水处理。',
      refunded: '退货入库属于反向入库，不计入估算出库成本。',
      gifts: '赠品形成真实出库流水时按商品成本价计入估算出库成本。',
      fallback: '缺少商品成本价、库存前后量样本或事件加权平均库存金额为零时返回无数据，不映射为物料成本率。',
    },
    allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
  }),
  resolverMetricContract({
    metricKey: 'follow_up_priority_score',
    name: '客户跟进优先级评分',
    aliases: ['客户跟进优先级评分', '跟进优先级', '客户优先级', '召回优先级'],
    domain: 'customer',
    capabilityKey: 'customer_priority_recommendation',
    capabilityKeys: ['marketing_growth_overview'],
    executorSymbol: 'BrainSemanticQueryCapabilityExecutor.customerPriorityRecommendation',
    description: '取后台客户机会池中每位客户当前有效机会的最高分，作为人工跟进优先级。',
    sourceModels: ['CustomerOpportunity', 'Customer'],
    dimensions: ['customerId', 'customerName'],
    permission: 'core:marketing:analytics',
    template: 'template:customer_follow_up',
    outputField: 'follow_up_priority_score',
    resolver: {
      kind: 'domain_service',
      key: 'marketing_follow_up_opportunities',
      dimensionFields: { customerId: 'customerId', customerName: 'customerName' },
      expression: { op: 'field', field: 'score' },
      overallAggregation: 'max',
    },
    storeModel: 'CustomerOpportunity',
    allowedTaskTypes: ['query', 'ranking', 'recommendation'],
    exceptionPolicy: {
      cancelled: '已关闭、已取消或已删除的客户机会不参与跟进优先级。',
      refunded: '退款影响由后台预测与机会生成链路更新，不在 Ami Brain 查询时二次计算。',
      gifts: '赠送权益的影响由后台机会生成规则统一处理。',
      fallback: '没有当前有效客户机会时返回数据缺口，不使用另一套临时公式补分。',
    },
  }),
]);

export const AMI_CORE_BUSINESS_DIMENSION_CONTRACTS: readonly AmiCoreBusinessDimensionContract[] = Object.freeze([
  dimension('productId', '商品 ID', 'product', ['商品编号'], 'OrderItem', 'itemId', 'product_sales_ranking', [
    'core:brain:use',
  ]),
  dimension('productName', '商品名称', 'product', ['商品', '产品名称'], 'OrderItem', 'name', 'product_sales_ranking', [
    'core:brain:use',
  ]),
  dimension('projectId', '项目 ID', 'project', ['项目编号'], 'OrderItem', 'itemId', 'project_service_ranking', [
    'core:project-order-profit:view',
  ]),
  dimension(
    'projectName',
    '项目名称',
    'project',
    ['项目', '服务项目'],
    'OrderItem',
    'name',
    'project_service_ranking',
    ['core:project-order-profit:view'],
  ),
  dimension(
    'orderId',
    '订单 ID',
    'finance',
    ['订单编号 ID', '订单主键'],
    'ProductOrder',
    'id',
    'finance_risk_overview',
    ['core:finance:view'],
  ),
  dimension(
    'orderNo',
    '订单号',
    'finance',
    ['业务订单号', '订单号码'],
    'ProductOrder',
    'orderNo',
    'finance_risk_overview',
    ['core:finance:view'],
  ),
  dimension('orderKind', '订单类型', 'finance', ['订单种类'], 'ProductOrder', 'orderKind', 'finance_risk_overview', [
    'core:finance:view',
  ]),
  dimension(
    'orderBusinessType',
    '订单业务类型',
    'finance',
    ['商品订单', '项目订单', '开卡订单', '预收订单'],
    'ProductOrder',
    'orderKind',
    'finance_risk_overview',
    ['core:finance:view'],
    [],
    {
      kind: 'order_item_business_type',
      productItemTypes: ['product', 'goods'],
      projectItemTypes: ['project', 'service', 'service_project'],
      prepaidItemTypes: ['card', 'customer_card', 'card_sale', 'member_card', 'recharge'],
      orderKindFallback: ['member_card_open'],
    },
  ),
  dimension(
    'cardName',
    '卡项名称',
    'finance',
    ['次卡名称', '套餐卡名称'],
    'CardUsageRecord',
    'cardName',
    'finance_risk_overview',
    ['core:finance:view'],
  ),
  dimension(
    'commissionType',
    '提成类型',
    'finance',
    ['提成构成', '提成类别'],
    'CommissionRecord',
    'type',
    'finance_risk_overview',
    ['core:finance:view'],
  ),
  dimension(
    'beauticianId',
    '美容师 ID',
    'staff',
    ['员工编号'],
    'Beautician',
    'id',
    'staff_performance_ranking',
    ['core:beautician-performance:view'],
    ['manager_staff_overview', 'customer_feedback_overview', 'finance_risk_overview'],
  ),
  dimension(
    'beauticianName',
    '美容师姓名',
    'staff',
    ['员工', '美容师'],
    'Beautician',
    'name',
    'staff_performance_ranking',
    ['core:beautician-performance:view'],
    ['manager_staff_overview', 'customer_feedback_overview', 'finance_risk_overview'],
  ),
  dimension('customerId', '客户 ID', 'customer', ['客户编号'], 'Customer', 'id', 'customer_priority_recommendation', [
    'core:brain:use',
  ]),
  dimension(
    'customerName',
    '客户姓名',
    'customer',
    ['客户', '顾客姓名'],
    'Customer',
    'name',
    'customer_priority_recommendation',
    ['core:brain:use'],
  ),
  dimension(
    'customerLevel',
    '会员等级',
    'customer',
    ['客户等级', '会员级别', '原始会员等级'],
    'Customer',
    'memberLevel',
    'customer_facts',
    ['core:brain:use'],
    ['reservation_list'],
  ),
  dimension(
    'customerSource',
    '客户来源',
    'customer',
    ['新客来源', '获客渠道', '来源渠道'],
    'Customer',
    'source',
    'customer_facts',
    ['core:customer:view'],
  ),
  dimension(
    'customerAgeGroup',
    '到店客户年龄段',
    'customer',
    ['客户年龄段', '年龄画像', '到店年龄分布'],
    'Customer',
    'age',
    'customer_facts',
    ['core:customer:view'],
    [],
    {
      kind: 'age_bucket',
      birthdayFallbackField: 'birthday',
      asOf: 'requested_range_end',
      buckets: ['24岁及以下', '25-34岁', '35-44岁', '45-54岁', '55岁及以上'],
      unknownPolicy: 'separate_count',
      population: 'unique_arrived_customers',
    },
  ),
  dimension(
    'paymentMethod',
    '支付方式',
    'finance',
    ['收款方式', '收款渠道', '支付渠道', '现金', '微信', '支付宝', '银行卡', '储值余额'],
    'PaymentRecord',
    'method',
    'finance_payment_breakdown',
    ['core:finance:view'],
    ['finance_risk_overview'],
  ),
  dimension(
    'costCategory',
    '成本类别',
    'finance',
    ['费用类别', '成本分类', '支出类别'],
    'OperatingCost',
    'category',
    'finance_risk_overview',
    ['core:finance:view'],
  ),
  dimension(
    'marketingChannel',
    '营销渠道',
    'marketing',
    ['渠道', '触达渠道', '微信', '短信', '小程序'],
    'MarketingAutomationTouch',
    'channel',
    'marketing_growth_overview',
    ['core:marketing:analytics'],
  ),
]);

function metricContract(
  input: Omit<AmiCoreBusinessMetricContract, 'payload' | 'executorSourcePath'> & {
    description: string;
    valueType: CanonicalMetricPayload['valueType'];
    measure: CanonicalMetricPayload['measure'];
    sourceModels: string[];
    joinPath: CanonicalMetricPayload['joinPath'];
    filters: CanonicalMetricPayload['filters'];
    dimensions: string[];
    timeField: string;
    timePolicy?: CanonicalMetricPayload['timePolicy'];
    storeScope: CanonicalMetricPayload['storeScope'];
    permission: string;
    additionalPermissions?: string[];
    template: string;
    outputField: string;
    exceptionPolicy: CanonicalMetricPayload['exceptionPolicy'];
    allowedTaskTypes: CanonicalMetricPayload['allowedTaskTypes'];
    executorSourcePath?: string;
    sensitive?: boolean;
    capabilityKeys?: string[];
  },
): AmiCoreBusinessMetricContract {
  const capabilityKeys = [...new Set([input.capabilityKey, ...(input.capabilityKeys ?? [])])];
  const payload: CanonicalMetricPayload = {
    metricKey: input.metricKey,
    aliases: [...input.aliases],
    description: input.description,
    valueType: input.valueType,
    allowedTaskTypes: input.allowedTaskTypes,
    sensitive: input.sensitive ?? input.metricKey === 'staff_performance_score',
    measure: input.measure,
    sourceModels: input.sourceModels,
    joinPath: input.joinPath,
    filters: input.filters,
    dimensions: input.dimensions,
    timePolicy: input.timePolicy ?? {
      mode: 'event_time',
      field: input.timeField,
      boundary: '[start,end)',
      timezone: 'Asia/Shanghai',
    },
    storeScope: input.storeScope,
    permissionPolicies: capabilityKeys.map((bindingRef) => ({
      bindingRef,
      allOf: [...new Set(['core:brain:use', input.permission, ...(input.additionalPermissions ?? [])])],
    })),
    exceptionPolicy: input.exceptionPolicy,
    bindings: {
      template: [input.template],
      capability: capabilityKeys,
      executor: [AMI_CORE_RUNTIME_QUERY_EXECUTOR],
      outputField: [input.outputField],
      sort: { outputField: input.outputField, direction: 'desc', missing: 'error' },
    },
  };
  return Object.freeze({
    metricKey: input.metricKey,
    name: input.name,
    aliases: Object.freeze([...input.aliases]),
    domain: input.domain,
    capabilityKey: input.capabilityKey,
    executorSourcePath: input.executorSourcePath ?? SEMANTIC_EXECUTOR_PATH,
    executorSymbol: input.executorSymbol,
    payload,
  });
}

function resolverMetricContract(
  input: Omit<AmiCoreBusinessMetricContract, 'payload' | 'executorSourcePath'> & {
    description: string;
    sourceModels: string[];
    dimensions: string[];
    permission: string;
    additionalPermissions?: string[];
    template: string;
    outputField: string;
    resolver: NonNullable<CanonicalMetricPayload['measure']['resolver']>;
    storeModel: string;
    exceptionPolicy: CanonicalMetricPayload['exceptionPolicy'];
    allowedTaskTypes?: CanonicalMetricPayload['allowedTaskTypes'];
    capabilityKeys?: string[];
    executorSourcePath?: string;
    valueType?: CanonicalMetricPayload['valueType'];
    sensitive?: boolean;
    timeField?: string;
    timePolicy?: CanonicalMetricPayload['timePolicy'];
  },
): AmiCoreBusinessMetricContract {
  return metricContract({
    ...input,
    valueType: input.valueType ?? 'score',
    measure: { aggregation: 'score', resolver: input.resolver },
    joinPath: [],
    filters: [],
    timeField: input.timeField ?? `${input.storeModel}.createdAt`,
    ...(input.timePolicy ? { timePolicy: input.timePolicy } : {}),
    storeScope: { mode: 'current_store', model: input.storeModel, field: 'storeId', joinPath: [] },
    allowedTaskTypes: input.allowedTaskTypes ?? ['query', 'ranking'],
  });
}

function financeResolverMetricContract(input: {
  metricKey: string;
  name: string;
  aliases: string[];
  description: string;
  valueType: CanonicalMetricPayload['valueType'];
  outputField: string;
  template?: string;
  sourceModels: string[];
  storeModel: string;
  resolverKey: NonNullable<CanonicalMetricPayload['measure']['resolver']>['key'];
  expression: NonNullable<CanonicalMetricPayload['measure']['resolver']>['expression'];
  dimensions?: string[];
  dimensionFields?: Record<string, string>;
  overallAggregation?: NonNullable<CanonicalMetricPayload['measure']['resolver']>['overallAggregation'];
  allowedTaskTypes?: CanonicalMetricPayload['allowedTaskTypes'];
  timeField?: string;
  timePolicy?: CanonicalMetricPayload['timePolicy'];
  exceptionPolicy: CanonicalMetricPayload['exceptionPolicy'];
}) {
  return resolverMetricContract({
    metricKey: input.metricKey,
    name: input.name,
    aliases: input.aliases,
    domain: 'finance',
    capabilityKey: 'finance_risk_overview',
    executorSourcePath: DOMAIN_EXECUTOR_PATH,
    executorSymbol: 'BrainDomainServiceCapabilityExecutor.financeRiskOverview',
    description: input.description,
    sourceModels: input.sourceModels,
    dimensions: input.dimensions ?? [],
    permission: 'core:finance:view',
    template: input.template ?? 'template:finance_cost',
    outputField: input.outputField,
    valueType: input.valueType,
    resolver: {
      kind: 'domain_service',
      key: input.resolverKey,
      dimensionFields: input.dimensionFields ?? {},
      expression: input.expression,
      overallAggregation: input.overallAggregation ?? 'sum',
    },
    storeModel: input.storeModel,
    exceptionPolicy: input.exceptionPolicy,
    allowedTaskTypes: input.allowedTaskTypes ?? ['query', 'diagnosis'],
    ...(input.timeField ? { timeField: input.timeField } : {}),
    ...(input.timePolicy ? { timePolicy: input.timePolicy } : {}),
  });
}

function weightedRatio(field: string, denominator: number, weight: number) {
  return {
    op: 'multiply' as const,
    left: {
      op: 'clamp' as const,
      value: {
        op: 'divide' as const,
        numerator: { op: 'field' as const, field },
        denominator: { op: 'constant' as const, value: denominator },
        zero: 'error' as const,
      },
      min: 0,
      max: 1,
    },
    right: { op: 'constant' as const, value: weight },
  };
}

function dimension(
  dimensionKey: string,
  name: string,
  domain: string,
  aliases: string[],
  model: string,
  field: string,
  capabilityKey: string,
  permissions: string[],
  capabilityKeys: string[] = [],
  derivation?: Record<string, unknown>,
): AmiCoreBusinessDimensionContract {
  const allCapabilityKeys = [...new Set([capabilityKey, ...capabilityKeys])];
  return Object.freeze({
    dimensionKey,
    name,
    domain,
    aliases: Object.freeze(aliases),
    source: Object.freeze({ model, field }),
    ...(derivation ? { derivation: Object.freeze(structuredClone(derivation)) } : {}),
    capabilityKey,
    capabilityKeys: Object.freeze(allCapabilityKeys),
    permissions: Object.freeze(permissions),
  });
}
