import { Injectable } from '@nestjs/common';
import type { BusinessTaskDomain, BusinessTaskType } from '../agent/business-task/business-task.types.js';

export type SemanticMetricDefinition = {
  key: string;
  name: string;
  domain: BusinessTaskDomain;
  description: string;
  source: string[];
  filters: string[];
  allowedTaskTypes: BusinessTaskType[];
  sensitive: boolean;
  valueType?: 'money' | 'count' | 'percent' | 'score' | 'duration';
  defaultAggregation?: 'sum' | 'count' | 'avg' | 'ratio' | 'score';
  userVisibleDefinition?: string;
  auditDefinition?: string;
};

@Injectable()
export class SemanticMetricRegistryService {
  private readonly metrics: SemanticMetricDefinition[] = [
    {
      key: 'follow_up_priority_score',
      name: '客户优先跟进评分',
      domain: 'customer',
      description: '综合流失风险、复购机会、营销响应、LTV、最近到店和跟进状态的客户推荐评分。',
      source: ['Customer', 'CustomerPredictionSnapshot', 'Reservation', 'TerminalFollowUpTask'],
      filters: ['storeId=当前门店', 'Customer.deletedAt is null'],
      allowedTaskTypes: ['recommendation', 'ranking'],
      sensitive: false,
    },
    {
      key: 'product_sales_growth',
      name: '商品销量增长',
      domain: 'product',
      description: '对比当前窗口和上一窗口的商品销量/销售额增长。',
      source: ['Order', 'OrderItem', 'Product'],
      filters: ['storeId=当前门店', '订单状态 in completed/paid', 'OrderItem.itemType=product'],
      allowedTaskTypes: ['query', 'ranking'],
      sensitive: false,
    },
    {
      key: 'product_sales_quantity',
      name: '商品销量',
      domain: 'product',
      description: '商品类订单明细在指定周期内的销售数量。',
      source: ['OrderItem', 'ProductOrder', 'Product'],
      filters: ['storeId=当前门店', 'OrderItem.itemType=product', '订单状态 in completed/paid'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: false,
      valueType: 'count',
      defaultAggregation: 'sum',
      userVisibleDefinition: '指定周期内商品售出的数量。',
      auditDefinition: 'product_sales_quantity = sum(OrderItem.quantity) where itemType=product and order.status in paid/completed.',
    },
    {
      key: 'project_service_growth',
      name: '项目服务增长',
      domain: 'project',
      description: '对比当前窗口和上一窗口的项目服务次数、项目收入和服务客户数增长。',
      source: ['Order', 'OrderItem', 'Project'],
      filters: ['storeId=当前门店', '订单状态 in completed/paid', 'OrderItem.itemType=project'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: false,
    },
    {
      key: 'card_expiry_risk',
      name: '卡项到期风险',
      domain: 'card',
      description: '统计 active 且有剩余次数的客户次卡到期天数和剩余次数风险。',
      source: ['CustomerCard', 'Customer'],
      filters: ['storeId=当前门店', 'CustomerCard.status=active', 'remainingTimes>0'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis', 'forecast'],
      sensitive: false,
    },
    {
      key: 'card_usage_times',
      name: '卡项核销次数',
      domain: 'card',
      description: '按时间范围统计 CardUsageRecord.times，并按卡项、项目和客户聚合。',
      source: ['CardUsageRecord', 'Customer'],
      filters: ['storeId=当前门店', 'verifiedAt=查询周期'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: false,
    },
    {
      key: 'member_balance',
      name: '会员卡余额',
      domain: 'memberCard',
      description: '统计会员储值账户现金余额、赠送余额和充值/消费流水。',
      source: ['CustomerBalanceAccount', 'CustomerBalanceTransaction', 'Customer'],
      filters: ['storeId=当前门店', 'CustomerBalanceAccount.status=active'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: false,
    },
    {
      key: 'revenue',
      name: '收入',
      domain: 'business',
      description: '有效订单收入汇总，按门店和时间范围过滤。',
      source: ['Order'],
      filters: ['storeId=当前门店', '订单状态 in completed/paid'],
      allowedTaskTypes: ['query', 'diagnosis', 'ranking'],
      sensitive: false,
    },
    {
      key: 'paid_amount',
      name: '实收金额',
      domain: 'order',
      description: '支付成功记录的实收金额汇总。',
      source: ['PaymentRecord', 'ProductOrder'],
      filters: ['storeId=当前门店', 'PaymentRecord.status in paid/completed/success'],
      allowedTaskTypes: ['query', 'diagnosis', 'ranking'],
      sensitive: false,
      valueType: 'money',
      defaultAggregation: 'sum',
      userVisibleDefinition: '指定周期内已支付成功的收款金额。',
      auditDefinition: 'paid_amount = sum(PaymentRecord.amount) where status in paid/completed/success and order.storeId=current store.',
    },
    {
      key: 'order_count',
      name: '订单数',
      domain: 'order',
      description: '指定周期内有效订单数量。',
      source: ['ProductOrder'],
      filters: ['storeId=当前门店', '订单状态 in completed/paid'],
      allowedTaskTypes: ['query', 'diagnosis', 'ranking'],
      sensitive: false,
      valueType: 'count',
      defaultAggregation: 'count',
      userVisibleDefinition: '指定周期内已完成或已支付的订单数量。',
      auditDefinition: 'order_count = count(ProductOrder.id) where status in paid/completed and storeId=current store.',
    },
    {
      key: 'stock_risk_score',
      name: '库存风险评分',
      domain: 'inventory',
      description: '综合当前库存、安全库存、临期和销量的库存风险评分。',
      source: ['Product', 'StockBatch', 'StockMovement'],
      filters: ['storeId=当前门店', 'Product.deletedAt is null'],
      allowedTaskTypes: ['query', 'ranking', 'forecast'],
      sensitive: false,
    },
    {
      key: 'reservation_arrival_rate',
      name: '预约到店率',
      domain: 'reservation',
      description: '预约到店、取消和爽约的比例指标。',
      source: ['Reservation'],
      filters: ['storeId=当前门店'],
      allowedTaskTypes: ['query', 'diagnosis'],
      sensitive: false,
    },
    {
      key: 'reservation_count',
      name: '预约数',
      domain: 'reservation',
      description: '指定周期内预约数量。',
      source: ['Reservation'],
      filters: ['storeId=当前门店'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: false,
      valueType: 'count',
      defaultAggregation: 'count',
      userVisibleDefinition: '指定周期内门店预约数量。',
      auditDefinition: 'reservation_count = count(Reservation.id) where storeId=current store.',
    },
    {
      key: 'arrival_rate',
      name: '到店率',
      domain: 'reservation',
      description: '到店预约占全部有效预约的比例。',
      source: ['Reservation'],
      filters: ['storeId=当前门店', 'Reservation.status != cancelled'],
      allowedTaskTypes: ['query', 'diagnosis'],
      sensitive: false,
      valueType: 'percent',
      defaultAggregation: 'ratio',
      userVisibleDefinition: '已到店预约占有效预约的比例。',
      auditDefinition: 'arrival_rate = arrived reservations / non-cancelled reservations.',
    },
    {
      key: 'schedule_utilization_rate',
      name: '排班占用率',
      domain: 'schedule',
      description: '美容师排班中非 available/normal/正常/空闲 时段占比，用于识别忙闲和排班缺口。',
      source: ['Schedule', 'Beautician', 'Reservation'],
      filters: ['storeId=当前门店', 'date=查询周期'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis', 'forecast'],
      sensitive: false,
    },
    {
      key: 'staff_performance_score',
      name: '员工表现评分',
      domain: 'staff',
      description: '综合员工服务次数、销售额、提成、预约完成率和服务任务完成情况的表现评分。',
      source: ['Beautician', 'OrderItem', 'CommissionRecord', 'Reservation', 'ServiceTask', 'CardUsageRecord'],
      filters: ['storeId=当前门店', '查询周期内员工关联数据'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis', 'recommendation'],
      sensitive: true,
    },
    {
      key: 'gross_margin',
      name: '毛利',
      domain: 'finance',
      description: '有效订单净收入扣除商品成本、项目 BOM 标准耗材成本和提成后的经营毛利。',
      source: ['Order', 'OrderItem', 'Product', 'Project', 'ProjectBomItem', 'CommissionRecord', 'DailySettlement'],
      filters: ['storeId=当前门店', '订单状态 in completed/paid'],
      allowedTaskTypes: ['query', 'diagnosis', 'ranking'],
      sensitive: true,
    },
    {
      key: 'material_cost',
      name: '耗材成本',
      domain: 'finance',
      description: '商品销售成本和项目 BOM 标准耗材成本汇总。',
      source: ['OrderItem', 'Product', 'ProjectBomItem'],
      filters: ['storeId=当前门店', '订单状态 in completed/paid'],
      allowedTaskTypes: ['query', 'diagnosis', 'ranking'],
      sensitive: true,
    },
    {
      key: 'commission_cost',
      name: '提成成本',
      domain: 'finance',
      description: '指定周期内未取消 CommissionRecord.amount 汇总。',
      source: ['CommissionRecord'],
      filters: ['storeId=当前门店', 'CommissionRecord.status != cancelled'],
      allowedTaskTypes: ['query', 'diagnosis'],
      sensitive: true,
    },
    {
      key: 'net_revenue',
      name: '净收入',
      domain: 'finance',
      description: '实收金额扣除已完成退款后的经营净额。',
      source: ['PaymentRecord', 'RefundRecord', 'ProductOrder'],
      filters: ['storeId=当前门店', 'payment.status in paid/completed/success', 'refund.status in refunded/success/completed'],
      allowedTaskTypes: ['query', 'diagnosis'],
      sensitive: true,
    },
    {
      key: 'average_order_value',
      name: '客单价',
      domain: 'order',
      description: '有效订单净收入除以订单数，用于判断成交结构变化。',
      source: ['ProductOrder', 'PaymentRecord', 'RefundRecord'],
      filters: ['storeId=当前门店', '订单状态 in completed/paid'],
      allowedTaskTypes: ['query', 'diagnosis', 'ranking'],
      sensitive: false,
    },
    {
      key: 'business_anomaly_count',
      name: '经营异常数',
      domain: 'business',
      description: '收入、预约、库存、客户、营销等经营指标中达到阈值的异常数量。',
      source: ['ProductOrder', 'Reservation', 'Product', 'CustomerPredictionSnapshot', 'MarketingAutomationExecution'],
      filters: ['storeId=当前门店', '按业务阈值扫描'],
      allowedTaskTypes: ['query', 'diagnosis', 'forecast'],
      sensitive: false,
    },
    {
      key: 'ltv',
      name: '客户累计价值',
      domain: 'customer',
      description: '客户累计消费、到店和卡项资产综合价值。',
      source: ['Customer', 'ProductOrder', 'CustomerCard', 'CustomerBalanceAccount'],
      filters: ['storeId=当前门店', 'Customer.deletedAt is null'],
      allowedTaskTypes: ['query', 'ranking', 'recommendation', 'diagnosis'],
      sensitive: false,
    },
    {
      key: 'rfm_score',
      name: '客户活跃价值评分',
      domain: 'customer',
      description: '基于最近消费、消费频次和消费金额的客户活跃价值评分。',
      source: ['Customer', 'ProductOrder', 'Reservation'],
      filters: ['storeId=当前门店', 'Customer.deletedAt is null'],
      allowedTaskTypes: ['query', 'ranking', 'recommendation'],
      sensitive: false,
    },
    {
      key: 'product_sales_amount',
      name: '商品销售额',
      domain: 'product',
      description: '商品类订单明细在指定周期内的销售金额。',
      source: ['OrderItem', 'ProductOrder', 'Product'],
      filters: ['storeId=当前门店', 'OrderItem.itemType=product', '订单状态 in completed/paid'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: false,
    },
    {
      key: 'product_gross_margin',
      name: '商品毛利',
      domain: 'product',
      description: '商品销售额扣除商品成本后的毛利估算。',
      source: ['OrderItem', 'ProductOrder', 'Product'],
      filters: ['storeId=当前门店', 'OrderItem.itemType=product', 'Product.costPrice'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: true,
    },
    {
      key: 'slow_moving_days',
      name: '滞销天数',
      domain: 'product',
      description: '商品最近一次销售距今天数和库存占用情况。',
      source: ['Product', 'OrderItem', 'ProductOrder'],
      filters: ['storeId=当前门店', 'Product.deletedAt is null'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis', 'recommendation'],
      sensitive: false,
    },
    {
      key: 'promotion_fit_score',
      name: '活动适配评分',
      domain: 'product',
      description: '结合销量、库存、临期、毛利和客户偏好判断商品/项目是否适合做活动。',
      source: ['Product', 'Project', 'StockBatch', 'OrderItem', 'MarketingActivity'],
      filters: ['storeId=当前门店', '只生成建议，不自动发布活动'],
      allowedTaskTypes: ['recommendation', 'ranking', 'diagnosis'],
      sensitive: false,
    },
    {
      key: 'project_service_count',
      name: '项目服务次数',
      domain: 'project',
      description: '项目订单和次卡核销产生的服务次数。',
      source: ['OrderItem', 'CardUsageRecord', 'Project'],
      filters: ['storeId=当前门店', '查询周期内服务记录'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: false,
    },
    {
      key: 'project_gross_margin',
      name: '项目毛利',
      domain: 'project',
      description: '项目价格扣除 BOM 标准耗材成本后的毛利估算。',
      source: ['Project', 'ProjectBomItem', 'Product', 'OrderItem'],
      filters: ['storeId=当前门店', 'Project.deletedAt is null'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: true,
    },
    {
      key: 'service_completion_rate',
      name: '服务完成率',
      domain: 'serviceQuality',
      description: '服务任务完成数占服务任务总数的比例。',
      source: ['ServiceTask', 'Reservation'],
      filters: ['storeId=当前门店', '查询周期内服务任务'],
      allowedTaskTypes: ['query', 'diagnosis', 'ranking'],
      sensitive: false,
    },
    {
      key: 'care_fit_score',
      name: '护理适配评分',
      domain: 'project',
      description: '结合客户肤况、标签和项目属性形成的护理推荐适配评分。',
      source: ['CustomerHealthProfile', 'SkinTest', 'Project', 'Customer'],
      filters: ['storeId=当前门店', '仅返回建议，不替代专业判断'],
      allowedTaskTypes: ['recommendation', 'diagnosis'],
      sensitive: false,
    },
    {
      key: 'reservation_no_show_rate',
      name: '预约未到率',
      domain: 'reservation',
      description: '未到店或爽约预约占有效预约比例。',
      source: ['Reservation'],
      filters: ['storeId=当前门店', 'Reservation.status != cancelled'],
      allowedTaskTypes: ['query', 'diagnosis', 'ranking'],
      sensitive: false,
    },
    {
      key: 'reservation_confirm_rate',
      name: '预约确认率',
      domain: 'reservation',
      description: '已确认预约占全部预约比例。',
      source: ['Reservation'],
      filters: ['storeId=当前门店'],
      allowedTaskTypes: ['query', 'diagnosis'],
      sensitive: false,
    },
    {
      key: 'staff_idle_hours',
      name: '员工空闲时长',
      domain: 'schedule',
      description: '员工可预约/空闲排班时段时长。',
      source: ['Schedule', 'BeauticianAvailability', 'Reservation'],
      filters: ['storeId=当前门店', '排除请假和忙碌时段'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: false,
    },
    {
      key: 'skill_match_rate',
      name: '技能匹配率',
      domain: 'schedule',
      description: '预约项目与美容师项目技能匹配的比例。',
      source: ['Reservation', 'BeauticianProjectSkill', 'Project'],
      filters: ['storeId=当前门店'],
      allowedTaskTypes: ['query', 'diagnosis'],
      sensitive: false,
    },
    {
      key: 'staff_service_revenue',
      name: '员工服务收入',
      domain: 'staff',
      description: '员工关联服务、订单和核销产生的收入。',
      source: ['Beautician', 'OrderItem', 'Reservation', 'ServiceTask'],
      filters: ['storeId=当前门店', '按员工关联数据聚合'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: true,
    },
    {
      key: 'staff_commission_amount',
      name: '员工提成金额',
      domain: 'staff',
      description: '员工提成记录金额，区分待确认和已确认状态。',
      source: ['CommissionRecord', 'CommissionSettlement', 'Beautician'],
      filters: ['storeId=当前门店', 'CommissionRecord.status != cancelled'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: true,
    },
    {
      key: 'staff_customer_repurchase_rate',
      name: '员工客户复购率',
      domain: 'staff',
      description: '员工服务过的客户在后续窗口内再次消费或到店的比例。',
      source: ['ServiceTask', 'Reservation', 'ProductOrder', 'Customer'],
      filters: ['storeId=当前门店', '按员工服务客户聚合'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: true,
    },
    {
      key: 'refund_amount',
      name: '退款金额',
      domain: 'afterSales',
      description: '查询周期内已完成退款金额。',
      source: ['RefundRecord', 'ProductOrder'],
      filters: ['storeId=当前门店', 'RefundRecord.status in refunded/success/completed'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: true,
    },
    {
      key: 'refund_rate',
      name: '退款率',
      domain: 'afterSales',
      description: '退款金额占有效订单收入比例，或退款订单数占订单数比例。',
      source: ['RefundRecord', 'ProductOrder'],
      filters: ['storeId=当前门店', '退款与订单按同一周期统计'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: true,
    },
    {
      key: 'payment_method_ratio',
      name: '支付方式占比',
      domain: 'order',
      description: '按支付方式统计实收金额和笔数占比。',
      source: ['PaymentRecord', 'ProductOrder'],
      filters: ['storeId=当前门店', 'PaymentRecord.status in paid/completed/success'],
      allowedTaskTypes: ['query', 'diagnosis'],
      sensitive: false,
    },
    {
      key: 'card_writeoff_rate',
      name: '次卡核销率',
      domain: 'card',
      description: '客户次卡已核销次数占总次数比例。',
      source: ['CustomerCard', 'CardUsageRecord'],
      filters: ['storeId=当前门店', 'CustomerCard.status=active'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: false,
    },
    {
      key: 'balance_inactive_days',
      name: '储值沉睡天数',
      domain: 'memberCard',
      description: '会员卡余额账户最近一次消费距今天数。',
      source: ['CustomerBalanceAccount', 'CustomerBalanceTransaction'],
      filters: ['storeId=当前门店', 'CustomerBalanceAccount.status=active'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: true,
    },
    {
      key: 'stock_turnover_days',
      name: '库存周转天数',
      domain: 'inventory',
      description: '当前库存按近期日均销量预计可销售天数。',
      source: ['Product', 'StockMovement', 'OrderItem'],
      filters: ['storeId=当前门店', 'Product.deletedAt is null'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis', 'forecast'],
      sensitive: false,
    },
    {
      key: 'batch_expiry_risk',
      name: '批次临期风险',
      domain: 'inventory',
      description: '库存批次到期天数、数量和金额综合风险。',
      source: ['StockBatch', 'Product'],
      filters: ['storeId=当前门店', 'StockBatch.stock > 0'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis', 'forecast'],
      sensitive: false,
    },
    {
      key: 'supplier_delivery_cycle',
      name: '供应商交付周期',
      domain: 'supplyChain',
      description: '供应商订单或采购单从下单到到货的交付周期。',
      source: ['SupplySupplier', 'ProcurementOrder', 'PurchaseOrder'],
      filters: ['storeId=当前门店', '按供应商聚合'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: true,
    },
    {
      key: 'supplier_settlement_amount',
      name: '供应商结算金额',
      domain: 'supplyChain',
      description: '供应商待结算、已结算和异常结算金额。',
      source: ['SupplySupplier', 'SupplySettlement'],
      filters: ['storeId=当前门店'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: true,
    },
    {
      key: 'supplier_purchase_score',
      name: '供应链采购优先级',
      domain: 'supplyChain',
      description: '结合缺货、销量、安全库存、供应商价格和交期的采购优先级。',
      source: ['SupplySupplier', 'SupplyCatalogMapping', 'SupplyQuote', 'Product', 'StockMovement'],
      filters: ['storeId=当前门店', '只读建议，不创建采购单'],
      allowedTaskTypes: ['query', 'ranking', 'recommendation', 'diagnosis'],
      sensitive: true,
    },
    {
      key: 'campaign_conversion_rate',
      name: '活动转化率',
      domain: 'marketing',
      description: '活动曝光、线索、预约、成交之间的转化比例。',
      source: ['MarketingActivity', 'MarketingPageEvent', 'MarketingPageLead', 'MarketingPageAttribution'],
      filters: ['storeId=当前门店', '查询周期内活动数据'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: false,
    },
    {
      key: 'marketing_activity_count',
      name: '营销活动数',
      domain: 'marketing',
      description: '指定周期内营销活动草稿、已发布活动和进行中活动的数量及清单。',
      source: ['MarketingActivity'],
      filters: ['活动创建、更新或起止时间在查询周期内'],
      allowedTaskTypes: ['query', 'ranking', 'recommendation'],
      sensitive: false,
      valueType: 'count',
      defaultAggregation: 'count',
      userVisibleDefinition: '指定周期内可查看的营销活动清单。',
      auditDefinition: 'marketing_activity_count = count(MarketingActivity.id) by createdAt/updatedAt/startDate/endDate within query range.',
    },
    {
      key: 'campaign_revenue',
      name: '活动成交收入',
      domain: 'marketing',
      description: '归因到活动或推广页的成交收入。',
      source: ['MarketingActivity', 'MarketingPageAttribution', 'ProductOrder'],
      filters: ['storeId=当前门店', '按活动归因窗口聚合'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: true,
    },
    {
      key: 'promotion_claim_rate',
      name: '权益领取率',
      domain: 'promotion',
      description: '权益领取数量、使用数量和可用数量之间的比例。',
      source: ['Promotion', 'MarketingActivity', 'MarketingPageLead'],
      filters: ['storeId=当前门店或全局权益', 'Promotion.status=active'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: false,
    },
    {
      key: 'automation_touch_success_rate',
      name: '自动化触达成功率',
      domain: 'automation',
      description: '自动化策略执行、触达、转化和归因收入的效果指标。',
      source: ['MarketingAutomationStrategy', 'MarketingAutomationExecution', 'MarketingAutomationTouch', 'MarketingAttribution'],
      filters: ['storeId=当前门店', '查询周期内自动化执行记录'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: false,
    },
    {
      key: 'customer_app_active_count',
      name: '客户小程序活跃数',
      domain: 'customerApp',
      description: '客户小程序身份和事件活跃数量。',
      source: ['CustomerAppIdentity', 'CustomerAppEvent'],
      filters: ['storeId=当前门店', 'source=ami_glow'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: false,
    },
    {
      key: 'customer_app_bind_rate',
      name: '客户小程序绑定率',
      domain: 'customerApp',
      description: '已绑定客户身份占小程序身份数量的比例。',
      source: ['CustomerAppIdentity'],
      filters: ['storeId=当前门店'],
      allowedTaskTypes: ['query', 'diagnosis'],
      sensitive: false,
    },
    {
      key: 'channel_conversion_rate',
      name: '渠道转化率',
      domain: 'channel',
      description: '按渠道统计访问、线索、预约和成交转化。',
      source: ['CustomerAppEvent', 'MarketingPageEvent', 'MarketingPageLead', 'MarketingPageAttribution'],
      filters: ['storeId=当前门店', '按 channel/source 聚合'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: false,
    },
    {
      key: 'terminal_failure_rate',
      name: '终端失败率',
      domain: 'terminal',
      description: '终端设备异常、离线、对话失败或需要澄清的比例。',
      source: ['TerminalDevice', 'TerminalConversation', 'AiAuditLog'],
      filters: ['storeId=当前门店'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: false,
    },
    {
      key: 'terminal_conversation_count',
      name: '终端会话数',
      domain: 'terminal',
      description: '终端会话数量、消息数量和高频失败问题。',
      source: ['TerminalConversation'],
      filters: ['storeId=当前门店', '按日期和设备聚合'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: false,
    },
    {
      key: 'store_rank_score',
      name: '门店综合排名分',
      domain: 'store',
      description: '门店收入、订单、客户、库存、转化和异常综合评分。',
      source: ['Store', 'ProductOrder', 'Customer', 'Reservation', 'Product', 'MarketingPageAttribution'],
      filters: ['仅查询当前用户授权门店'],
      allowedTaskTypes: ['query', 'ranking', 'diagnosis'],
      sensitive: true,
    },
  ];

  list() {
    return [...this.metrics];
  }

  findByKey(key: string) {
    return this.metrics.find((metric) => metric.key === key);
  }

  match(keys: string[], taskType?: BusinessTaskType) {
    return keys
      .map((key) => this.findByKey(key))
      .filter((metric): metric is SemanticMetricDefinition => Boolean(metric))
      .filter((metric) => !taskType || metric.allowedTaskTypes.includes(taskType));
  }
}
