import type { BrainSemanticIntentKind } from '../cognition/brain-semantic-intent.types.js';

export interface BrainCapabilityRetrieverCase {
  id: string;
  question: string;
  expectedKey: string;
  domain: string;
  intent: BrainSemanticIntentKind;
  metricDefinitionKey: string;
  entityDefinitionKey: string;
}

const groups: Array<Omit<BrainCapabilityRetrieverCase, 'id' | 'question'> & { questions: string[] }> = [
  {
    expectedKey: 'product_sales_ranking',
    domain: 'sales',
    intent: 'ranking',
    metricDefinitionKey: 'metric.product_sales_quantity',
    entityDefinitionKey: 'entity.product',
    questions: [
      '本月商品销售排行',
      '这个月产品销量榜',
      '最近30天哪些商品卖得最好',
      '商品销售数量从高到低',
      '产品卖出件数排行榜',
      '只看商品销量不要看员工',
      '护理项目先不看，给我商品榜',
      '本月商品销售冠军是谁',
      '哪些产品最畅销',
      '商品销量前十名',
      '按销售数量排商品',
      '看一下零售产品热销榜',
      '门店产品销售排名',
      '本周商品卖出数量排行',
      '昨天商品销量排序',
      '商品销售排行不要混入实收金额',
      '产品销量榜并排除员工表现',
      '卖得最多的商品有哪些',
      '商品出单数量榜',
      '按件数统计产品销售',
      '商品销量TOP10',
      '本季度产品热销排行',
      '哪款商品卖得最少',
      '商品销售倒序清单',
      '产品销量比较排行',
      '商品销售表现列表',
      '门店零售商品销量榜',
      '商品卖出次数排名',
      '产品销售数量分析排行',
      '本月商品销量，不要订单收入',
    ],
  },
  {
    expectedKey: 'project_service_ranking',
    domain: 'service',
    intent: 'ranking',
    metricDefinitionKey: 'metric.project_service_count',
    entityDefinitionKey: 'entity.project',
    questions: [
      '本月项目服务排行',
      '护理项目服务次数榜',
      '哪些项目做得最多',
      '项目核销服务数量排名',
      '门店项目受欢迎排行',
      '不要商品销量，只看服务项目',
      '美容项目次数前十',
      '本周项目服务量排序',
      '项目成交次数排行榜',
      '护理服务项目热度榜',
      '按服务次数排列项目',
      '项目服务量TOP10',
      '最近30天热门项目',
      '哪些护理项目最常做',
      '项目服务次数从高到低',
      '项目排行不要混入员工绩效',
      '本季度项目服务榜',
      '项目到店服务数量排行',
      '服务项目使用次数排名',
      '项目销售先不看，只看实际服务',
      '门店护理项目排行榜',
      '项目服务表现列表',
      '昨天项目服务数量排行',
      '哪项服务做得最少',
      '项目服务次数倒序',
      '热门护理项目清单',
      '项目服务频次比较',
      '按项目统计服务量',
      '本月项目次数，不要订单收入',
      '服务项目热度排名',
    ],
  },
  {
    expectedKey: 'staff_performance_ranking',
    domain: 'staff',
    intent: 'ranking',
    metricDefinitionKey: 'metric.staff_performance_score',
    entityDefinitionKey: 'entity.beautician',
    questions: [
      '本月员工表现排行',
      '美容师业绩排名',
      '技师绩效排行榜',
      '员工综合表现从高到低',
      '谁的员工表现最好',
      '不要商品销量，只看员工排行',
      '本周美容师绩效榜',
      '员工服务表现前十',
      '技师工作表现排名',
      '美容师综合得分榜',
      '按绩效分数排列员工',
      '员工表现TOP10',
      '最近30天员工表现',
      '哪些美容师表现突出',
      '员工绩效分数排序',
      '员工排行不要混入项目次数',
      '本季度技师表现榜',
      '美容师工作质量排行',
      '员工服务业绩排名',
      '人员绩效比较清单',
      '门店员工表现排行榜',
      '员工绩效表现列表',
      '昨天美容师表现排行',
      '谁的绩效最低',
      '员工表现倒序',
      '优秀美容师清单',
      '员工表现分数比较',
      '按美容师统计绩效',
      '本月员工表现，不要订单收入',
      '技师综合表现排名',
    ],
  },
  {
    expectedKey: 'order_revenue_analysis',
    domain: 'finance',
    intent: 'query',
    metricDefinitionKey: 'metric.paid_amount',
    entityDefinitionKey: 'entity.order',
    questions: [
      '本月订单收入分析',
      '这个月订单实收多少',
      '订单收入和订单数',
      '分析已支付订单金额',
      '门店订单营收汇总',
      '不要员工排行，只看订单收入',
      '本周订单实收分析',
      '订单平均客单价是多少',
      '已支付订单收入统计',
      '订单收入结构分析',
      '看订单金额和数量',
      '最近30天订单营收',
      '订单实收金额汇总',
      '本季度订单收入情况',
      '订单平均价值分析',
      '订单收入不要混入商品销量',
      '昨天订单实收多少',
      '支付完成订单金额',
      '订单营收指标清单',
      '按订单统计收入',
      '门店订单收入概览',
      '订单收入表现',
      '已支付订单数量和金额',
      '订单客单价是多少',
      '订单营收趋势先给汇总',
      '收入分析限定订单口径',
      '订单实收与单量',
      '本月订单收入，不要库存风险',
      '订单支付金额分析',
      '经营订单收入汇总',
    ],
  },
  {
    expectedKey: 'inventory_risk_ranking',
    domain: 'inventory',
    intent: 'ranking',
    metricDefinitionKey: 'metric.stock_risk_score',
    entityDefinitionKey: 'entity.product',
    questions: [
      '本月库存风险排行',
      '哪些商品库存风险最高',
      '产品库存风险榜',
      '库存预警商品从高到低',
      '商品缺货临期风险排名',
      '不要销售排行，只看库存风险',
      '本周库存风险前十',
      '产品库存危险程度排序',
      '库存风险商品清单',
      '门店库存预警排行',
      '按库存风险分数排列商品',
      '库存风险TOP10',
      '最近库存风险最高的产品',
      '哪些商品最需要关注库存',
      '商品库存风险分排序',
      '库存排行不要混入订单收入',
      '本季度库存风险榜',
      '低库存和临期商品排名',
      '商品周转风险排行',
      '库存健康风险比较',
      '门店商品库存风险排行榜',
      '库存风险表现列表',
      '昨天库存风险排行',
      '风险最低的库存商品',
      '库存风险倒序',
      '高风险库存商品清单',
      '商品库存风险比较',
      '按产品统计库存风险',
      '本月库存风险，不要员工表现',
      '库存预警程度排名',
    ],
  },
];

export const BRAIN_CAPABILITY_RETRIEVER_CASES: readonly BrainCapabilityRetrieverCase[] = groups.flatMap(
  ({ questions, ...group }, groupIndex) =>
    questions.map((question, questionIndex) => ({
      ...group,
      id: `${group.expectedKey}_${groupIndex + 1}_${questionIndex + 1}`,
      question,
    })),
);
