import type { AgentV2CapabilityManifest, AgentV2FieldPolicy } from './agent-v2-capability.types.js';

const VERSION = '2026-07-03.p0';

const allow = (field: string, label: string, reason = '业务查询核心字段'): AgentV2FieldPolicy => ({
  field,
  label,
  visibility: 'allow',
  reason,
});

const mask = (field: string, label: string, reason = '可能包含客户或内部说明，默认摘要展示'): AgentV2FieldPolicy => ({
  field,
  label,
  visibility: 'mask',
  reason,
});

const orderRecordPolicies = [
  allow('orderNo', '订单编号', '用于定位订单'),
  allow('customerName', '客户'),
  allow('storeName', '门店'),
  allow('itemSummary', '明细'),
  allow('netAmountText', '实收金额'),
  allow('discountAmountText', '优惠金额'),
  allow('payMethodLabel', '支付方式'),
  allow('statusLabel', '订单状态'),
  allow('createdAt', '下单时间'),
  mask('remark', '备注'),
];

export const AGENT_V2_CAPABILITY_MANIFESTS: AgentV2CapabilityManifest[] = [
  {
    capabilityId: 'inventory.scrap.records.list',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '已发生报废记录查询',
    description: '查询已经发生的库存报废流水，不回答临期风险、报废风险或建议处理库存。',
    domain: 'inventory',
    businessObject: 'StockMovement',
    personaCodes: ['manager', 'inventory'],
    actions: ['list', 'summary', 'analyze'],
    sourceModels: ['StockMovement', 'Product', 'Store', 'User', 'StockBatch'],
    eventTypes: ['scrap_out'],
    outputKinds: ['table', 'evidence_panel'],
    executor: {
      type: 'business_record_query',
      tool: 'business.record.query',
      queryKey: 'inventory.scrap.records',
    },
    storeScope: 'required',
    permissionCodes: ['core:inventory:view'],
    fieldPolicies: [
      allow('movementId', '流水ID', '用于定位业务记录'),
      allow('productName', '产品名称'),
      allow('scrapQuantityText', '报废数量'),
      allow('lossAmountText', '损耗金额', '库存损耗统计字段'),
      allow('operatorName', '操作人', '当前能力需要展示报废办理人员'),
      allow('occurredAt', '发生时间'),
      mask('remark', '备注'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['本周有哪些报废产品', '今天已经报废了哪些商品', '列出本月报废记录', '报废流水有哪些'],
    negativeExamples: ['哪些产品快报废了', '哪些商品有临期风险', '帮我报废这批面膜'],
    triggerKeywords: ['报废记录', '报废流水', '已经报废', '已报废', '报废产品', '报废商品'],
    boundaryNotes: [
      '只查 movementType=scrap_out 的已发生库存流水。',
      '不能用临期、过期、低库存风险数据替代已发生报废记录。',
    ],
  },
  {
    capabilityId: 'inventory.expiring-risk.list',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '临期与报废风险清单',
    description: '查询未来可能临期、过期、缺货或有报废风险的库存，不代表已经发生报废。',
    domain: 'inventory',
    businessObject: 'StockBatch',
    personaCodes: ['manager', 'inventory', 'reception'],
    actions: ['list', 'diagnose', 'recommend'],
    sourceModels: ['Product', 'StockBatch', 'StockMovement'],
    eventTypes: ['expiry_risk', 'low_stock'],
    outputKinds: ['table', 'evidence_panel', 'action_card'],
    executor: {
      type: 'business_query',
      tool: 'inventory.risk.rank',
      queryKey: 'inventory.expiring-risk',
    },
    storeScope: 'required',
    permissionCodes: ['core:inventory:view'],
    fieldPolicies: [
      allow('productName', '产品名称'),
      allow('expiryDate', '到期日期', '风险判断必要字段'),
      allow('stockQty', '当前库存', '风险判断必要字段'),
      allow('riskReason', '风险原因', '解释风险来源'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['哪些产品快报废了', '近期有哪些临期库存产品', '哪些商品有过期风险', '库存报废风险最高的是哪些'],
    negativeExamples: ['本周有哪些报废产品', '今天已经报废了哪些商品', '报废流水有哪些'],
    triggerKeywords: ['临期', '快过期', '即将过期', '报废风险', '过期风险', '库存风险'],
    boundaryNotes: [
      '这是风险预测，不是已发生报废记录。',
      '回答时必须明确“风险/预计/可能”，不能写成已报废。',
    ],
  },
  {
    capabilityId: 'inventory.stock.operation.draft',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '库存操作草稿',
    description: '从自然语言生成出库、盘点或报废草稿，不直接写入库存。',
    domain: 'inventory',
    businessObject: 'StockMovementDraft',
    personaCodes: ['manager', 'inventory'],
    actions: ['draft'],
    sourceModels: ['Product', 'StockMovement'],
    eventTypes: ['manual_outbound', 'scrap_out', 'stocktake'],
    outputKinds: ['action_card', 'evidence_panel'],
    executor: {
      type: 'business_action_draft',
      tool: 'business.action.draft',
      queryKey: 'inventory.stock-operation-draft',
    },
    storeScope: 'required',
    permissionCodes: ['core:inventory:adjustment'],
    fieldPolicies: [
      allow('productName', '产品名称', '草稿确认必要字段'),
      allow('quantity', '数量', '草稿确认必要字段'),
      allow('reason', '原因', '草稿确认必要字段'),
      { field: 'operatorId', label: '操作人ID', visibility: 'deny', reason: '执行前由授权上下文注入，不由模型指定' },
    ],
    riskLevel: 'medium',
    releaseStrategy: 'approval_required',
    examples: ['帮我报废这批过期面膜', '语音录入出库草稿', '生成盘点调整草稿'],
    negativeExamples: ['本周有哪些报废产品', '哪些产品快报废了'],
    triggerKeywords: ['帮我报废', '生成报废草稿', '出库草稿', '盘点草稿', '库存操作草稿'],
    boundaryNotes: ['只能生成待确认草稿，不能直接写入库存。'],
  },
  {
    capabilityId: 'order.detail.lookup',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '订单详情定位',
    description: '按订单编号查询单笔订单详情、订单明细、支付和退款记录，不判断是否进入日结或消费记录同步。',
    domain: 'order',
    businessObject: 'ProductOrder',
    personaCodes: ['manager', 'finance', 'reception'],
    actions: ['lookup'],
    sourceModels: ['ProductOrder', 'OrderItem', 'PaymentRecord', 'RefundRecord', 'Customer', 'Store'],
    eventTypes: ['order_lookup'],
    outputKinds: ['table', 'evidence_panel'],
    executor: { type: 'business_detail_query', tool: 'business.detail.query', queryKey: 'order.detail.lookup' },
    storeScope: 'required',
    permissionCodes: ['core:order:view'],
    fieldPolicies: [
      allow('orderNo', '订单编号', '用于定位订单'),
      allow('orderKindLabel', '订单类型'),
      allow('customerName', '客户'),
      allow('storeName', '门店'),
      allow('itemName', '明细'),
      allow('itemTypeLabel', '类型'),
      allow('quantityText', '数量'),
      allow('lineNetAmountText', '实收'),
      allow('methodLabel', '支付方式'),
      allow('statusLabel', '状态'),
      allow('createdAt', '下单时间'),
      mask('remark', '备注'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['看一下订单 POMQPDGTF8', '订单 PO1781893252477 详情', '查一下这笔订单明细', '这个订单支付和退款记录是什么'],
    negativeExamples: ['订单 POMQPDGTF8 有没有进入财务日结', '项目订单为什么没有同步到客户消费记录', '今天有哪些商品订单'],
    triggerKeywords: ['订单详情', '订单明细', '查订单', '看订单', '订单号'],
    boundaryNotes: [
      '这是单笔订单详情定位能力，只按订单编号展示订单、明细、支付和退款。',
      '如用户问是否进日结、是否同步客户消费记录，应切换到财务或同步诊断能力。',
    ],
  },
  {
    capabilityId: 'order.product.records.list',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '商品订单记录查询',
    description: '查询商品销售、商品收银和商品订单明细，不混入项目订单、会员卡或次卡开卡。',
    domain: 'order',
    businessObject: 'ProductOrder',
    personaCodes: ['manager', 'finance', 'reception'],
    actions: ['list', 'summary', 'analyze'],
    sourceModels: ['ProductOrder', 'OrderItem', 'PaymentRecord', 'RefundRecord', 'Customer', 'Store'],
    eventTypes: ['product_order', 'paid_order'],
    outputKinds: ['table', 'evidence_panel'],
    executor: { type: 'business_record_query', tool: 'business.record.query', queryKey: 'order.product.records' },
    storeScope: 'required',
    permissionCodes: ['core:order:products'],
    fieldPolicies: orderRecordPolicies,
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['今天有哪些商品订单', '商品销售订单明细', 'POMQPDGTF8 这个商品订单是什么', '本月商品收银记录'],
    negativeExamples: ['项目订单有哪些', '次卡开卡订单', '会员卡充值流水'],
    triggerKeywords: ['商品订单', '商品销售', '商品收银', '产品订单', '产品销售'],
    boundaryNotes: ['只查商品订单和商品型订单明细，不回答项目服务订单、会员卡充值或次卡开卡。'],
  },
  {
    capabilityId: 'order.project.records.list',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '项目订单记录查询',
    description: '查询项目服务订单、项目收银和项目订单明细，不混入商品销售或卡类订单。',
    domain: 'order',
    businessObject: 'ProductOrder',
    personaCodes: ['manager', 'finance', 'reception'],
    actions: ['list', 'summary', 'analyze'],
    sourceModels: ['ProductOrder', 'OrderItem', 'PaymentRecord', 'RefundRecord', 'Customer', 'Store'],
    eventTypes: ['project_order', 'paid_order'],
    outputKinds: ['table', 'evidence_panel'],
    executor: { type: 'business_record_query', tool: 'business.record.query', queryKey: 'order.project.records' },
    storeScope: 'required',
    permissionCodes: ['core:order:projects'],
    fieldPolicies: orderRecordPolicies,
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['项目订单 PO1781893252477 在哪里', '今天项目订单明细', '项目收银记录', '本月服务项目订单'],
    negativeExamples: ['商品订单有哪些', '次卡核销记录', '会员卡充值'],
    triggerKeywords: ['项目订单', '服务订单', '项目收银', '服务项目订单'],
    boundaryNotes: ['项目订单是收银订单的一种，不等同于次卡核销服务记录。'],
  },
  {
    capabilityId: 'order.member-card.records.list',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '会员卡开卡与充值记录查询',
    description: '查询会员卡开卡、充值、赠送金额等储值类订单，不混入次卡开卡。',
    domain: 'memberCard',
    businessObject: 'ProductOrder',
    personaCodes: ['manager', 'finance', 'reception'],
    actions: ['list', 'summary', 'analyze'],
    sourceModels: ['ProductOrder', 'OrderItem', 'PaymentRecord', 'CustomerCard', 'Customer', 'Store'],
    eventTypes: ['member_card_recharge', 'member_card_open'],
    outputKinds: ['table', 'evidence_panel'],
    executor: { type: 'business_record_query', tool: 'business.record.query', queryKey: 'order.member-card.records' },
    storeScope: 'required',
    permissionCodes: ['core:order:member-cards'],
    fieldPolicies: orderRecordPolicies,
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['今天会员卡充值记录', '会员开卡订单有哪些', '储值卡充值明细', '会员卡办理记录'],
    negativeExamples: ['次卡开卡订单', '次卡核销记录', '商品订单'],
    triggerKeywords: ['会员卡', '储值卡', '会员开卡', '开卡充值', '充值记录', '储值'],
    boundaryNotes: ['会员卡是储值余额业务；次卡是按次数核销业务，两者必须分开。'],
  },
  {
    capabilityId: 'order.card-package.records.list',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '次卡开卡订单查询',
    description: '查询次卡/套餐开卡订单和购买记录，不回答次卡核销服务流水。',
    domain: 'card',
    businessObject: 'CustomerCard',
    personaCodes: ['manager', 'finance', 'reception'],
    actions: ['list', 'summary', 'analyze'],
    sourceModels: ['CustomerCard', 'Card', 'ProductOrder', 'OrderItem', 'Customer', 'Store'],
    eventTypes: ['card_package_order', 'card_open'],
    outputKinds: ['table', 'evidence_panel'],
    executor: { type: 'business_record_query', tool: 'business.record.query', queryKey: 'order.card-package.records' },
    storeScope: 'required',
    permissionCodes: ['core:order:card-orders'],
    fieldPolicies: [
      allow('cardName', '次卡'),
      allow('customerName', '客户'),
      allow('storeName', '门店'),
      allow('totalTimes', '总次数'),
      allow('remainingTimes', '剩余次数'),
      allow('paidAmountText', '实付金额'),
      allow('operatorName', '办理人员'),
      allow('createdAt', '开卡时间'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['今天新增次卡订单', '次卡开卡管理有哪些订单', '次卡购买记录', '套餐卡开卡明细'],
    negativeExamples: ['次卡核销记录', '项目订单', '会员卡充值记录'],
    triggerKeywords: ['次卡开卡', '次卡订单', '次卡购买', '套餐卡', '开次卡'],
    boundaryNotes: ['次卡开卡订单记录客户买了什么卡；次卡核销记录客户用了哪次服务。'],
  },
  {
    capabilityId: 'cashier.payment.records.list',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '收银支付与退款流水查询',
    description: '查询收银支付、退款和支付方式流水，用于对账，不替代订单商品/项目明细。',
    domain: 'finance',
    businessObject: 'PaymentRecord',
    personaCodes: ['manager', 'finance', 'reception'],
    actions: ['list', 'summary', 'analyze'],
    sourceModels: ['PaymentRecord', 'RefundRecord', 'ProductOrder', 'Customer', 'Store'],
    eventTypes: ['payment', 'refund'],
    outputKinds: ['table', 'evidence_panel'],
    executor: { type: 'business_record_query', tool: 'business.record.query', queryKey: 'cashier.payment.records' },
    storeScope: 'required',
    permissionCodes: ['core:finance:view'],
    fieldPolicies: [
      allow('paymentNo', '支付流水号'),
      allow('orderNo', '订单编号'),
      allow('customerName', '客户'),
      allow('methodLabel', '支付方式'),
      allow('amountText', '支付金额'),
      allow('statusLabel', '状态'),
      allow('paidAt', '支付时间'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['今天收银流水', '微信支付流水有哪些', '订单 POMQPDGTF8 有没有进财务', '本月退款记录'],
    negativeExamples: ['商品订单明细', '项目订单明细', '客户消费记录'],
    triggerKeywords: ['收银流水', '支付流水', '付款记录', '退款记录', '对账', '支付方式'],
    boundaryNotes: ['收银流水回答钱是否入账；订单明细回答买了什么。'],
  },
  {
    capabilityId: 'card.usage.records.list',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '次卡核销记录查询',
    description: '查询客户使用次卡核销服务的记录，包含核销人、终端/管理端来源和识别收入。',
    domain: 'card',
    businessObject: 'CardUsageRecord',
    personaCodes: ['manager', 'finance', 'reception', 'beautician'],
    actions: ['list', 'summary', 'analyze'],
    sourceModels: ['CardUsageRecord', 'CustomerCard', 'Card', 'Project', 'Customer', 'User', 'Beautician', 'TerminalDevice'],
    eventTypes: ['card_usage'],
    outputKinds: ['table', 'evidence_panel'],
    executor: { type: 'business_record_query', tool: 'business.record.query', queryKey: 'card.usage.records' },
    storeScope: 'required',
    permissionCodes: ['core:order:card-usage'],
    fieldPolicies: [
      allow('cardName', '次卡'),
      allow('customerName', '客户'),
      allow('projectName', '使用项目'),
      allow('timesText', '本次核销'),
      allow('remainingTimesText', '剩余次数'),
      allow('recognizedAmountText', '识别收入'),
      allow('operatorName', '核销人'),
      allow('entrySourceLabel', '核销入口'),
      allow('verifiedAt', '核销时间'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['今天次卡核销记录', '刚才系统管理员核销的次卡在哪里', '次卡核销服务有没有自动入库', '本月核销明细'],
    negativeExamples: ['次卡开卡订单', '会员卡充值记录', '项目订单'],
    triggerKeywords: ['次卡核销', '核销记录', '核销流水', '核销服务', '核销人'],
    boundaryNotes: ['核销入口可能来自管理端或智能终端，不能只按终端设备判断。'],
  },
  {
    capabilityId: 'finance.daily-settlement.metric',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '日结报表指标查询',
    description: '查询财务日结报表的营收、退款、订单数、客数、毛利和提成等汇总指标。',
    domain: 'finance',
    businessObject: 'DailySettlement',
    personaCodes: ['manager', 'finance'],
    actions: ['summary', 'analyze'],
    sourceModels: ['DailySettlement', 'PaymentRecord', 'RefundRecord', 'ProductOrder', 'CommissionRecord'],
    eventTypes: ['daily_settlement'],
    outputKinds: ['kpi', 'table', 'evidence_panel'],
    executor: { type: 'business_metric_query', tool: 'business.metric.query', queryKey: 'finance.daily-settlement.metric' },
    storeScope: 'required',
    permissionCodes: ['core:finance:view'],
    fieldPolicies: [
      allow('settleDate', '日结日期'),
      allow('totalRevenueText', '实收'),
      allow('refundAmountText', '退款'),
      allow('netRevenueText', '净收'),
      allow('orderCount', '订单数'),
      allow('customerCount', '客户数'),
      allow('grossProfitText', '毛利'),
      allow('commissionTotalText', '提成'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['今天日结报表是多少', '订单 POMQPDGTF8 为什么没有进日结', '本月财务日结收入', '日结报表营收'],
    negativeExamples: ['商品订单明细', '单个客户消费记录'],
    triggerKeywords: ['日结', '日结报表', '财务报表', '每日结算', '净收', '实收'],
    boundaryNotes: ['日结是财务汇总口径；如要定位单个订单是否入账，应联动收银支付流水。'],
  },
  {
    capabilityId: 'finance.revenue.trend',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '营业额趋势查询',
    description: '按业务日期统计营业额趋势，用于回答近几天、本周或本月营收走势，不替代单日结报表。',
    domain: 'finance',
    businessObject: 'ProductOrder',
    personaCodes: ['manager', 'finance'],
    actions: ['summary', 'analyze'],
    sourceModels: ['ProductOrder', 'Store'],
    eventTypes: ['paid_order'],
    outputKinds: ['kpi', 'chart', 'table', 'evidence_panel'],
    executor: { type: 'business_trend_query', tool: 'business.trend.query', queryKey: 'finance.revenue.trend' },
    storeScope: 'required',
    permissionCodes: ['core:finance:view'],
    fieldPolicies: [
      allow('date', '日期'),
      allow('revenueText', '营业额'),
      allow('orderCount', '订单数'),
      allow('avgOrderValueText', '客单价'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['最近三天营业额趋势怎么样', '近7天营收走势', '本周收入变化', '这个月营业额变化趋势'],
    negativeExamples: ['今天日结报表是多少', '订单 POMQPDGTF8 为什么没有进日结', '今天现金微信支付宝各收了多少'],
    triggerKeywords: ['营业额趋势', '营收走势', '收入趋势', '收入变化', '营业额变化', '走势', '趋势'],
    boundaryNotes: [
      '趋势能力按 ProductOrder 订单日期聚合，回答走势和变化。',
      '单日财务确认、日结口径或单笔订单入账问题不走趋势能力。',
    ],
  },
  {
    capabilityId: 'finance.payment-method-breakdown.metric',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '支付方式收款拆分指标',
    description: '按支付方式统计现金、微信、支付宝、银行卡、会员卡余额等收款金额和订单数。',
    domain: 'finance',
    businessObject: 'PaymentRecord',
    personaCodes: ['manager', 'finance', 'reception'],
    actions: ['summary', 'analyze'],
    sourceModels: ['PaymentRecord', 'ProductOrder', 'RefundRecord', 'Store'],
    eventTypes: ['payment'],
    outputKinds: ['kpi', 'table', 'evidence_panel'],
    executor: { type: 'business_metric_query', tool: 'business.metric.query', queryKey: 'finance.payment-method-breakdown.metric' },
    storeScope: 'required',
    permissionCodes: ['core:finance:view'],
    fieldPolicies: [
      allow('methodLabel', '支付方式'),
      allow('revenueText', '收款金额'),
      allow('paymentCount', '支付笔数'),
      allow('orderCount', '订单数'),
      allow('latestPaidAt', '最近收款时间'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['今天现金、微信、支付宝各收了多少', '今天现金收了多少，微信支付宝各多少', '今天各支付方式收款', '支付方式拆分'],
    negativeExamples: ['商品订单明细', '项目订单明细', '退款明细有哪些'],
    triggerKeywords: ['现金', '微信', '支付宝', '支付方式', '各收', '收了多少', '收款拆分'],
    boundaryNotes: ['这是收银支付方式聚合口径；如要看具体订单明细，应切换订单记录能力。'],
  },
  {
    capabilityId: 'finance.refund.metric',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '退款笔数与金额指标',
    description: '统计指定时间内退款笔数、退款金额，并列出近期退款记录用于核对。',
    domain: 'finance',
    businessObject: 'RefundRecord',
    personaCodes: ['manager', 'finance'],
    actions: ['summary', 'analyze'],
    sourceModels: ['RefundRecord', 'ProductOrder', 'Customer', 'Store'],
    eventTypes: ['refund'],
    outputKinds: ['kpi', 'table', 'evidence_panel'],
    executor: { type: 'business_metric_query', tool: 'business.metric.query', queryKey: 'finance.refund.metric' },
    storeScope: 'required',
    permissionCodes: ['core:finance:view'],
    fieldPolicies: [
      allow('refundNo', '退款流水号'),
      allow('orderNo', '订单编号'),
      allow('customerName', '客户'),
      allow('amountText', '退款金额'),
      allow('statusLabel', '退款状态'),
      allow('refundedAt', '退款时间'),
      mask('reason', '退款原因'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['今天退款有几笔，金额多少', '本月退款金额', '今天退款记录', '有没有大额异常退款'],
    negativeExamples: ['退款怎么操作', '帮我退款这笔订单'],
    triggerKeywords: ['退款', '退款金额', '退款有几笔', '异常退款', '退款记录'],
    boundaryNotes: ['这是已发生退款统计，不执行退款。涉及退款操作必须走人工确认或阻断。'],
  },
  {
    capabilityId: 'finance.staff-commission.metric',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '员工提成汇总指标',
    description: '按系统用户 staffUserId 汇总员工提成总额、记录数和排名，beauticianId 仅作为历史兼容。',
    domain: 'finance',
    businessObject: 'CommissionRecord',
    personaCodes: ['manager', 'finance'],
    actions: ['summary', 'analyze'],
    sourceModels: ['CommissionRecord', 'User', 'Beautician', 'CommissionRule', 'ProductOrder', 'OrderItem'],
    eventTypes: ['commission'],
    outputKinds: ['kpi', 'table', 'evidence_panel'],
    executor: { type: 'business_metric_query', tool: 'business.metric.query', queryKey: 'finance.staff-commission.metric' },
    storeScope: 'required',
    permissionCodes: ['core:finance:view'],
    fieldPolicies: [
      allow('staffName', '员工'),
      allow('commissionAmountText', '提成金额'),
      allow('recordCount', '提成笔数'),
      allow('sourceAmountText', '计提金额'),
      allow('latestCreatedAt', '最近生成时间'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['本月员工总提成大概多少', '这个月提成最高的是谁，大概多少', '我的提成这个月大概是多少', '昨天的提成是多少'],
    negativeExamples: ['提成规则怎么配置', '修改提成规则'],
    triggerKeywords: ['总提成', '提成最高', '我的提成', '提成多少', '员工提成', '人员提成'],
    boundaryNotes: ['提成汇总必须以系统用户为主体，不能再只按美容师历史表解释。'],
  },
  {
    capabilityId: 'finance.product-gross-profit.metric',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '商品毛利指标',
    description: '按商品订单明细和商品成本价统计商品销售收入、成本、毛利和毛利率。',
    domain: 'finance',
    businessObject: 'ProductGrossProfit',
    personaCodes: ['manager', 'finance'],
    actions: ['summary', 'analyze'],
    sourceModels: ['ProductOrder', 'OrderItem', 'Product', 'PaymentRecord', 'RefundRecord'],
    eventTypes: ['product_order', 'gross_profit'],
    outputKinds: ['kpi', 'table', 'evidence_panel'],
    executor: { type: 'business_metric_query', tool: 'business.metric.query', queryKey: 'finance.product-gross-profit.metric' },
    storeScope: 'required',
    permissionCodes: ['core:finance:view'],
    fieldPolicies: [
      allow('productName', '商品'),
      allow('sku', 'SKU'),
      allow('quantity', '销量'),
      allow('revenueText', '收入'),
      allow('costText', '成本'),
      allow('grossProfitText', '毛利'),
      allow('grossMarginText', '毛利率'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['哪些产品毛利率最高', '商品毛利情况', '本月商品毛利排行', '产品毛利率最高的是哪些'],
    negativeExamples: ['项目毛利情况', '员工提成', '日结报表'],
    triggerKeywords: ['商品毛利', '产品毛利', '商品毛利率', '产品毛利率', '毛利率最高'],
    boundaryNotes: ['商品毛利按 ProductOrder.orderItems 的商品明细计算，成本来自 Product.costPrice；缺成本时会在证据中提示。'],
  },
  {
    capabilityId: 'finance.project-gross-profit.metric',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '项目毛利指标',
    description: '按项目订单明细、项目 BOM 耗材成本和已生成提成统计项目服务次数、收入、成本、毛利和毛利率。',
    domain: 'finance',
    businessObject: 'ProjectGrossProfit',
    personaCodes: ['manager', 'finance'],
    actions: ['summary', 'analyze'],
    sourceModels: ['ProductOrder', 'OrderItem', 'Project', 'ProjectBomItem', 'Product', 'CommissionRecord'],
    eventTypes: ['project_order', 'gross_profit'],
    outputKinds: ['kpi', 'table', 'evidence_panel'],
    executor: { type: 'business_metric_query', tool: 'business.metric.query', queryKey: 'finance.project-gross-profit.metric' },
    storeScope: 'required',
    permissionCodes: ['core:finance:view'],
    fieldPolicies: [
      allow('projectName', '项目'),
      allow('serviceCount', '服务次数'),
      allow('revenueText', '收入'),
      allow('materialCostText', '耗材成本'),
      allow('commissionCostText', '提成成本'),
      allow('grossProfitText', '毛利'),
      allow('grossMarginText', '毛利率'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['帮我看一下各项目的毛利情况', '这个项目的实际毛利', '有没有项目毛利异常低', '有没有项目成本明显上涨影响毛利的'],
    negativeExamples: ['商品毛利率最高', '员工提成流水', '次卡销售金额'],
    triggerKeywords: ['项目毛利', '服务毛利', '项目成本', '实际毛利', '毛利异常低'],
    boundaryNotes: ['项目毛利优先使用订单明细收入、项目 BOM 标准耗材成本和已生成提成记录；缺少 BOM 或提成记录时会明确提示。'],
  },
  {
    capabilityId: 'finance.overall-gross-margin.metric',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '整体毛利率指标',
    description: '按财务日结汇总统计指定周期整体收入、耗材成本、提成成本、毛利和毛利率。',
    domain: 'finance',
    businessObject: 'GrossMargin',
    personaCodes: ['manager', 'finance'],
    actions: ['summary', 'analyze'],
    sourceModels: ['DailySettlement', 'ProductOrder', 'CommissionRecord', 'StockMovement'],
    eventTypes: ['gross_margin'],
    outputKinds: ['kpi', 'table', 'evidence_panel'],
    executor: { type: 'business_metric_query', tool: 'business.metric.query', queryKey: 'finance.overall-gross-margin.metric' },
    storeScope: 'required',
    permissionCodes: ['core:finance:view'],
    fieldPolicies: [
      allow('periodLabel', '周期'),
      allow('revenueText', '收入'),
      allow('materialCostText', '耗材成本'),
      allow('commissionCostText', '提成成本'),
      allow('grossProfitText', '毛利'),
      allow('grossMarginText', '毛利率'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['这个月的毛利率是多少', '本月毛利率是多少', '这个月毛利率为什么比上个月低', '本月整体毛利'],
    negativeExamples: ['哪些产品毛利率最高', '各项目毛利情况'],
    triggerKeywords: ['毛利率', '整体毛利', '本月毛利', '这个月毛利', '毛利为什么'],
    boundaryNotes: ['整体毛利率基于已生成 DailySettlement；如果日结缺失，需要先生成或修复日结链路。'],
  },
  {
    capabilityId: 'finance.card-package-sales.metric',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '次卡销售金额指标',
    description: '统计次卡开卡/套餐卡销售金额、开卡张数、赠送次数和平均成交价。',
    domain: 'finance',
    businessObject: 'CustomerCard',
    personaCodes: ['manager', 'finance'],
    actions: ['summary', 'analyze'],
    sourceModels: ['CustomerCard', 'Card', 'Customer', 'ProductOrder', 'OrderItem'],
    eventTypes: ['card_package_sale'],
    outputKinds: ['kpi', 'table', 'evidence_panel'],
    executor: { type: 'business_metric_query', tool: 'business.metric.query', queryKey: 'finance.card-package-sales.metric' },
    storeScope: 'required',
    permissionCodes: ['core:finance:view'],
    fieldPolicies: [
      allow('cardName', '次卡'),
      allow('customerName', '客户'),
      allow('paidAmountText', '实收金额'),
      allow('giftTimes', '赠送次数'),
      allow('totalTimes', '总次数'),
      allow('createdAt', '开卡时间'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['这个月次卡销售了多少金额', '本月次卡开卡金额', '次卡销售金额', '套餐卡本月卖了多少'],
    negativeExamples: ['次卡核销记录', '会员卡充值金额'],
    triggerKeywords: ['次卡销售', '次卡开卡金额', '套餐卡销售', '次卡卖了多少', '次卡销售金额'],
    boundaryNotes: ['次卡销售按 CustomerCard.sourceOrder/sourceOrderItem 和 paidAmount 统计；核销收入应走次卡核销能力。'],
  },
  {
    capabilityId: 'finance.payment-channel-fee.metric',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '支付渠道手续费预估',
    description: '按支付流水和渠道默认费率预估微信、支付宝、银行卡等支付手续费。',
    domain: 'finance',
    businessObject: 'PaymentFee',
    personaCodes: ['manager', 'finance'],
    actions: ['summary', 'analyze'],
    sourceModels: ['PaymentRecord', 'ProductOrder', 'Store'],
    eventTypes: ['payment_fee'],
    outputKinds: ['kpi', 'table', 'evidence_panel'],
    executor: { type: 'business_metric_query', tool: 'business.metric.query', queryKey: 'finance.payment-channel-fee.metric' },
    storeScope: 'required',
    permissionCodes: ['core:finance:view'],
    fieldPolicies: [
      allow('methodLabel', '支付渠道'),
      allow('amountText', '收款金额'),
      allow('feeRateText', '费率'),
      allow('estimatedFeeText', '预估手续费'),
      allow('paymentCount', '支付笔数'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['帮我看一下今天不同支付渠道的手续费', '本月微信支付宝手续费多少', '支付渠道手续费', '今天支付手续费'],
    negativeExamples: ['今天各支付方式收了多少', '退款手续费'],
    triggerKeywords: ['手续费', '支付渠道手续费', '微信手续费', '支付宝手续费', '银行卡手续费'],
    boundaryNotes: ['当前 PaymentRecord 未存实际手续费，先按默认费率预估；接入支付通道对账单后可切换为真实手续费。'],
  },
  {
    capabilityId: 'finance.staff-commission.records.list',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '员工提成流水查询',
    description: '查询员工提成明细，主体为 staffUserId，不再局限美容师。',
    domain: 'finance',
    businessObject: 'CommissionRecord',
    personaCodes: ['manager', 'finance'],
    actions: ['list', 'summary', 'analyze'],
    sourceModels: ['CommissionRecord', 'User', 'Beautician', 'CommissionRule', 'ProductOrder', 'OrderItem', 'CardUsageRecord'],
    eventTypes: ['commission'],
    outputKinds: ['table', 'evidence_panel'],
    executor: { type: 'business_record_query', tool: 'business.record.query', queryKey: 'finance.staff-commission.records' },
    storeScope: 'required',
    permissionCodes: ['core:finance:view'],
    fieldPolicies: [
      allow('staffName', '员工'),
      allow('sourceTypeLabel', '来源'),
      allow('orderNo', '订单编号'),
      allow('ruleName', '规则'),
      allow('sourceAmountText', '计提金额'),
      allow('amountText', '提成'),
      allow('statusLabel', '状态'),
      allow('createdAt', '生成时间'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['今天员工提成流水', '系统管理用户对应的提成明细', '提成记录缺失有哪些', '周宁本月提成'],
    negativeExamples: ['提成规则怎么配置', '项目管理提成配置'],
    triggerKeywords: ['提成流水', '提成明细', '员工提成', '人员提成', '佣金记录'],
    boundaryNotes: ['提成流水主体是系统用户 staffUserId；beauticianId 仅做历史兼容关联。'],
  },
  {
    capabilityId: 'customer.consumption.records.list',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '客户消费记录查询',
    description: '查询客户画像中的消费记录，并可定位订单、收银、次卡核销是否同步到客户消费流水。',
    domain: 'customer',
    businessObject: 'ConsumptionRecord',
    personaCodes: ['manager', 'reception', 'finance'],
    actions: ['list', 'summary', 'analyze'],
    sourceModels: ['ConsumptionRecord', 'Customer', 'ProductOrder', 'CardUsageRecord', 'CustomerCard'],
    eventTypes: ['customer_consumption'],
    outputKinds: ['table', 'evidence_panel'],
    executor: { type: 'business_record_query', tool: 'business.record.query', queryKey: 'customer.consumption.records' },
    storeScope: 'required',
    permissionCodes: ['core:customer:view'],
    fieldPolicies: [
      allow('customerName', '客户'),
      allow('consumeTypeLabel', '消费类型'),
      allow('consumeContentText', '消费内容'),
      allow('payMethodLabel', '支付方式'),
      allow('amountText', '消费金额'),
      allow('campaign', '关联活动'),
      allow('consumeTime', '消费时间'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['客户陈天佑的消费记录', '订单 PO1781893252477 为什么客户消费记录没有', '客户画像消费流水', '今天客户消费明细'],
    negativeExamples: ['客户画像分析', '小程序行为明细'],
    triggerKeywords: ['客户消费', '消费记录', '消费流水', '客户画像消费', '消费内容'],
    boundaryNotes: ['客户消费记录是客户视角流水；订单、收银、核销是来源系统，缺失时需要说明来源链路。'],
  },
  {
    capabilityId: 'marketing.coupon-redemption.metric',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '优惠券核销指标',
    description: '统计优惠券/权益的发放、核销、未核销和平均核销周期，不执行发券。',
    domain: 'marketing',
    businessObject: 'Promotion',
    personaCodes: ['manager', 'marketing', 'finance'],
    actions: ['summary', 'analyze'],
    sourceModels: ['Promotion', 'ProductOrder'],
    eventTypes: ['coupon_redemption'],
    outputKinds: ['kpi', 'table', 'evidence_panel'],
    executor: { type: 'business_metric_query', tool: 'business.metric.query', queryKey: 'marketing.coupon-redemption.metric' },
    storeScope: 'required',
    permissionCodes: ['core:marketing:view'],
    fieldPolicies: [
      allow('promotionName', '权益名称'),
      allow('issuedCount', '发放数'),
      allow('usedCount', '核销数'),
      allow('unusedCount', '未核销数'),
      allow('redemptionRateText', '核销率'),
      allow('averageCycleDaysText', '平均核销周期'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['这个月优惠券核销了多少', '我们的优惠券平均核销周期是多久', '优惠券核销率是多少'],
    negativeExamples: ['帮客户发优惠券', '直接给客户发券'],
    triggerKeywords: ['优惠券核销', '券核销', '优惠券平均核销周期', '核销率', '已核销优惠券'],
    boundaryNotes: ['只读统计 Promotion/ProductOrder 中的权益核销口径；发券、删除券、强制核销必须走审批或专门写入能力。'],
  },
  {
    capabilityId: 'customer.coupon.status.lookup',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '客户优惠券状态查询',
    description: '查询某位客户是否有可用、已使用或未核销的优惠券/权益，并说明数据缺口。',
    domain: 'customer',
    businessObject: 'CustomerCoupon',
    personaCodes: ['manager', 'marketing', 'reception'],
    actions: ['lookup', 'summary'],
    sourceModels: ['Customer', 'Promotion', 'ProductOrder'],
    eventTypes: ['customer_coupon'],
    outputKinds: ['table', 'evidence_panel', 'data_gap'],
    executor: { type: 'business_record_query', tool: 'business.record.query', queryKey: 'customer.coupon.status.lookup' },
    storeScope: 'required',
    permissionCodes: ['core:customer:view'],
    fieldPolicies: [
      allow('customerName', '客户'),
      allow('promotionName', '权益名称'),
      allow('statusLabel', '状态'),
      allow('usedOrderNo', '使用订单'),
      allow('usedAt', '使用时间'),
      allow('validUntil', '有效期'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['这位客人有没有未核销的优惠券', '这个客户还有可用优惠券吗', '客户未使用的券有哪些'],
    negativeExamples: ['这个月优惠券核销了多少', '帮客户发券'],
    triggerKeywords: ['未核销优惠券', '可用优惠券', '客户优惠券', '客人有没有券', '未使用的券'],
    boundaryNotes: ['如果问题没有提供客户名、手机号或客户 ID，返回需要补充客户条件，不猜测具体客户。'],
  },
  {
    capabilityId: 'card.package.status.lookup',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '客户次卡余量与有效期查询',
    description: '查询客户次卡剩余次数、总次数、到期时间和状态，不执行核销。',
    domain: 'order',
    businessObject: 'CustomerCard',
    personaCodes: ['manager', 'reception', 'beautician'],
    actions: ['lookup', 'summary'],
    sourceModels: ['CustomerCard', 'Card', 'Customer', 'CardUsageRecord'],
    eventTypes: ['card_package_status'],
    outputKinds: ['table', 'evidence_panel'],
    executor: { type: 'business_record_query', tool: 'business.record.query', queryKey: 'card.package.status.lookup' },
    storeScope: 'required',
    permissionCodes: ['core:order:view'],
    fieldPolicies: [
      allow('customerName', '客户'),
      allow('cardName', '次卡'),
      allow('remainingTimes', '剩余次数'),
      allow('totalTimes', '总次数'),
      allow('expiryDate', '有效期'),
      allow('statusLabel', '状态'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['客人说她的次卡还有余量，帮我确认一下', '这个客人的次卡有效期还有多久', '客户次卡剩余次数'],
    negativeExamples: ['帮我打开核销界面', '今天次卡核销记录', '次卡开卡订单'],
    triggerKeywords: ['次卡余量', '次卡剩余', '次卡有效期', '次卡还有', '次卡到期'],
    boundaryNotes: ['只查询 CustomerCard 当前状态；真正扣次必须走次卡核销能力。'],
  },
  {
    capabilityId: 'navigation.cashier.open',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '打开收银界面',
    description: '打开 Ami Aura Lite 收银入口，属于低风险导航，不创建订单、不执行收款。',
    domain: 'terminal',
    businessObject: 'Navigation',
    personaCodes: ['manager', 'reception'],
    actions: ['confirm_action'],
    sourceModels: ['AmiAuraLiteCommandRegistry'],
    sourceApis: ['operation.cashier'],
    eventTypes: ['navigation'],
    outputKinds: ['action_card', 'evidence_panel'],
    executor: { type: 'navigation', tool: 'navigation.open', queryKey: 'navigation.cashier.open' },
    storeScope: 'required',
    permissionCodes: ['core:order:view'],
    fieldPolicies: [allow('actionCommand', '终端动作'), allow('target', '目标入口')],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['帮我打开收银界面，客人要结账了', '打开收银', '进入结账界面'],
    negativeExamples: ['帮我收款', '直接创建订单', '给客人退款'],
    triggerKeywords: ['打开收银', '收银界面', '结账界面', '进入收银'],
    boundaryNotes: ['只返回导航动作，不执行收款、退款或创建订单。'],
  },
  {
    capabilityId: 'navigation.card-usage.open',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '打开次卡核销界面',
    description: '打开次卡核销入口，属于低风险导航，不扣减次数、不生成核销记录。',
    domain: 'terminal',
    businessObject: 'Navigation',
    personaCodes: ['manager', 'reception', 'beautician'],
    actions: ['confirm_action'],
    sourceModels: ['AmiAuraLiteCommandRegistry', 'AdminRoutes'],
    sourceApis: ['operation.verify', '/orders/card-usage'],
    eventTypes: ['navigation'],
    outputKinds: ['action_card', 'evidence_panel'],
    executor: { type: 'navigation', tool: 'navigation.open', queryKey: 'navigation.card-usage.open' },
    storeScope: 'required',
    permissionCodes: ['core:order:view'],
    fieldPolicies: [allow('terminalActionCommand', '终端动作'), allow('adminRoute', '管理端路由'), allow('target', '目标入口')],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['帮我打开核销界面，客人要用次卡', '打开次卡核销', '进入核销界面'],
    negativeExamples: ['帮我核销这张次卡', '今天次卡核销记录'],
    triggerKeywords: ['打开核销', '核销界面', '次卡核销入口', '进入核销'],
    boundaryNotes: ['只返回导航动作，不执行核销、扣次或库存消耗。'],
  },
  {
    capabilityId: 'finance.discount-permission-risk.metric',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '折扣越权风险查询',
    description: '检查订单中手工折扣、额外优惠和疑似超权限折扣风险。当前先基于订单折扣来源识别，后续可接审批日志。',
    domain: 'finance',
    businessObject: 'DiscountPermissionRisk',
    personaCodes: ['manager', 'finance'],
    actions: ['summary', 'analyze'],
    sourceModels: ['ProductOrder', 'OrderItem', 'User'],
    eventTypes: ['discount_permission_risk'],
    outputKinds: ['kpi', 'table', 'evidence_panel'],
    executor: { type: 'business_metric_query', tool: 'business.metric.query', queryKey: 'finance.discount-permission-risk.metric' },
    storeScope: 'required',
    permissionCodes: ['core:finance:view'],
    fieldPolicies: [
      allow('orderNo', '订单编号'),
      allow('customerName', '客户'),
      allow('discountAmountText', '折扣金额'),
      allow('discountSourceLabel', '折扣来源'),
      allow('riskLabel', '风险判断'),
      allow('createdAt', '下单时间'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['有没有员工超权限给了额外折扣', '本月额外折扣风险有哪些', '谁给了手工优惠'],
    negativeExamples: ['帮我给客户打折', '修改折扣规则'],
    triggerKeywords: ['超权限折扣', '额外折扣', '越权折扣', '手工优惠', '折扣风险'],
    boundaryNotes: ['当前不做权限写入，仅识别订单折扣风险；真实越权结论需结合审批/授权日志。'],
  },
  {
    capabilityId: 'card.package.inactive-customers.list',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '次卡沉睡客户名单',
    description: '找出已购买次卡但近期未核销/未到店使用的客户，用于门店跟进，不执行触达或核销。',
    domain: 'order',
    businessObject: 'CustomerCard',
    personaCodes: ['manager', 'reception', 'marketing'],
    actions: ['list', 'summary', 'analyze'],
    sourceModels: ['CustomerCard', 'CardUsageRecord', 'Customer', 'Card'],
    eventTypes: ['card_package_inactive_customer'],
    outputKinds: ['table', 'evidence_panel'],
    executor: { type: 'business_record_query', tool: 'business.record.query', queryKey: 'card.package.inactive-customers.list' },
    storeScope: 'required',
    permissionCodes: ['core:order:view'],
    fieldPolicies: [
      allow('customerName', '客户'),
      allow('customerPhone', '手机号'),
      allow('cardName', '次卡'),
      allow('remainingTimes', '剩余次数'),
      allow('lastUsedAt', '最近使用时间'),
      allow('inactiveDays', '未使用天数'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['哪些客户买了次卡但最近一直不来用', '买了次卡但很久没核销的客户有哪些', '次卡沉睡客户名单'],
    negativeExamples: ['帮我核销这张次卡', '打开核销界面'],
    triggerKeywords: ['买了次卡不来用', '次卡沉睡', '很久没核销', '次卡未使用'],
    boundaryNotes: ['只输出名单和证据，不自动下发跟进或扣次。'],
  },
  {
    capabilityId: 'card.package.free-vs-paid.behavior.metric',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '免费次卡与付费客户消费差异',
    description: '对比免费/赠送次卡客户与付费次卡客户的消费、核销和复购行为差异。',
    domain: 'finance',
    businessObject: 'CustomerCard',
    personaCodes: ['manager', 'finance', 'marketing'],
    actions: ['summary', 'analyze'],
    sourceModels: ['CustomerCard', 'CardUsageRecord', 'ProductOrder', 'Customer'],
    eventTypes: ['card_package_customer_behavior'],
    outputKinds: ['kpi', 'table', 'evidence_panel'],
    executor: { type: 'business_metric_query', tool: 'business.metric.query', queryKey: 'card.package.free-vs-paid.behavior.metric' },
    storeScope: 'required',
    permissionCodes: ['core:finance:view'],
    fieldPolicies: [
      allow('segmentLabel', '客户类型'),
      allow('customerCount', '客户数'),
      allow('usageCount', '核销次数'),
      allow('revenueText', '消费金额'),
      allow('avgRevenueText', '人均消费'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['免费次卡换来的客户和付费客户的消费行为有什么差异', '赠送次卡客户和付费次卡客户复购差异'],
    negativeExamples: ['给客户赠送次卡', '新增免费次卡订单'],
    triggerKeywords: ['免费次卡', '付费客户', '消费行为差异', '赠送次卡客户'],
    boundaryNotes: ['只做分群对比；不会自动创建赠送次卡或营销活动。'],
  },
  {
    capabilityId: 'finance.risk-diagnostics.metric',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '财务异常与经营压力诊断',
    description: '汇总退款、收银、订单、提成、报销/审批和日结数据，回答财务漏洞、异常、月报和经营压力问题。',
    domain: 'finance',
    businessObject: 'FinanceDiagnostics',
    personaCodes: ['manager', 'finance'],
    actions: ['summary', 'analyze', 'recommend'],
    sourceModels: ['DailySettlement', 'ProductOrder', 'PaymentRecord', 'RefundRecord', 'CommissionRecord', 'AgentApproval'],
    eventTypes: ['finance_risk_diagnostics'],
    outputKinds: ['kpi', 'table', 'evidence_panel'],
    executor: { type: 'business_metric_query', tool: 'business.metric.query', queryKey: 'finance.risk-diagnostics.metric' },
    storeScope: 'required',
    permissionCodes: ['core:finance:view'],
    fieldPolicies: [
      allow('riskType', '风险类型'),
      allow('riskLevel', '风险等级'),
      allow('evidenceText', '证据'),
      allow('suggestion', '建议'),
      allow('metricText', '指标'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['有没有哪里有财务漏洞需要注意', '帮我检查一下这个月的财务数据有没有异常', '员工报销和财务记录有没有不符的地方', '帮我生成一份月度财务简报', '下个月客流减少30%财务压力有多大'],
    negativeExamples: ['直接退款', '删除财务记录', '修改日结报表'],
    triggerKeywords: ['财务漏洞', '财务异常', '财务数据异常', '财务报告', '月度财务简报', '财务压力', '报销不符'],
    boundaryNotes: ['诊断和报告可以自动生成；退款、删除、写入和审批动作仍必须走人工确认或阻断。'],
  },
  {
    capabilityId: 'agent.multi-domain.summary',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '多域经营摘要',
    description: '对用户一次提出的多个经营问题拆分为多域只读摘要，覆盖营收、预约、库存、员工、客户和月报。',
    domain: 'business',
    businessObject: 'MultiDomainSummary',
    personaCodes: ['manager'],
    actions: ['summary', 'analyze'],
    sourceModels: ['ProductOrder', 'Appointment', 'StockBatch', 'CommissionRecord', 'Customer', 'DailySettlement'],
    eventTypes: ['multi_domain_summary'],
    outputKinds: ['kpi', 'table', 'evidence_panel'],
    executor: { type: 'business_metric_query', tool: 'business.metric.query', queryKey: 'agent.multi-domain.summary' },
    storeScope: 'required',
    permissionCodes: ['core:finance:view', 'core:inventory:view', 'core:customer:view', 'core:order:view', 'core:store:view'],
    fieldPolicies: [
      allow('section', '模块'),
      allow('metricText', '摘要'),
      allow('nextStep', '建议动作'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['帮我同时做六件事：查今日营收、看预约、检查库存、分析员工、找沉睡客户、生成月报'],
    negativeExamples: ['同时删除这些记录', '同时下发跟进并发券'],
    triggerKeywords: ['同时做', '六件事', '查今日营收', '看预约', '检查库存', '生成月报'],
    boundaryNotes: ['多域摘要只做规划和只读聚合；涉及写入、删除、发券或下发必须拆出审批动作。'],
  },
  {
    capabilityId: 'finance.commission-cost-optimization.advice',
    version: VERSION,
    status: 'enabled',
    source: 'manual_builtin',
    displayName: '提成成本优化建议',
    description: '结合提成流水和收入，给出提升员工积极性且控制提成成本的建议。',
    domain: 'finance',
    businessObject: 'CommissionOptimization',
    personaCodes: ['manager', 'finance'],
    actions: ['recommend', 'analyze'],
    sourceModels: ['CommissionRecord', 'ProductOrder', 'CommissionRule', 'User'],
    eventTypes: ['commission_optimization'],
    outputKinds: ['kpi', 'table', 'evidence_panel'],
    executor: { type: 'business_metric_query', tool: 'business.metric.query', queryKey: 'finance.commission-cost-optimization.advice' },
    storeScope: 'required',
    permissionCodes: ['core:finance:view'],
    fieldPolicies: [
      allow('totalCommissionText', '提成成本'),
      allow('totalRevenueText', '收入'),
      allow('commissionRateText', '提成占比'),
      allow('advice', '建议'),
    ],
    riskLevel: 'low',
    releaseStrategy: 'auto_publish',
    examples: ['我想提升员工积极性，同时控制提成成本，有什么建议', '提成成本怎么优化', '员工激励和提成成本怎么平衡'],
    negativeExamples: ['直接修改提成规则', '给员工发工资'],
    triggerKeywords: ['员工积极性', '提成成本', '控制提成', '员工激励', '提成优化'],
    boundaryNotes: ['只输出建议和证据，不自动修改提成规则。'],
  },
];

export function listAgentV2CapabilityManifests() {
  return AGENT_V2_CAPABILITY_MANIFESTS.filter((item) => item.status === 'enabled');
}
