import type {
  ApprovalScopes,
  DataScopes,
  FieldScopes,
  Permission,
  PermissionAssignment,
  PermissionPlatform,
  PlatformScopes,
  Role,
} from '@/types';

export const PLATFORMS: PermissionPlatform[] = ['core', 'assist', 'terminal'];

export const PERMISSION_CATALOG: Permission[] = [
  {
    code: 'core:dashboard:view',
    name: '查看工作台',
    type: 'menu',
    module: '工作台',
    platform: 'core',
    description: '查看工作台与首页待办',
    legacyCodes: ['dashboard:view'],
  },
  {
    code: 'core:agent:view',
    name: '访问 AI 智能体',
    type: 'menu',
    module: '工作台',
    platform: 'core',
    description: '访问洞悉美业·AI 智能体工作台',
    legacyCodes: [],
  },
  {
    code: 'core:customer:view',
    name: '查看客户',
    type: 'operation',
    module: '客户管理',
    platform: 'core',
    description: '查看客户列表与详情',
    legacyCodes: ['customer:view'],
  },
  {
    code: 'core:customer:create',
    name: '新增客户',
    type: 'operation',
    module: '客户管理',
    platform: 'core',
    description: '创建客户档案',
    legacyCodes: ['customer:create'],
  },
  {
    code: 'core:customer:update',
    name: '编辑客户',
    type: 'operation',
    module: '客户管理',
    platform: 'core',
    description: '修改客户基础信息',
    legacyCodes: ['customer:edit', 'customer:update'],
  },
  {
    code: 'core:customer:delete',
    name: '删除客户',
    type: 'operation',
    module: '客户管理',
    platform: 'core',
    description: '删除客户记录',
    legacyCodes: ['customer:delete'],
  },
  {
    code: 'core:customer:export',
    name: '导出客户',
    type: 'operation',
    module: '客户管理',
    platform: 'core',
    description: '导出客户数据',
    legacyCodes: ['customer:export'],
  },
  {
    code: 'core:customer:profile',
    name: '客户画像',
    type: 'menu',
    module: '客户管理',
    platform: 'core',
    description: '查看客户画像与护理信息',
    legacyCodes: ['customer:profile'],
  },
  {
    code: 'core:customer:script',
    name: '智能邀约',
    type: 'menu',
    module: '客户管理',
    platform: 'core',
    description: '生成邀约话术与跟进脚本',
    legacyCodes: ['customer:script'],
  },
  {
    code: 'core:marketing:view',
    name: '查看营销活动',
    type: 'menu',
    module: '智能营销',
    platform: 'core',
    description: '查看营销活动列表',
    legacyCodes: ['marketing:view'],
  },
  {
    code: 'core:marketing:create',
    name: '创建营销活动',
    type: 'operation',
    module: '智能营销',
    platform: 'core',
    description: '创建新的营销活动',
    legacyCodes: ['marketing:create'],
  },
  {
    code: 'core:marketing:update',
    name: '编辑营销活动',
    type: 'operation',
    module: '智能营销',
    platform: 'core',
    description: '修改营销活动',
    legacyCodes: ['marketing:edit'],
  },
  {
    code: 'core:marketing:delete',
    name: '删除营销活动',
    type: 'operation',
    module: '智能营销',
    platform: 'core',
    description: '删除营销活动',
    legacyCodes: ['marketing:delete'],
  },
  {
    code: 'core:marketing:recommend',
    name: '智能推荐',
    type: 'menu',
    module: '智能营销',
    platform: 'core',
    description: 'AI 推荐与客户洞察',
    legacyCodes: ['marketing:recommend'],
  },
  {
    code: 'core:marketing:template',
    name: '营销模板',
    type: 'menu',
    module: '智能营销',
    platform: 'core',
    description: '自动营销模板',
    legacyCodes: ['marketing:template'],
  },
  {
    code: 'core:marketing:analytics',
    name: '营销分析',
    type: 'menu',
    module: '智能营销',
    platform: 'core',
    description: '查看活动效果分析',
    legacyCodes: ['marketing:analytics'],
  },
  {
    code: 'core:store:view',
    name: '查看门店',
    type: 'operation',
    module: '门店管理',
    platform: 'core',
    description: '查看门店信息',
    legacyCodes: ['store:view'],
  },
  {
    code: 'core:store:projects',
    name: '项目管理',
    type: 'menu',
    module: '门店管理',
    platform: 'core',
    description: '管理服务项目',
    legacyCodes: ['store:projects', 'store:project:manage'],
  },
  {
    code: 'core:store:project-types',
    name: '项目类型管理',
    type: 'menu',
    module: '门店管理',
    platform: 'core',
    description: '管理项目类型',
    legacyCodes: ['store:project-types'],
  },
  {
    code: 'core:store:beauticians',
    name: '美容师管理',
    type: 'menu',
    module: '门店管理',
    platform: 'core',
    description: '管理美容师',
    legacyCodes: ['store:beauticians', 'store:beautician:manage'],
  },
  {
    code: 'core:store:beautician-levels',
    name: '美容师等级',
    type: 'menu',
    module: '门店管理',
    platform: 'core',
    description: '管理美容师等级',
    legacyCodes: ['store:beautician-levels'],
  },
  {
    code: 'core:store:scheduling',
    name: '排班管理',
    type: 'menu',
    module: '门店管理',
    platform: 'core',
    description: '管理排班与日程',
    legacyCodes: ['store:scheduling', 'scheduling:view', 'scheduling:edit', 'store:schedule:manage'],
  },
  {
    code: 'core:store:reservations',
    name: '项目预约',
    type: 'menu',
    module: '门店管理',
    platform: 'core',
    description: '管理预约与改派',
    legacyCodes: ['store:reservations', 'store:reservation:manage'],
  },
  {
    code: 'core:goods:types',
    name: '商品类型',
    type: 'menu',
    module: '商品管理',
    platform: 'core',
    description: '管理商品分类',
    legacyCodes: ['goods:types'],
  },
  {
    code: 'core:goods:products',
    name: '商品管理',
    type: 'menu',
    module: '商品管理',
    platform: 'core',
    description: '管理商品资料',
    legacyCodes: ['goods:products', 'product:view'],
  },
  {
    code: 'core:goods:cards',
    name: '次卡管理',
    type: 'menu',
    module: '商品管理',
    platform: 'core',
    description: '管理次卡与卡项',
    legacyCodes: ['goods:cards'],
  },
  {
    code: 'core:order:products',
    name: '商品订单',
    type: 'menu',
    module: '订单管理',
    platform: 'core',
    description: '商品订单管理',
    legacyCodes: ['order:products', 'order:view'],
  },
  {
    code: 'core:order:projects',
    name: '项目订单',
    type: 'menu',
    module: '订单管理',
    platform: 'core',
    description: '项目订单管理',
    legacyCodes: ['order:projects'],
  },
  {
    code: 'core:order:member-cards',
    name: '会员卡管理',
    type: 'menu',
    module: '订单管理',
    platform: 'core',
    description: '储值会员卡账户、开卡、充值、赠送与划扣管理',
    legacyCodes: ['order:member-cards', 'member-card:view'],
  },
  {
    code: 'core:order:card-orders',
    name: '次卡开卡',
    type: 'menu',
    module: '订单管理',
    platform: 'core',
    description: '次卡开卡管理',
    legacyCodes: ['order:card-orders'],
  },
  {
    code: 'core:order:card-usage',
    name: '次卡核销',
    type: 'menu',
    module: '订单管理',
    platform: 'core',
    description: '次卡核销管理',
    legacyCodes: ['order:card-usage', 'card:verify'],
  },
  {
    code: 'core:order:create',
    name: '创建订单',
    type: 'operation',
    module: '订单管理',
    platform: 'core',
    description: '创建订单',
    legacyCodes: ['order:create'],
  },
  {
    code: 'core:order:update',
    name: '编辑订单',
    type: 'operation',
    module: '订单管理',
    platform: 'core',
    description: '修改未完成订单',
    legacyCodes: ['order:edit'],
  },
  {
    code: 'core:order:refund',
    name: '订单退款',
    type: 'operation',
    module: '订单管理',
    platform: 'core',
    description: '处理订单退款',
    legacyCodes: ['order:refund'],
  },
  {
    code: 'core:project-order-profit:view',
    name: '查看项目订单利润',
    type: 'operation',
    module: '订单管理',
    platform: 'core',
    description: '查看单笔项目订单收入、BOM 耗材、提成和毛利明细',
  },
  {
    code: 'core:product-order-profit:view',
    name: '查看商品订单利润',
    type: 'operation',
    module: '订单管理',
    platform: 'core',
    description: '查看单笔商品订单收入、商品成本、提成和毛利明细',
  },
  {
    code: 'core:card-order-profit:view',
    name: '查看次卡订单利润',
    type: 'operation',
    module: '订单管理',
    platform: 'core',
    description: '查看单笔次卡订单开卡收入、履约负债、提成和毛利明细',
  },
  {
    code: 'core:inventory:products',
    name: '产品管理',
    type: 'menu',
    module: '库存管理',
    platform: 'core',
    description: '管理库存商品',
    legacyCodes: ['inventory:products', 'inventory:view'],
  },
  {
    code: 'core:inventory:stock',
    name: '库存管理',
    type: 'menu',
    module: '库存管理',
    platform: 'core',
    description: '查看库存与批次',
    legacyCodes: ['inventory:stock'],
  },
  {
    code: 'core:inventory:purchase',
    name: '采购管理',
    type: 'menu',
    module: '库存管理',
    platform: 'core',
    description: '采购与入库管理',
    legacyCodes: ['inventory:purchase'],
  },
  {
    code: 'core:inventory:expiry',
    name: '过期管理',
    type: 'menu',
    module: '库存管理',
    platform: 'core',
    description: '过期与临期管理',
    legacyCodes: ['inventory:expiry'],
  },
  {
    code: 'core:inventory:transfer',
    name: '门店库存调拨',
    type: 'menu',
    module: '库存管理',
    platform: 'core',
    description: '门店间库存调拨',
    legacyCodes: ['inventory:transfer'],
  },
  {
    code: 'core:inventory:consumption',
    name: '服务消耗',
    type: 'menu',
    module: '库存管理',
    platform: 'core',
    description: 'BOM 和服务消耗管理',
    legacyCodes: ['inventory:consumption'],
  },
  {
    code: 'core:finance:view',
    name: '查看财务数据',
    type: 'menu',
    module: '财务管理',
    platform: 'core',
    description: '查看提成明细、月度结算与财务报表',
    legacyCodes: ['finance:view'],
  },
  {
    code: 'core:finance:manage',
    name: '管理财务规则',
    type: 'operation',
    module: '财务管理',
    platform: 'core',
    description: '管理提成规则、确认提成与结算单',
    legacyCodes: ['finance:manage', 'commission:manage'],
  },
  {
    code: 'core:finance:export',
    name: '导出财务报表',
    type: 'operation',
    module: '财务管理',
    platform: 'core',
    description: '导出提成明细、结算工资表与财务报表',
    legacyCodes: ['finance:export'],
  },
  {
    code: 'core:operation-profit:view',
    name: '查看经营利润',
    type: 'menu',
    module: '经营利润',
    platform: 'core',
    description: '查看经营利润看板、收入成本结构与经营异常',
  },
  {
    code: 'core:operation-profit:export',
    name: '导出经营利润',
    type: 'operation',
    module: '经营利润',
    platform: 'core',
    description: '导出经营利润报表',
  },
  {
    code: 'core:operation-cost:view',
    name: '查看经营成本',
    type: 'menu',
    module: '经营利润',
    platform: 'core',
    description: '查看月度经营成本配置',
  },
  {
    code: 'core:operation-cost:manage',
    name: '管理经营成本',
    type: 'operation',
    module: '经营利润',
    platform: 'core',
    description: '新增、编辑、删除和复制月度经营成本',
  },
  {
    code: 'core:product-margin:view',
    name: '查看商品毛利',
    type: 'menu',
    module: '经营利润',
    platform: 'core',
    description: '查看商品销售收入、商品成本、提成和毛利率',
  },
  {
    code: 'core:project-margin:view',
    name: '查看项目毛利',
    type: 'menu',
    module: '经营利润',
    platform: 'core',
    description: '查看项目收入、耗材、提成和贡献毛利',
  },
  {
    code: 'core:prepaid-liability:view',
    name: '查看会员卡履约',
    type: 'menu',
    module: '经营利润',
    platform: 'core',
    description: '查看会员卡剩余权益、临期和沉睡风险',
  },
  {
    code: 'core:beautician-performance:view',
    name: '查看员工人效',
    type: 'menu',
    module: '经营利润',
    platform: 'core',
    description: '查看美容师服务收入、服务次数、客户数和贡献毛利',
  },
  {
    code: 'core:supply:view',
    name: '查看供应链',
    type: 'menu',
    module: '供应链',
    platform: 'core',
    description: '查看供应商、采购订单与供应链结算数据',
    legacyCodes: ['supply:view'],
  },
  {
    code: 'core:supply:manage',
    name: '管理供应链',
    type: 'operation',
    module: '供应链',
    platform: 'core',
    description: '管理供应商、采购订单与供应链结算',
    legacyCodes: ['supply:manage', 'supplier:manage'],
  },
  {
    code: 'core:supply:supplier',
    name: '供应商自助',
    type: 'operation',
    module: '供应链',
    platform: 'core',
    description: '供应商自助维护商品、报价、订单发货与对账',
    legacyCodes: ['supply:supplier'],
  },
  {
    code: 'core:industry:view',
    name: '查看行业数据平台',
    type: 'menu',
    module: '行业数据平台',
    platform: 'core',
    description: '查看行业模板、参考价格、BOM、薪酬与知识库',
    legacyCodes: ['industry:view'],
  },
  {
    code: 'core:industry:manage',
    name: '管理行业数据平台',
    type: 'operation',
    module: '行业数据平台',
    platform: 'core',
    description: '管理行业模板、数据源、审核发布与采用记录',
    legacyCodes: ['industry:manage'],
  },
  {
    code: 'core:industry:data-source',
    name: '数据源管理',
    type: 'menu',
    module: '行业数据平台',
    platform: 'core',
    description: '维护公开来源、采集批次与可信度评级',
    legacyCodes: ['industry:data-source'],
  },
  {
    code: 'core:industry:service-template',
    name: '服务项目模板',
    type: 'menu',
    module: '行业数据平台',
    platform: 'core',
    description: '维护成熟服务项目模板、参考售价、时长与服务标准',
    legacyCodes: ['industry:service-template'],
  },
  {
    code: 'core:industry:bom-template',
    name: '项目 BOM 模板',
    type: 'menu',
    module: '行业数据平台',
    platform: 'core',
    description: '维护项目对应耗品、用量、单位成本与供应链映射预留字段',
    legacyCodes: ['industry:bom-template'],
  },
  {
    code: 'core:industry:product-template',
    name: '标准商品/耗品',
    type: 'menu',
    module: '行业数据平台',
    platform: 'core',
    description: '维护商品、耗品、规格、参考成本与参考零售价',
    legacyCodes: ['industry:product-template'],
  },
  {
    code: 'core:industry:salary',
    name: '岗位薪酬模板',
    type: 'menu',
    module: '行业数据平台',
    platform: 'core',
    description: '维护岗位薪酬、提成口径与区域参考范围',
    legacyCodes: ['industry:salary'],
  },
  {
    code: 'core:industry:knowledge',
    name: '服务知识库',
    type: 'menu',
    module: '行业数据平台',
    platform: 'core',
    description: '维护 SOP、卫生安全、禁忌提醒、销售话术与培训知识',
    legacyCodes: ['industry:knowledge'],
  },
  {
    code: 'core:industry:adoption',
    name: '采用记录',
    type: 'menu',
    module: '行业数据平台',
    platform: 'core',
    description: '查看行业模板被门店项目、商品、薪酬和知识配置采用的记录',
    legacyCodes: ['industry:adoption'],
  },
  {
    code: 'core:industry:supply-mapping',
    name: '供应链预留映射',
    type: 'menu',
    module: '行业数据平台',
    platform: 'core',
    description: '查看行业耗品与未来供应链商品库的映射占位状态',
    legacyCodes: ['industry:supply-mapping'],
  },
  {
    code: 'core:system:users',
    name: '用户管理',
    type: 'menu',
    module: '系统设置',
    platform: 'core',
    description: '管理系统用户',
    legacyCodes: ['system:users', 'system:user:manage'],
  },
  {
    code: 'core:system:roles',
    name: '角色管理',
    type: 'menu',
    module: '系统设置',
    platform: 'core',
    description: '管理角色与权限',
    legacyCodes: ['system:roles', 'system:role:manage'],
  },
  {
    code: 'core:system:permissions',
    name: '权限管理',
    type: 'menu',
    module: '系统设置',
    platform: 'core',
    description: '查看权限目录',
    legacyCodes: ['system:permissions'],
  },
  {
    code: 'core:system:stores',
    name: '门店管理',
    type: 'menu',
    module: '系统设置',
    platform: 'core',
    description: '管理门店信息',
    legacyCodes: ['system:stores', 'system:store:manage'],
  },
  {
    code: 'core:system:logs',
    name: '操作日志',
    type: 'menu',
    module: '系统设置',
    platform: 'core',
    description: '查看系统操作日志',
    legacyCodes: ['system:log:view'],
  },
  {
    code: 'assist:chat:view',
    name: '查看会话',
    type: 'menu',
    module: '咨询协同',
    platform: 'assist',
    description: '查看客户会话',
  },
  {
    code: 'assist:chat:reply',
    name: '回复会话',
    type: 'operation',
    module: '咨询协同',
    platform: 'assist',
    description: '回复客户咨询',
  },
  {
    code: 'assist:booking:create',
    name: '创建预约',
    type: 'operation',
    module: '咨询协同',
    platform: 'assist',
    description: '创建客户预约',
  },
  {
    code: 'assist:followup:create',
    name: '新增跟进',
    type: 'operation',
    module: '咨询协同',
    platform: 'assist',
    description: '新增客户跟进记录',
  },
  {
    code: 'terminal:device:login',
    name: '终端登录',
    type: 'operation',
    module: '智能终端',
    platform: 'terminal',
    description: '允许设备登录',
  },
  {
    code: 'terminal:service:view',
    name: '查看服务任务',
    type: 'menu',
    module: '智能终端',
    platform: 'terminal',
    description: '查看当前服务任务',
  },
  {
    code: 'terminal:service:start',
    name: '开始服务',
    type: 'operation',
    module: '智能终端',
    platform: 'terminal',
    description: '开始当前服务',
  },
  {
    code: 'terminal:service:complete',
    name: '完成服务',
    type: 'operation',
    module: '智能终端',
    platform: 'terminal',
    description: '提交服务完成',
  },
  {
    code: 'terminal:skin:record',
    name: '皮肤检测',
    type: 'operation',
    module: '智能终端',
    platform: 'terminal',
    description: '记录皮肤检测结果',
  },
  {
    code: 'aura:manager:view',
    name: 'Aura 店长视图',
    type: 'menu',
    module: 'Ami Aura Lite',
    platform: 'terminal',
    description: '店长经营驾驶舱与管理视图',
  },
  {
    code: 'aura:reception:view',
    name: 'Aura 前台视图',
    type: 'menu',
    module: 'Ami Aura Lite',
    platform: 'terminal',
    description: '前台接待与交易视图',
  },
  {
    code: 'aura:beautician:view',
    name: 'Aura 美容师视图',
    type: 'menu',
    module: 'Ami Aura Lite',
    platform: 'terminal',
    description: '美容师服务视图',
  },
  {
    code: 'aura:customer:read',
    name: 'Aura 查看客户',
    type: 'operation',
    module: 'Ami Aura Lite',
    platform: 'terminal',
    description: '读取客户档案与服务相关信息',
  },
  {
    code: 'aura:appointment:read',
    name: 'Aura 查看预约',
    type: 'operation',
    module: 'Ami Aura Lite',
    platform: 'terminal',
    description: '读取预约与排班信息',
  },
  {
    code: 'aura:appointment:write',
    name: 'Aura 维护预约',
    type: 'operation',
    module: 'Ami Aura Lite',
    platform: 'terminal',
    description: '创建与调整预约',
  },
  {
    code: 'aura:card:consume',
    name: 'Aura 次卡核销',
    type: 'operation',
    module: 'Ami Aura Lite',
    platform: 'terminal',
    description: '核销次卡与疗程卡',
  },
  {
    code: 'aura:cashier:create',
    name: 'Aura 收银开单',
    type: 'operation',
    module: 'Ami Aura Lite',
    platform: 'terminal',
    description: '创建收银单据',
  },
  {
    code: 'aura:card-order:create',
    name: 'Aura 办卡',
    type: 'operation',
    module: 'Ami Aura Lite',
    platform: 'terminal',
    description: '创建办卡订单',
  },
  {
    code: 'aura:recharge:create',
    name: 'Aura 充值',
    type: 'operation',
    module: 'Ami Aura Lite',
    platform: 'terminal',
    description: '创建充值订单',
  },
  {
    code: 'aura:service-record:create',
    name: 'Aura 服务记录',
    type: 'operation',
    module: 'Ami Aura Lite',
    platform: 'terminal',
    description: '记录服务结果与护理建议',
  },
  {
    code: 'aura:inventory:read',
    name: 'Aura 查看库存',
    type: 'operation',
    module: 'Ami Aura Lite',
    platform: 'terminal',
    description: '读取库存预警与补货建议',
  },
  {
    code: 'aura:staff:read',
    name: 'Aura 查看员工',
    type: 'operation',
    module: 'Ami Aura Lite',
    platform: 'terminal',
    description: '读取员工排班与绩效信息',
  },
];

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  super_admin: ['*'],
  store_manager: [
    'core:dashboard:view',
    'core:agent:view',
    'core:customer:view',
    'core:customer:create',
    'core:customer:update',
    'core:customer:delete',
    'core:customer:export',
    'core:customer:profile',
    'core:customer:script',
    'core:marketing:view',
    'core:marketing:create',
    'core:marketing:update',
    'core:marketing:delete',
    'core:marketing:recommend',
    'core:marketing:template',
    'core:marketing:analytics',
    'core:store:view',
    'core:store:project-types',
    'core:store:projects',
    'core:store:beauticians',
    'core:store:beautician-levels',
    'core:store:scheduling',
    'core:store:reservations',
    'core:goods:types',
    'core:goods:products',
    'core:goods:cards',
    'core:order:products',
    'core:order:projects',
    'core:order:member-cards',
    'core:order:card-orders',
    'core:order:card-usage',
    'core:order:create',
    'core:order:update',
    'core:order:refund',
    'core:project-order-profit:view',
    'core:product-order-profit:view',
    'core:card-order-profit:view',
    'core:inventory:products',
    'core:inventory:stock',
    'core:inventory:purchase',
    'core:inventory:expiry',
    'core:inventory:transfer',
    'core:inventory:consumption',
    'core:finance:view',
    'core:finance:manage',
    'core:finance:export',
    'core:operation-profit:view',
    'core:operation-cost:view',
    'core:product-margin:view',
    'core:project-margin:view',
    'core:prepaid-liability:view',
    'core:beautician-performance:view',
    'core:supply:view',
    'core:supply:manage',
    'core:system:users',
    'core:system:roles',
    'core:system:permissions',
    'core:system:stores',
    'core:system:logs',
    'aura:manager:view',
    'aura:reception:view',
    'aura:beautician:view',
    'aura:customer:read',
    'aura:appointment:read',
    'aura:appointment:write',
    'aura:card:consume',
    'aura:cashier:create',
    'aura:card-order:create',
    'aura:recharge:create',
    'aura:service-record:create',
    'aura:inventory:read',
    'aura:staff:read',
  ],
  beautician: [
    'core:dashboard:view',
    'core:customer:profile',
    'core:customer:script',
    'core:order:card-usage',
    'core:store:scheduling',
    'core:store:reservations',
    'terminal:service:view',
    'terminal:service:start',
    'terminal:service:complete',
    'terminal:skin:record',
    'aura:beautician:view',
    'aura:customer:read',
    'aura:appointment:read',
    'aura:service-record:create',
  ],
  cashier: [
    'core:dashboard:view',
    'core:customer:view',
    'core:customer:create',
    'core:customer:update',
    'core:store:reservations',
    'core:order:products',
    'core:order:projects',
    'core:order:member-cards',
    'core:order:card-orders',
    'core:order:card-usage',
    'core:order:create',
    'core:order:update',
    'core:order:refund',
    'aura:reception:view',
    'aura:customer:read',
    'aura:appointment:read',
    'aura:appointment:write',
    'aura:card:consume',
    'aura:cashier:create',
    'aura:card-order:create',
    'aura:recharge:create',
  ],
  inventory_manager: [
    'core:dashboard:view',
    'core:inventory:products',
    'core:inventory:stock',
    'core:inventory:purchase',
    'core:inventory:expiry',
    'core:inventory:transfer',
    'core:inventory:consumption',
    'core:project-margin:view',
  ],
  supplier_admin: ['core:supply:view', 'core:supply:supplier'],
};

export const DEFAULT_PLATFORM_SCOPES: Record<string, PlatformScopes> = {
  super_admin: { core: true, assist: true, terminal: true },
  store_manager: { core: true, assist: true, terminal: true },
  beautician: { core: true, assist: true, terminal: true },
  cashier: { core: true, assist: true, terminal: true },
  inventory_manager: { core: true, assist: false, terminal: false },
  supplier_admin: { core: true, assist: false, terminal: false },
};

export const DEFAULT_DATA_SCOPES: Record<string, DataScopes> = {
  super_admin: {
    store: 'all',
    customer: 'all',
    order: 'all',
    booking: 'all',
    inventory: 'all',
    report: 'all',
    device: 'all',
  },
  store_manager: {
    store: 'own_store',
    customer: 'own_store',
    order: 'own_store',
    booking: 'own_store',
    inventory: 'own_store',
    report: 'own_store',
    device: 'own_store',
  },
  beautician: {
    store: 'own_store',
    customer: 'served_customers',
    order: 'served_customers',
    booking: 'self',
    inventory: 'none',
    report: 'self',
    device: 'current_device',
  },
  cashier: {
    store: 'own_store',
    customer: 'own_store',
    order: 'own_store',
    booking: 'own_store',
    inventory: 'none',
    report: 'own_store',
    device: 'none',
  },
  inventory_manager: {
    store: 'own_store',
    customer: 'none',
    order: 'none',
    booking: 'none',
    inventory: 'own_store',
    report: 'own_store',
    device: 'none',
  },
  supplier_admin: {
    store: 'none',
    customer: 'none',
    order: 'none',
    booking: 'none',
    inventory: 'none',
    report: 'none',
    device: 'none',
  },
};

export const DEFAULT_FIELD_SCOPES: Record<string, FieldScopes> = {
  super_admin: {
    customerPhone: 'visible',
    customerWechat: 'visible',
    customerBalance: 'visible',
    customerCost: 'visible',
    customerProfit: 'visible',
    customerPrivateNote: 'visible',
    customerRemark: 'visible',
    staffCommission: 'visible',
  },
  store_manager: {
    customerPhone: 'visible',
    customerWechat: 'visible',
    customerBalance: 'visible',
    customerCost: 'visible',
    customerProfit: 'visible',
    customerPrivateNote: 'visible',
    customerRemark: 'visible',
    staffCommission: 'visible',
  },
  beautician: {
    customerPhone: 'masked',
    customerWechat: 'masked',
    customerBalance: 'hidden',
    customerCost: 'hidden',
    customerProfit: 'hidden',
    customerPrivateNote: 'hidden',
    customerRemark: 'visible',
    staffCommission: 'hidden',
  },
  cashier: {
    customerPhone: 'masked',
    customerWechat: 'masked',
    customerBalance: 'visible',
    customerCost: 'hidden',
    customerProfit: 'hidden',
    customerPrivateNote: 'hidden',
    customerRemark: 'visible',
    staffCommission: 'hidden',
  },
  inventory_manager: {
    customerPhone: 'hidden',
    customerWechat: 'hidden',
    customerBalance: 'hidden',
    customerCost: 'visible',
    customerProfit: 'hidden',
    customerPrivateNote: 'hidden',
    customerRemark: 'hidden',
    staffCommission: 'hidden',
  },
  supplier_admin: {
    customerPhone: 'hidden',
    customerWechat: 'hidden',
    customerBalance: 'hidden',
    customerCost: 'hidden',
    customerProfit: 'hidden',
    customerPrivateNote: 'hidden',
    customerRemark: 'hidden',
    staffCommission: 'hidden',
  },
};

export const DEFAULT_APPROVAL_SCOPES: Record<string, ApprovalScopes> = {
  super_admin: {
    refund: 'approve',
    discount: 'approve',
    priceChange: 'approve',
    deleteCustomer: 'approve',
    exportCustomer: 'approve',
    inventoryAdjustment: 'approve',
    deviceUnbind: 'approve',
  },
  store_manager: {
    refund: 'approve_limited',
    discount: 'approve_limited',
    priceChange: 'approve_limited',
    deleteCustomer: 'request',
    exportCustomer: 'request',
    inventoryAdjustment: 'approve_limited',
    deviceUnbind: 'request',
  },
  beautician: {
    refund: 'none',
    discount: 'none',
    priceChange: 'none',
    deleteCustomer: 'none',
    exportCustomer: 'none',
    inventoryAdjustment: 'request',
    deviceUnbind: 'none',
  },
  cashier: {
    refund: 'request',
    discount: 'request',
    priceChange: 'none',
    deleteCustomer: 'none',
    exportCustomer: 'none',
    inventoryAdjustment: 'none',
    deviceUnbind: 'none',
  },
  inventory_manager: {
    refund: 'none',
    discount: 'none',
    priceChange: 'none',
    deleteCustomer: 'none',
    exportCustomer: 'none',
    inventoryAdjustment: 'request',
    deviceUnbind: 'none',
  },
  supplier_admin: {
    refund: 'none',
    discount: 'none',
    priceChange: 'none',
    deleteCustomer: 'none',
    exportCustomer: 'none',
    inventoryAdjustment: 'none',
    deviceUnbind: 'none',
  },
};

export const LEGACY_PERMISSION_MAP: Record<string, string> = PERMISSION_CATALOG.reduce<Record<string, string>>((acc, permission) => {
  acc[permission.code] = permission.code;
  for (const legacyCode of permission.legacyCodes ?? []) {
    acc[legacyCode] = permission.code;
  }
  return acc;
}, {});

export function normalizePermissionCode(code: string): string {
  if (code === '*') {
    return code;
  }
  return LEGACY_PERMISSION_MAP[code] ?? code;
}

export function normalizePermissions(permissions: string[] = []): string[] {
  if (permissions.includes('*')) {
    return ['*'];
  }
  return Array.from(new Set(permissions.map(normalizePermissionCode)));
}

export function hasPermission(permissions: string[] = [], permissionCode: string): boolean {
  if (permissions.includes('*')) {
    return true;
  }
  const normalized = new Set(normalizePermissions(permissions));
  return normalized.has(normalizePermissionCode(permissionCode));
}

export function getPermissionsByPlatform(platform: PermissionPlatform): Permission[] {
  return PERMISSION_CATALOG.filter((permission) => permission.platform === platform);
}

export function getRoleDefaults(roleCode: string): PermissionAssignment & {
  platformScopes: PlatformScopes;
  dataScopes: DataScopes;
  fieldScopes: FieldScopes;
  approvalScopes: ApprovalScopes;
} {
  return {
    permissions: normalizePermissions(ROLE_PERMISSIONS[roleCode] ?? []),
    platformScopes: DEFAULT_PLATFORM_SCOPES[roleCode] ?? { core: false, assist: false, terminal: false },
    dataScopes: DEFAULT_DATA_SCOPES[roleCode] ?? {
      store: 'none',
      customer: 'none',
      order: 'none',
      booking: 'none',
      inventory: 'none',
      report: 'none',
      device: 'none',
    },
    fieldScopes: DEFAULT_FIELD_SCOPES[roleCode] ?? {
      customerPhone: 'hidden',
      customerWechat: 'hidden',
      customerBalance: 'hidden',
      customerCost: 'hidden',
      customerProfit: 'hidden',
      customerPrivateNote: 'hidden',
      customerRemark: 'hidden',
      staffCommission: 'hidden',
    },
    approvalScopes: DEFAULT_APPROVAL_SCOPES[roleCode] ?? {
      refund: 'none',
      discount: 'none',
      priceChange: 'none',
      deleteCustomer: 'none',
      exportCustomer: 'none',
      inventoryAdjustment: 'none',
      deviceUnbind: 'none',
    },
  };
}

export function createDefaultRole(roleCode: string, name: string, description: string, isSystem = true, userCount = 0): Role {
  const defaults = getRoleDefaults(roleCode);
  return {
    id: 0,
    name,
    code: roleCode,
    description,
    isSystem,
    userCount,
    permissions: defaults.permissions,
    platformScopes: defaults.platformScopes,
    dataScopes: defaults.dataScopes,
    fieldScopes: defaults.fieldScopes,
    approvalScopes: defaults.approvalScopes,
  };
}
