import type { BusinessQueryCapability } from './business-query.types.js';

export const BUSINESS_QUERY_CAPABILITIES: BusinessQueryCapability[] = [
  {
    id: 'business_overview',
    domain: 'business',
    name: '经营概览',
    description: '查询门店收入、订单、预约、库存和客户机会摘要',
    allowedRoles: ['manager'],
    defaultParams: { dateRange: 'today', limit: 10 },
    resultLimit: 10,
    riskLevel: 'medium',
    cardType: 'businessOverview',
    implemented: true,
  },
  {
    id: 'product_sales_trend',
    domain: 'product',
    name: '商品销量趋势',
    description: '查询商品销量、销售额、订单数、客户数及环比增长',
    allowedRoles: ['manager', 'reception'],
    defaultParams: { dateRange: 'last_30_days', compareWith: 'previous_30_days', metric: 'quantity', limit: 10 },
    resultLimit: 10,
    riskLevel: 'low',
    cardType: 'productSalesTrend',
    implemented: true,
  },
  {
    id: 'product_customer_distribution',
    domain: 'product',
    name: '商品购买客户分布',
    description: '基于上一轮商品结果查询购买客户、订单数和购买数量',
    allowedRoles: ['manager', 'reception'],
    defaultParams: { dateRange: 'last_30_days', limit: 20 },
    resultLimit: 20,
    riskLevel: 'medium',
    cardType: 'productCustomerDistribution',
    implemented: true,
  },
  {
    id: 'product_replenishment_opportunity',
    domain: 'inventory',
    name: '商品补货机会',
    description: '结合低库存、安全库存和近期销量给出补货优先级',
    allowedRoles: ['manager', 'reception'],
    defaultParams: { dateRange: 'last_30_days', limit: 10 },
    resultLimit: 10,
    riskLevel: 'medium',
    cardType: 'productReplenishmentOpportunity',
    implemented: true,
  },
  {
    id: 'customer_profile_lookup',
    domain: 'customer',
    name: '客户档案查询',
    description: '根据客户实体查询基础资料、会员等级、消费和最近到店摘要',
    allowedRoles: ['manager', 'reception', 'beautician'],
    defaultParams: { limit: 1 },
    resultLimit: 1,
    riskLevel: 'low',
    cardType: 'customerProfileLookup',
    implemented: true,
  },
  {
    id: 'customer_reservation_today',
    domain: 'reservation',
    name: '客户今日预约',
    description: '根据客户实体查询今日预约、项目、美容师和预约状态',
    allowedRoles: ['manager', 'reception', 'beautician'],
    defaultParams: { dateRange: 'today', limit: 20 },
    resultLimit: 20,
    riskLevel: 'low',
    cardType: 'customerReservationToday',
    implemented: true,
  },
  {
    id: 'customer_card_benefit_summary',
    domain: 'card',
    name: '客户卡项权益摘要',
    description: '根据客户实体查询持有卡项、剩余次数、到期和可核销权益',
    allowedRoles: ['manager', 'reception'],
    defaultParams: { limit: 20 },
    resultLimit: 20,
    riskLevel: 'low',
    cardType: 'customerCardBenefitSummary',
    implemented: true,
  },
  {
    id: 'customer_churn_risk',
    domain: 'customer',
    name: '客户流失风险',
    description: '查询久未到店、高消费或无未来预约的客户风险',
    allowedRoles: ['manager', 'reception', 'beautician'],
    defaultParams: { limit: 10 },
    resultLimit: 10,
    riskLevel: 'low',
    cardType: 'customerChurnRisk',
    implemented: true,
  },
  {
    id: 'customer_growth_opportunity',
    domain: 'customer',
    name: '客户增长机会',
    description: '查询高价值客户、复购机会和跟进建议',
    allowedRoles: ['manager', 'reception', 'beautician'],
    defaultParams: { limit: 10 },
    resultLimit: 10,
    riskLevel: 'low',
    cardType: 'customerGrowthOpportunity',
    implemented: true,
  },
  {
    id: 'inventory_alert',
    domain: 'inventory',
    name: '库存预警',
    description: '查询低库存、临期和补货建议',
    allowedRoles: ['manager', 'reception'],
    defaultParams: { limit: 10 },
    resultLimit: 10,
    riskLevel: 'low',
    cardType: 'inventoryAlert',
    implemented: true,
  },
  {
    id: 'reservation_today',
    domain: 'reservation',
    name: '今日预约',
    description: '查询今日预约、未到店、已到店和空位',
    allowedRoles: ['manager', 'reception', 'beautician'],
    defaultParams: { dateRange: 'today', limit: 20 },
    resultLimit: 20,
    riskLevel: 'low',
    cardType: 'reservationToday',
    implemented: true,
  },
  {
    id: 'finance_order_lookup',
    domain: 'order',
    name: '订单流水查询',
    description: '根据订单号或收银组号查询订单、支付、退款和明细',
    allowedRoles: ['manager', 'reception'],
    defaultParams: { limit: 1 },
    resultLimit: 1,
    riskLevel: 'low',
    cardType: 'financeOrderLookup',
    implemented: true,
  },
  {
    id: 'finance_today_transaction_list',
    domain: 'finance',
    name: '今日交易订单清单',
    description: '查询今日收银、核销、办卡、充值、退款等交易订单列表，并支持打印预览',
    allowedRoles: ['manager', 'reception'],
    defaultParams: { dateRange: 'today', limit: 50 },
    resultLimit: 50,
    riskLevel: 'medium',
    cardType: 'financeTodayTransactionList',
    implemented: true,
  },
  {
    id: 'order_revenue_analysis',
    domain: 'order',
    name: '订单收入分析',
    description: '查询收入、订单数、客单价和支付方式分布',
    allowedRoles: ['manager', 'reception'],
    defaultParams: { dateRange: 'today', limit: 10 },
    resultLimit: 10,
    riskLevel: 'low',
    cardType: 'orderRevenueAnalysis',
    implemented: true,
  },
  {
    id: 'order_customer_consumption_list',
    domain: 'order',
    name: '消费客户清单',
    description: '查询指定时间范围内发生有效消费/成交/流水的客户清单、消费金额、订单数和最近消费时间',
    allowedRoles: ['manager', 'reception'],
    defaultParams: { dateRange: 'yesterday', limit: 20 },
    resultLimit: 20,
    riskLevel: 'low',
    cardType: 'orderCustomerConsumptionList',
    implemented: true,
  },
  {
    id: 'project_service_trend',
    domain: 'project',
    name: '项目服务趋势',
    description: '查询项目服务次数、收入和趋势',
    allowedRoles: ['manager', 'reception', 'beautician'],
    defaultParams: { dateRange: 'last_30_days', limit: 10 },
    resultLimit: 10,
    riskLevel: 'low',
    cardType: 'projectServiceTrend',
    implemented: true,
  },
  {
    id: 'project_material_margin',
    domain: 'project',
    name: '项目耗材毛利',
    description: '按项目价格、BOM 标准用量和商品成本估算项目耗材成本与毛利空间',
    allowedRoles: ['manager'],
    defaultParams: { limit: 10 },
    resultLimit: 10,
    riskLevel: 'medium',
    cardType: 'projectMaterialMargin',
    implemented: true,
  },
  {
    id: 'member_card_lookup',
    domain: 'card',
    name: '客户卡项详情',
    description: '根据客户卡项实体查询剩余次数、到期和最近核销记录',
    allowedRoles: ['manager', 'reception'],
    defaultParams: { limit: 10 },
    resultLimit: 10,
    riskLevel: 'low',
    cardType: 'memberCardLookup',
    implemented: true,
  },
  {
    id: 'card_expiry_risk',
    domain: 'card',
    name: '卡项到期风险',
    description: '查询即将到期次卡和剩余次数',
    allowedRoles: ['manager', 'reception'],
    defaultParams: { dateRange: 'next_30_days', limit: 10 },
    resultLimit: 10,
    riskLevel: 'low',
    cardType: 'cardExpiryRisk',
    implemented: true,
  },
  {
    id: 'card_usage_analysis',
    domain: 'card',
    name: '卡项核销分析',
    description: '查询次卡核销数量、核销趋势和高频核销卡项',
    allowedRoles: ['manager', 'reception'],
    defaultParams: { dateRange: 'last_30_days', limit: 10 },
    resultLimit: 10,
    riskLevel: 'low',
    cardType: 'cardUsageAnalysis',
    implemented: true,
  },
  {
    id: 'member_balance_analysis',
    domain: 'memberCard',
    name: '会员卡余额分析',
    description: '查询储值余额、充值和沉淀资金',
    allowedRoles: ['manager', 'reception'],
    defaultParams: { limit: 10 },
    resultLimit: 10,
    riskLevel: 'medium',
    cardType: 'memberBalanceAnalysis',
    implemented: true,
  },
  {
    id: 'finance_cashflow_summary',
    domain: 'finance',
    name: '财务现金流摘要',
    description: '查询实收、退款、结算和费用摘要',
    allowedRoles: ['manager'],
    defaultParams: { dateRange: 'today', limit: 10 },
    resultLimit: 10,
    riskLevel: 'medium',
    cardType: 'financeCashflowSummary',
    implemented: true,
  },
  {
    id: 'marketing_activity_list',
    domain: 'marketing',
    name: '营销活动清单',
    description: '查询近期营销活动、草稿、已发布活动和进行中活动清单',
    allowedRoles: ['manager', 'reception'],
    defaultParams: { dateRange: 'last_30_days', limit: 10 },
    resultLimit: 10,
    riskLevel: 'low',
    cardType: 'marketingActivityList',
    implemented: true,
  },
  {
    id: 'marketing_activity_link_lookup',
    domain: 'marketing',
    name: '营销活动链接查询',
    description: '根据营销活动或推广页实体查询活动链接、小程序路径和二维码',
    allowedRoles: ['manager', 'reception'],
    defaultParams: { limit: 5 },
    resultLimit: 5,
    riskLevel: 'low',
    cardType: 'marketingActivityLink',
    implemented: true,
  },
  {
    id: 'marketing_conversion',
    domain: 'marketing',
    name: '营销转化分析',
    description: '查询活动触达、转化、收入和归因',
    allowedRoles: ['manager'],
    defaultParams: { dateRange: 'last_30_days', limit: 10 },
    resultLimit: 10,
    riskLevel: 'low',
    cardType: 'marketingConversion',
    implemented: true,
  },
  {
    id: 'automation_execution_summary',
    domain: 'automation',
    name: '自动化执行复盘',
    description: '查询自动化执行、触达、转化和归因收入',
    allowedRoles: ['manager'],
    defaultParams: { dateRange: 'last_30_days', limit: 10 },
    resultLimit: 10,
    riskLevel: 'low',
    cardType: 'automationExecutionSummary',
    implemented: true,
  },
  {
    id: 'supplier_purchase_advice',
    domain: 'supplyChain',
    name: '供应链采购建议',
    description: '结合补货需求、主供应商、采购价、起订量和交期给出采购优先级',
    allowedRoles: ['manager'],
    defaultParams: { dateRange: 'last_30_days', limit: 10 },
    resultLimit: 10,
    riskLevel: 'medium',
    cardType: 'supplierPurchaseAdvice',
    implemented: true,
  },
  {
    id: 'business_anomaly_alert',
    domain: 'business',
    name: '经营异常主动提醒',
    description: '扫描收入、预约、库存、客户和自动化数据，识别需要店长关注的异常',
    allowedRoles: ['manager'],
    defaultParams: { dateRange: 'today', limit: 10 },
    resultLimit: 10,
    riskLevel: 'medium',
    cardType: 'businessAnomalyAlert',
    implemented: true,
  },
  {
    id: 'multi_store_comparison',
    domain: 'store',
    name: '多门店对比',
    description: '跨门店对比收入、客户、库存和转化，需要多门店权限',
    allowedRoles: ['manager'],
    defaultParams: { dateRange: 'last_30_days', limit: 10 },
    resultLimit: 10,
    riskLevel: 'high',
    cardType: 'multiStoreComparison',
    implemented: true,
  },
  {
    id: 'schedule_utilization',
    domain: 'schedule',
    name: '排班利用率',
    description: '查询美容师排班、忙闲、请假和时段占用率',
    allowedRoles: ['manager', 'reception', 'beautician'],
    defaultParams: { dateRange: 'today', limit: 20 },
    resultLimit: 20,
    riskLevel: 'low',
    cardType: 'scheduleUtilization',
    implemented: true,
  },
  {
    id: 'staff_performance',
    domain: 'staff',
    name: '员工表现',
    description: '查询员工业绩、提成、服务完成率和服务质量',
    allowedRoles: ['manager'],
    defaultParams: { dateRange: 'month_to_date', limit: 10 },
    resultLimit: 10,
    riskLevel: 'medium',
    cardType: 'staffPerformance',
    implemented: true,
  },
  {
    id: 'terminal_health_diagnosis',
    domain: 'terminal',
    name: '终端设备与对话诊断',
    description: '查询终端设备在线状态、外设状态、会话数量和高频失败问题',
    allowedRoles: ['manager'],
    defaultParams: { dateRange: 'last_30_days', limit: 10 },
    resultLimit: 10,
    riskLevel: 'low',
    cardType: 'terminalHealthDiagnosis',
    implemented: true,
  },
];

export function getBusinessQueryCapability(id: string) {
  return BUSINESS_QUERY_CAPABILITIES.find((item) => item.id === id);
}
