import {
  AlertTriangle,
  BadgeCheck,
  BarChart3,
  Building2,
  Calendar,
  CalendarCheck,
  CheckCircle2,
  ClipboardList,
  CreditCard,
  FileText,
  HeartPulse,
  LayoutDashboard,
  Megaphone,
  Monitor,
  PackageCheck,
  PackagePlus,
  Shield,
  ShoppingCart,
  Sparkles,
  TrendingUp,
  UserPlus,
  Users,
  WalletCards,
  type LucideIcon,
} from 'lucide-react';

export const workbenchIconMap: Record<string, LucideIcon> = {
  AlertTriangle,
  BadgeCheck,
  BarChart3,
  Building2,
  Calendar,
  CalendarCheck,
  CheckCircle2,
  ClipboardList,
  CreditCard,
  FileText,
  HeartPulse,
  LayoutDashboard,
  Megaphone,
  Monitor,
  PackageCheck,
  PackagePlus,
  Shield,
  ShoppingCart,
  Sparkles,
  TrendingUp,
  UserPlus,
  Users,
  WalletCards,
};

export const metricIconByKey: Record<string, LucideIcon> = {
  activeStores: Building2,
  campaigns: Megaphone,
  cashierToday: CreditCard,
  customers: Users,
  expiringBatches: AlertTriangle,
  income: TrendingUp,
  incomeToday: TrendingUp,
  inventory: PackageCheck,
  inventoryAlerts: PackageCheck,
  lowStock: PackageCheck,
  myCommission: WalletCards,
  myReservations: CalendarCheck,
  onlineDevices: Monitor,
  pendingCardUsage: BadgeCheck,
  pendingCheckIn: CheckCircle2,
  pendingServices: HeartPulse,
  purchasePending: ShoppingCart,
  serviceRecordsTodo: FileText,
  storeAlerts: AlertTriangle,
  todayReservations: CalendarCheck,
  totalIncomeToday: TrendingUp,
  transferPending: PackagePlus,
};

export const todoIconByType: Record<string, LucideIcon> = {
  customer: Users,
  device: Monitor,
  finance: WalletCards,
  inventory: PackageCheck,
  marketing: Sparkles,
  order: CreditCard,
  reservation: CalendarCheck,
  service: HeartPulse,
  system: Shield,
};

export function getWorkbenchIcon(iconName?: string, fallback: LucideIcon = LayoutDashboard): LucideIcon {
  if (!iconName) return fallback;
  return workbenchIconMap[iconName] ?? fallback;
}
