import type { ReadOnlySqlField, ReadOnlySqlView } from '../read-only-sql-kernel/read-only-sql-kernel.types.js';

const text = (name: string, description: string, policy: ReadOnlySqlField['policy'] = 'allow'): ReadOnlySqlField => ({
  name,
  type: 'string',
  description,
  policy,
});
const number = (name: string, description: string, policy: ReadOnlySqlField['policy'] = 'allow'): ReadOnlySqlField => ({
  name,
  type: 'number',
  description,
  policy,
});
const date = (name: string, description: string, policy: ReadOnlySqlField['policy'] = 'allow'): ReadOnlySqlField => ({
  name,
  type: 'date',
  description,
  policy,
});
const boolean = (name: string, description: string): ReadOnlySqlField => ({
  name,
  type: 'boolean',
  description,
  policy: 'allow',
});

const base = [number('store_id', '授权门店 ID'), text('store_name', '门店名称')];

export const ASK_DATA_FREE_SQL_VIEWS: ReadOnlySqlView[] = [
  {
    viewName: 'agent_v3_order_summary_view',
    label: '订单摘要',
    domain: 'order',
    description: '订单、成交、实收、退款和净收摘要。',
    keywords: ['订单', '营业额', '实收', '退款', '净收', '支付方式'],
    dataPolicy: '金额按订单实收与退款口径展示；客户姓名脱敏，不开放手机号和订单备注。',
    requiredPermissions: ['core:finance:view'],
    storeScopeField: 'store_id',
    defaultTimeField: 'order_created_at',
    fields: [
      ...base,
      number('order_id', '订单 ID'),
      date('order_created_at', '下单时间'),
      number('customer_id', '客户 ID'),
      text('customer_name_masked', '脱敏客户姓名', 'mask'),
      text('order_status', '订单状态'),
      number('total_amount', '订单总额'),
      number('paid_amount', '实收金额'),
      number('refund_amount', '退款金额'),
      number('net_amount', '净收金额'),
      text('pay_method', '支付方式'),
    ],
    allowJoin: true,
  },
  {
    viewName: 'agent_v3_order_item_sales_view',
    label: '商品销售',
    domain: 'product',
    description: '商品销售明细、销量排行和销售额排行。',
    keywords: ['商品销售', '销量', '销售额', 'SKU', '商品排行', '优惠金额'],
    dataPolicy: '按订单商品明细统计净销售额与退款，不开放订单内部载荷。',
    requiredPermissions: ['core:order:products', 'core:goods:products'],
    storeScopeField: 'store_id',
    defaultTimeField: 'order_created_at',
    fields: [
      ...base,
      number('order_id', '订单 ID'),
      date('order_created_at', '订单时间'),
      number('product_id', '商品 ID'),
      text('product_name', '商品名称'),
      text('sku', 'SKU'),
      text('category_name', '商品分类'),
      number('quantity', '销售数量'),
      number('gross_amount', '销售原额'),
      number('discount_amount', '优惠金额'),
      number('net_amount', '净销售额'),
      number('refund_amount', '退款金额'),
      text('order_status', '订单状态'),
    ],
    allowJoin: true,
  },
  {
    viewName: 'agent_v3_project_service_sales_view',
    label: '项目服务销售',
    domain: 'project',
    description: '项目服务次数、项目销售额和预估毛利。',
    keywords: ['项目收入', '服务次数', '项目排行', '预估毛利', '护理项目'],
    dataPolicy: '毛利为项目销售口径的预估值，不等同于已确认月结利润。',
    requiredPermissions: ['core:order:projects', 'core:store:projects'],
    storeScopeField: 'store_id',
    defaultTimeField: 'order_created_at',
    fields: [
      ...base,
      number('project_id', '项目 ID'),
      text('project_name', '项目名称'),
      text('project_type', '项目分类'),
      date('order_created_at', '订单时间'),
      number('service_quantity', '服务次数'),
      number('net_amount', '项目净销售额'),
      number('estimated_material_cost', '预估耗材成本'),
      number('estimated_margin', '预估毛利'),
    ],
    allowJoin: true,
  },
  {
    viewName: 'ask_data_item_margin_view',
    label: '商品与项目贡献毛利',
    domain: 'finance',
    description: '商品销售、项目销售、次卡核销和退款冲减的可归属成本与贡献毛利。',
    keywords: ['商品毛利', '产品毛利', '项目毛利', '项目耗材成本', '贡献毛利', '低于成本', '亏损项目'],
    dataPolicy: '贡献毛利=已识别净收入-可归属商品/耗材成本，不含员工提成和经营费用；多数历史成本使用商品档案成本或 BOM 标准成本估算，不等同已确认月结利润。',
    requiredPermissions: ['core:operation-profit:view'],
    storeScopeField: 'store_id',
    defaultTimeField: 'event_at',
    fields: [
      ...base,
      text('event_id', '经济事件 ID'),
      text('event_type', '事件类型：order_sale、card_redemption 或 refund'),
      date('event_at', '收入识别、次卡核销或退款发生时间'),
      text('item_type', '项目类型：product 或 project'),
      number('item_id', '商品或项目 ID'),
      text('item_name', '商品或项目名称'),
      number('product_id', '商品 ID'),
      text('product_name', '商品名称'),
      text('sku', 'SKU'),
      number('project_id', '项目 ID'),
      text('project_name', '项目名称'),
      text('project_type', '项目分类'),
      number('quantity', '事件数量；退款事件为负数'),
      number('gross_revenue', '原始收入'),
      number('discount_amount', '优惠金额'),
      number('refund_amount', '退款冲减金额'),
      number('net_revenue', '已识别净收入；退款事件为负数'),
      number('attributed_cost', '可归属商品或耗材成本；返库成本冲回为负数'),
      number('contribution_margin', '贡献毛利'),
      number('contribution_margin_rate', '贡献毛利率'),
      text('revenue_basis', '收入口径'),
      text('cost_basis', '成本口径'),
      text('refund_basis', '退款归属口径'),
      boolean('is_estimated_cost', '是否包含估算成本'),
      text('cost_completeness', '成本完整性'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'agent_v3_payment_refund_view',
    label: '支付与退款',
    domain: 'finance',
    description: '支付、退款和售后退款摘要。',
    keywords: ['支付', '退款', '支付方式', '售后退款', '退款原因'],
    dataPolicy: '仅开放支付与退款汇总字段，不开放支付流水号和内部处理备注。',
    requiredPermissions: ['core:finance:view'],
    storeScopeField: 'store_id',
    defaultTimeField: 'paid_at',
    fields: [
      ...base,
      number('order_id', '订单 ID'),
      date('paid_at', '支付时间'),
      date('refunded_at', '退款时间'),
      text('payment_method', '支付方式'),
      number('payment_amount', '支付金额'),
      number('refund_amount', '退款金额'),
      text('payment_status', '支付状态'),
      text('refund_status', '退款状态'),
      text('refund_reason_category', '退款原因分类'),
    ],
    allowJoin: true,
  },
  {
    viewName: 'agent_v3_daily_settlement_view',
    label: '日结',
    domain: 'finance',
    description: '日收入、退款、净收、订单数和客户数。',
    keywords: ['日结', '每日收入', '营业额趋势', '净收趋势', '订单数', '客户数'],
    dataPolicy: '按门店业务日汇总收入、退款和净收，不代表已确认月度利润。',
    requiredPermissions: ['core:finance:view'],
    storeScopeField: 'store_id',
    defaultTimeField: 'settlement_date',
    fields: [
      ...base,
      date('settlement_date', '结算日期'),
      number('revenue_amount', '收入'),
      number('paid_amount', '实收'),
      number('refund_amount', '退款'),
      number('net_amount', '净收'),
      number('order_count', '订单数'),
      number('customer_count', '客户数'),
    ],
    allowJoin: true,
  },
  {
    viewName: 'agent_v3_product_inventory_view',
    label: '商品库存',
    domain: 'inventory',
    description: '商品当前库存、安全库存、库存金额和最近效期。',
    keywords: ['库存', '安全库存', '低库存', '库存金额', '效期', '缺货'],
    dataPolicy: '展示当前库存快照和最近效期，不开放供应商合同或批次内部备注。',
    requiredPermissions: ['core:inventory:products', 'core:inventory:stock'],
    storeScopeField: 'store_id',
    requiresTimeScope: false,
    fields: [
      ...base,
      number('product_id', '商品 ID'),
      text('product_name', '商品名称'),
      text('sku', 'SKU'),
      text('unit', '单位'),
      number('current_stock', '当前库存'),
      number('safety_stock', '安全库存'),
      number('stock_value', '库存金额'),
      text('status', '库存状态'),
      date('nearest_expiry_date', '最近效期'),
    ],
    allowJoin: true,
  },
  {
    viewName: 'agent_v3_stock_movement_view',
    label: '库存流水',
    domain: 'inventory',
    description: '入库、出库、盘点和库存变化流水。',
    keywords: ['库存流水', '入库', '出库', '盘点', '库存变化', '耗材'],
    dataPolicy: '出库数量使用负数记录；统计出库量时按 ABS(quantity) 计算。',
    requiredPermissions: ['core:inventory:stock', 'core:inventory:consumption'],
    storeScopeField: 'store_id',
    defaultTimeField: 'occurred_at',
    fields: [
      ...base,
      number('movement_id', '流水 ID'),
      number('product_id', '商品 ID'),
      text('product_name', '商品名称'),
      text('sku', 'SKU'),
      text(
        'movement_type',
        '流水类型；常见出库包括 sale_out、service_consume、service_consumption、scrap_out、transfer_out、manual_outbound',
      ),
      number('quantity', '库存变化量；出库为负数，统计出库数量使用 ABS(quantity) 并筛选 quantity < 0'),
      number('before_stock', '变更前库存'),
      number('after_stock', '变更后库存'),
      text('source_type', '来源类型'),
      date('occurred_at', '发生时间'),
    ],
    allowJoin: true,
  },
  {
    viewName: 'agent_v3_inventory_scrap_view',
    label: '库存报废',
    domain: 'inventory',
    description: '报废数量、损耗金额和操作摘要。',
    keywords: ['报废', '损耗', '损耗金额', '报废商品', '库存损失'],
    dataPolicy: '仅开放报废业务摘要；备注为受控摘要，不开放原始内部记录。',
    requiredPermissions: ['core:inventory:consumption'],
    storeScopeField: 'store_id',
    defaultTimeField: 'occurred_at',
    fields: [
      ...base,
      number('movement_id', '流水 ID'),
      number('product_id', '商品 ID'),
      text('product_name', '商品名称'),
      text('sku', 'SKU'),
      number('scrap_quantity', '报废数量'),
      number('loss_amount', '损耗金额'),
      date('occurred_at', '发生时间'),
      text('operator_name', '操作人'),
      text('remark_summary', '备注摘要'),
    ],
    allowJoin: true,
  },
  {
    viewName: 'ask_data_inventory_turnover_view',
    label: '库存周转与采购覆盖',
    domain: 'inventory',
    description: '商品库存覆盖天数、运营周转、慢动销、需求变化、采购覆盖和估算消耗成本。',
    keywords: [
      '库存周转',
      '库存可用天数',
      '还能用多久',
      '慢动销',
      '库存积压',
      '需求增加',
      '低于安全库存',
      '未采购',
      '在途采购',
      '每日耗材费用',
    ],
    dataPolicy: '周转率为近 30 天库存事件加权的运营指标，不等同于财务库存周转率；成本按商品档案成本估算，不代表批次实际采购成本；采购覆盖只陈述事实，不生成补货建议。',
    noDataHint: '当前门店尚无商品库存档案，无法计算库存周转与采购覆盖事实。',
    freshnessField: 'data_as_of',
    requiredPermissions: ['core:inventory:stock'],
    storeScopeField: 'store_id',
    requiresTimeScope: false,
    fields: [
      ...base,
      number('product_id', '商品 ID'),
      text('product_name', '商品名称'),
      text('sku', 'SKU'),
      text('category_name', '商品分类'),
      text('unit', '单位'),
      text('product_status', '商品状态'),
      number('current_stock', '当前库存'),
      number('safety_stock', '安全库存'),
      number('catalog_cost_price', '商品档案成本单价；属于估算口径'),
      number('current_stock_value', '按商品档案成本估算的当前库存金额'),
      number('outbound_quantity_30d', '最近 30 天出库量'),
      number('outbound_quantity_previous_30d', '前一个 30 天窗口出库量'),
      number('outbound_quantity_90d', '最近 90 天出库量'),
      number('outbound_quantity_current_month', '当前自然月累计出库量'),
      number('outbound_quantity_current_quarter', '当前自然季度累计出库量'),
      number('avg_daily_outbound_30d', '最近 30 天日均出库量'),
      number('avg_daily_outbound_90d', '最近 90 天日均出库量'),
      number('event_weighted_avg_stock_30d', '最近 30 天库存事件加权平均库存'),
      number('estimated_outbound_cost_30d', '最近 30 天按商品档案成本估算的出库成本'),
      number('estimated_avg_daily_outbound_cost_30d', '最近 30 天按商品档案成本估算的日均出库成本'),
      number('estimated_outbound_cost_current_month', '当前自然月按商品档案成本估算的累计出库成本'),
      number('estimated_avg_daily_outbound_cost_current_month', '当前自然月按已过自然日估算的日均出库成本'),
      date('last_outbound_at', '最近出库时间'),
      date('last_inbound_at', '最近入库或正向库存变动时间'),
      number('positive_batch_count', '当前正库存批次数'),
      date('nearest_expiry_date', '最近效期'),
      date('oldest_positive_batch_created_at', '当前正库存批次中最早建档时间；不是开封时间'),
      number('open_procurement_order_count', '未完成采购单数'),
      number('open_procurement_quantity', '未完成采购待到货数量'),
      date('expected_arrival_date', '最近预计到货时间'),
      number('procurement_order_count_90d', '最近 90 天非取消采购单数'),
      number('procurement_ordered_quantity_90d', '最近 90 天非取消采购数量'),
      date('last_procurement_at', '最近非取消采购单创建时间'),
      number('days_of_stock_30d', '按最近 30 天日均出库计算的库存可用天数；无消耗时为空'),
      number('operational_turnover_ratio_30d', '近 30 天运营周转率'),
      number('demand_change_rate_30d', '近 30 天需求变化率'),
      text('slow_moving_status', '慢动销状态'),
      text('replenishment_fact_status', '采购覆盖状态'),
      number('slow_moving_turnover_threshold_30d', '低周转治理阈值，当前为 0.5'),
      text('turnover_policy', '运营周转口径标识'),
      text('cost_policy', '成本估算口径标识'),
      date('data_as_of', '数据计算时间'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'ask_data_customer_profile_summary_view',
    label: '客户档案摘要',
    domain: 'customer',
    description: '客户等级、来源、生日窗口、到店复购、次卡使用和生命周期摘要。',
    keywords: ['客户', '会员等级', '最近到店', '累计消费', '复购', '沉睡客户', '生日客户', '客户来源', '次卡未使用'],
    dataPolicy: '客户只展示 ID、脱敏姓名、年龄段和生日窗口；不开放精确生日、手机号、标签原文、健康信息或生命周期证据。',
    freshnessField: 'data_as_of',
    requiredPermissions: ['core:customer:view'],
    storeScopeField: 'store_id',
    requiresTimeScope: false,
    fields: [
      ...base,
      number('customer_id', '客户 ID'),
      text('customer_name_masked', '脱敏客户姓名', 'mask'),
      text('member_level', '会员等级'),
      date('last_visit_at', '最近到店时间'),
      date('last_order_at', '最近消费时间'),
      number('total_paid_amount', '累计实收'),
      number('order_count', '订单数'),
      text('source_channel', '客户来源渠道'),
      text('age_band', '年龄段：under_25、25_34、35_44、45_54、55_plus、unknown'),
      date('next_birthday_date', '下一个生日日期；不包含出生年份'),
      number('days_until_birthday', '距离下一个生日的天数'),
      date('first_order_at', '首次消费时间'),
      date('first_reservation_at', '首次预约日期'),
      date('last_reservation_at', '最近预约日期'),
      number('reservation_count', '预约数'),
      number('completed_reservation_count', '到店或已完成预约数'),
      number('days_since_last_visit', '距最近到店或消费天数'),
      number('average_return_interval_days', '平均复购到店间隔天数'),
      number('active_card_count', '当前有效次卡数'),
      number('remaining_card_times', '有效次卡剩余总次数'),
      number('unused_card_count', '购买后尚未使用的有效次卡数'),
      number('low_remaining_card_count', '剩余 1—2 次的有效次卡数'),
      date('first_card_purchase_at', '首次购卡时间'),
      date('last_card_purchase_at', '最近购卡时间'),
      number('card_usage_times', '累计次卡核销次数'),
      date('last_card_usage_at', '最近次卡核销时间'),
      text('lifecycle_stage', '客户生命周期阶段'),
      text('ltv_tier', '客户价值档位'),
      text('churn_risk_level', '流失风险等级'),
      text('customer_status', '客户状态：prospect、new、repeat、inactive'),
      date('data_as_of', '数据更新时间'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'agent_v3_staff_profile_view',
    label: '员工档案',
    domain: 'staff',
    description: '美容师和员工基础资料。',
    keywords: ['员工', '美容师', '在职员工', '员工级别', '员工人数'],
    dataPolicy: '只开放员工经营基础资料，不开放薪资、联系方式和人事备注。',
    requiredPermissions: ['core:store:beauticians'],
    storeScopeField: 'store_id',
    requiresTimeScope: false,
    fields: [
      ...base,
      number('staff_id', '员工 ID'),
      text('staff_name', '员工姓名'),
      text('level_name', '级别'),
      text('status', '员工状态；active 表示在职，inactive 表示停用'),
      date('created_at', '创建时间'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'ask_data_staff_performance_view',
    label: '员工绩效',
    domain: 'staff',
    description: '员工人效、提成、服务量和客单价摘要。',
    keywords: ['员工绩效', '员工排行', '提成', '服务量', '客单价', '人效'],
    dataPolicy: '展示经营绩效汇总，不开放员工薪资明细和考核备注。',
    requiredPermissions: ['core:beautician-performance:view'],
    storeScopeField: 'store_id',
    defaultTimeField: 'settle_month',
    fields: [
      ...base,
      number('staff_id', '员工 ID'),
      text('staff_name', '员工姓名'),
      date('settle_month', '结算月份'),
      number('paid_amount', '业绩金额'),
      number('average_order_amount', '平均客单价'),
      number('commission_amount', '提成金额'),
      number('service_count', '服务量'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'agent_v3_reservation_view',
    label: '预约',
    domain: 'reservation',
    description: '预约记录、项目、美容师和预约状态。',
    keywords: ['预约', '预约取消率', '到店', '预约状态', '美容师预约'],
    dataPolicy: '客户姓名脱敏；不开放手机号、健康信息和预约备注。',
    requiredPermissions: ['core:store:reservations'],
    storeScopeField: 'store_id',
    defaultTimeField: 'date',
    fields: [
      ...base,
      number('reservation_id', '预约 ID'),
      number('customer_id', '客户 ID'),
      text('customer_name_masked', '脱敏客户姓名', 'mask'),
      number('project_id', '项目 ID'),
      text('project_name', '项目名称'),
      text('project_type', '项目类型'),
      number('beautician_id', '美容师 ID'),
      text('beautician_name', '美容师名称'),
      date('date', '预约日期'),
      text('start_time', '开始时间'),
      text('status', '预约状态：pending、confirmed、checked_in、completed、cancelled；取消率分子为 cancelled'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'agent_v3_marketing_conversion_view',
    label: '营销转化',
    domain: 'marketing',
    description: '营销活动事件、线索、转化和归因收入。',
    keywords: ['营销转化', '线索', '转化数', '归因收入', '触达事件'],
    dataPolicy: '使用营销归因汇总，不开放客户级触达内容和渠道身份信息。',
    requiredPermissions: ['core:marketing:analytics'],
    storeScopeField: 'store_id',
    defaultTimeField: 'latest_event_at',
    fields: [
      ...base,
      number('activity_id', '活动 ID'),
      text('activity_title', '活动名称'),
      number('event_count', '触达事件数'),
      number('lead_count', '线索数'),
      number('conversion_count', '转化数'),
      number('attributed_revenue', '归因收入'),
      date('latest_event_at', '最近事件时间'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'agent_v3_card_asset_view',
    label: '次卡资产',
    domain: 'card',
    description: '客户次卡的总次数、剩余次数、实收金额、到期时间和状态。',
    keywords: ['次卡', '卡项', '剩余次数', '到期', '过期', '会员权益'],
    dataPolicy: '客户姓名脱敏；只展示当前门店客户持有的次卡资产。',
    requiredPermissions: ['core:order:member-cards'],
    storeScopeField: 'store_id',
    defaultTimeField: 'expiry_date',
    requiresTimeScope: false,
    fields: [
      ...base,
      number('customer_id', '客户 ID'),
      text('customer_name_masked', '脱敏客户姓名', 'mask'),
      number('customer_card_id', '客户卡 ID'),
      text('card_name', '卡项名称'),
      number('total_times', '总次数'),
      number('remaining_times', '剩余次数'),
      number('paid_amount', '购卡实收金额'),
      date('expiry_date', '到期日期'),
      text('status', '卡状态'),
    ],
    allowJoin: true,
  },
  {
    viewName: 'agent_v3_card_usage_view',
    label: '次卡核销',
    domain: 'card',
    description: '次卡核销次数、确认收入和核销后剩余次数。',
    keywords: ['次卡核销', '划扣', '核销', '确认收入', '卡耗'],
    dataPolicy: '客户姓名脱敏；确认收入使用核销记录的 recognized_amount。',
    requiredPermissions: ['core:order:card-usage'],
    storeScopeField: 'store_id',
    defaultTimeField: 'verified_at',
    fields: [
      ...base,
      number('customer_id', '客户 ID'),
      text('customer_name_masked', '脱敏客户姓名', 'mask'),
      text('card_name', '卡项名称'),
      text('project_name', '项目名称'),
      number('times', '核销次数'),
      number('remaining_times', '剩余次数'),
      number('recognized_amount', '确认收入金额'),
      date('verified_at', '核销时间'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'agent_v3_customer_balance_view',
    label: '客户余额',
    domain: 'card',
    description: '客户现金余额、赠送余额和账户状态。',
    keywords: ['客户余额', '储值余额', '现金余额', '赠送余额', '会员资产'],
    dataPolicy: '客户姓名脱敏；不开放余额流水备注和支付信息。',
    requiredPermissions: ['core:prepaid-liability:view'],
    storeScopeField: 'store_id',
    defaultTimeField: 'updated_at',
    requiresTimeScope: false,
    fields: [
      ...base,
      number('customer_id', '客户 ID'),
      text('customer_name_masked', '脱敏客户姓名', 'mask'),
      number('cash_balance', '现金余额'),
      number('gift_balance', '赠送余额'),
      text('status', '账户状态'),
      date('updated_at', '更新时间'),
    ],
    allowJoin: true,
  },
  {
    viewName: 'agent_v3_service_quality_view',
    label: '服务质量',
    domain: 'service',
    description: '服务任务的项目、员工、服务状态和完成时间。',
    keywords: ['服务质量', '服务任务', '护理完成', '服务完成率', '项目服务'],
    dataPolicy: '仅开放服务任务状态，不开放护理记录和客户健康原文。',
    requiredPermissions: ['core:store:reservations'],
    storeScopeField: 'store_id',
    defaultTimeField: 'appointment_time',
    fields: [
      ...base,
      number('service_task_id', '服务任务 ID'),
      number('customer_id', '客户 ID'),
      number('project_id', '项目 ID'),
      text('project_name', '项目名称'),
      number('beautician_id', '美容师 ID'),
      text('beautician_name', '美容师姓名'),
      text('status', '服务状态：pending、in_progress、completed、cancelled、no_show；已完成仅对应 completed'),
      date('appointment_time', '预约时间'),
      date('completed_at', '完成时间'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'agent_v3_appointment_gap_view',
    label: '预约空档',
    domain: 'reservation',
    description: '可邀约空档、可用容量、候选客户数和预计收入。',
    keywords: ['空档', '预约空档', '低峰', '可用容量', '邀约机会'],
    dataPolicy: '只展示机会汇总，不开放候选客户名单。',
    requiredPermissions: ['core:store:scheduling:gap:view'],
    storeScopeField: 'store_id',
    defaultTimeField: 'date',
    fields: [
      ...base,
      number('opportunity_id', '机会 ID'),
      date('date', '日期'),
      text('start_time', '开始时间'),
      text('end_time', '结束时间'),
      number('available_capacity', '可用容量'),
      number('estimated_revenue', '预计收入'),
      number('candidate_count', '候选客户数'),
      text('status', '机会状态'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'agent_v3_project_catalog_view',
    label: '项目目录',
    domain: 'project',
    description: '项目价格、服务时长、护理周期、疗程次数和状态。',
    keywords: ['项目目录', '项目价格', '服务时长', '护理周期', '疗程'],
    dataPolicy: '仅查询当前门店未删除项目。',
    requiredPermissions: ['core:store:projects'],
    storeScopeField: 'store_id',
    defaultTimeField: 'updated_at',
    requiresTimeScope: false,
    fields: [
      ...base,
      number('project_id', '项目 ID'),
      text('project_name', '项目名称'),
      text('project_type', '项目类型'),
      number('price', '项目价格'),
      number('duration', '服务时长（分钟）'),
      number('care_cycle_weeks', '护理周期周数'),
      number('treatment_course_times', '疗程次数'),
      text('status', '项目状态'),
      date('updated_at', '更新时间'),
    ],
    allowJoin: true,
  },
  {
    viewName: 'agent_v3_marketing_activity_view',
    label: '营销活动',
    domain: 'marketing',
    description: '当前门店营销活动的发布状态、活动周期、参与和转化。',
    keywords: ['营销活动', '活动列表', '活动状态', '参与人数', '发布状态'],
    dataPolicy: '直接使用活动所属门店，不通过营销页面推断门店。',
    requiredPermissions: ['core:marketing:view'],
    storeScopeField: 'store_id',
    defaultTimeField: 'start_at',
    fields: [
      ...base,
      number('activity_id', '活动 ID'),
      text('activity_title', '活动名称'),
      text('status', '活动状态'),
      text('publish_status', '发布状态'),
      date('start_at', '开始时间'),
      date('end_at', '结束时间'),
      number('participants', '参与人数'),
      text('conversion', '转化率文本，例如 0%'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'agent_v3_marketing_automation_view',
    label: '自动触达',
    domain: 'marketing',
    description: '自动触达任务来源、触发类型、执行状态和完成量。',
    keywords: ['自动触达', '自动化', '跟进任务', '触达完成', '触达状态'],
    dataPolicy: '仅展示任务聚合，不开放客户触达话术和备注。',
    requiredPermissions: ['core:marketing:view'],
    storeScopeField: 'store_id',
    defaultTimeField: 'latest_task_at',
    fields: [
      ...base,
      text('automation_source', '自动化来源'),
      text('trigger_type', '触发类型'),
      text('status', '执行状态'),
      number('task_count', '任务数'),
      date('latest_task_at', '最近任务时间'),
      number('completed_count', '完成数'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'agent_v3_promotion_offer_view',
    label: '优惠活动',
    domain: 'marketing',
    description: '门店可见的门店优惠和全局优惠配置及使用情况。',
    keywords: ['优惠活动', '促销', '优惠券', '发放', '核销', '折扣'],
    dataPolicy: '全局优惠复制到各门店查询视角，并用 scope_type 标明范围。',
    requiredPermissions: ['core:marketing:view'],
    storeScopeField: 'store_id',
    defaultTimeField: 'start_at',
    fields: [
      ...base,
      number('promotion_id', '优惠 ID'),
      text('promotion_name', '优惠名称'),
      text('type', '优惠类型'),
      text('scenario', '适用场景'),
      text('discount_text', '优惠说明'),
      number('issued_count', '发放数'),
      number('used_count', '使用数'),
      text('status', '状态'),
      date('start_at', '开始时间'),
      date('end_at', '结束时间'),
      text('scope_type', '范围：global 或 store'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'ask_data_operating_cost_view',
    label: '经营成本',
    domain: 'finance',
    description: '经营费用的月份、日期、类别、金额和分摊方式。',
    keywords: ['经营成本', '费用', '租金', '水电', '成本类别', '费用结构'],
    dataPolicy: '使用经营成本台账，不将订单成本混入经营费用。',
    requiredPermissions: ['core:operation-cost:view'],
    storeScopeField: 'store_id',
    defaultTimeField: 'cost_date',
    fields: [
      ...base,
      number('cost_id', '成本 ID'),
      date('period_month', '所属月份'),
      date('cost_date', '成本日期'),
      text('category', '成本类别'),
      number('amount', '成本金额'),
      text('allocation_type', '分摊类型'),
    ],
    allowJoin: true,
  },
  {
    viewName: 'agent_v3_purchase_procurement_view',
    label: '采购',
    domain: 'supply',
    description: '采购单、供应商、采购金额、状态和到货时间。',
    keywords: ['采购', '采购单', '到货', '供应商', '采购金额'],
    dataPolicy: '采购管理或供应链查看权限任一满足即可查询。',
    requiredPermissions: ['core:inventory:purchase', 'core:supply:view'],
    permissionMode: 'any',
    storeScopeField: 'store_id',
    defaultTimeField: 'created_at',
    fields: [
      ...base,
      number('procurement_id', '采购单 ID'),
      text('procurement_no', '采购单号'),
      number('supplier_id', '供应商 ID'),
      text('supplier_name', '供应商名称'),
      text('status', '采购状态'),
      number('total_amount', '采购金额'),
      date('expected_arrival_date', '预计到货日期'),
      date('created_at', '创建时间'),
      date('received_at', '到货时间'),
    ],
    allowJoin: true,
  },
  {
    viewName: 'agent_v3_supplier_performance_view',
    label: '供应商表现',
    domain: 'supply',
    description: '供应商采购次数、采购金额和平均交付天数。',
    keywords: ['供应商表现', '供应商排行', '交付天数', '采购次数'],
    dataPolicy: '交付天数按采购创建至到货或最近更新时间计算。',
    requiredPermissions: ['core:supply:view'],
    storeScopeField: 'store_id',
    defaultTimeField: 'last_procurement_at',
    fields: [
      ...base,
      number('supplier_id', '供应商 ID'),
      text('supplier_name', '供应商名称'),
      number('procurement_count', '采购次数'),
      number('procurement_amount', '采购金额'),
      number('avg_delivery_days', '平均交付天数'),
      date('last_procurement_at', '最近采购时间'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'ask_data_supplier_quote_terms_view',
    label: '供应商报价与商业条款',
    domain: 'supply',
    description: '门店商品对应的已审批供应商报价、最低采购量、账期、交期和同商品价格比较。',
    keywords: ['供应商报价', '最近报价', '报价比较', '供应商价格', '最低采购量', 'MOQ', '账期', '结算方式', '交期', '更低报价'],
    dataPolicy: '仅展示当前门店商品映射的 active + approved 报价；报价不等于最终采购成交价，最低报价不代表质量或综合性价比最好。',
    noDataHint: '当前门店尚无已审批并映射到商品的供应商报价。',
    freshnessField: 'data_as_of',
    requiredPermissions: ['core:supply:view'],
    storeScopeField: 'store_id',
    defaultTimeField: 'quote_created_at',
    requiresTimeScope: false,
    fields: [
      ...base,
      number('product_id', '商品 ID'),
      text('product_name', '商品名称'),
      text('product_sku', '门店商品 SKU'),
      text('category_name', '商品分类'),
      text('product_unit', '门店商品单位'),
      number('supply_sku_id', '供应链 SKU ID'),
      text('supply_sku_name', '供应链 SKU 名称'),
      text('brand', '品牌'),
      text('spec', '规格'),
      text('supply_unit', '供应链报价单位'),
      number('supplier_id', '供应商 ID'),
      text('supplier_name', '供应商名称'),
      text('settlement_mode', '结算方式'),
      text('payment_terms', '账期条款；空值表示后台未维护'),
      number('quote_id', '报价 ID'),
      number('quote_price', '已审批报价；不等于最终采购成交价'),
      boolean('tax_included', '报价是否含税'),
      number('minimum_order_quantity', '最低采购量 MOQ'),
      number('lead_days', '预计交付天数；空值表示后台未维护'),
      text('stock_status', '供应商库存状态'),
      number('available_stock', '供应商可用库存；空值表示后台未维护'),
      date('valid_from', '报价有效期开始'),
      date('valid_to', '报价有效期结束'),
      date('quote_created_at', '报价创建时间'),
      date('quote_updated_at', '报价更新时间'),
      boolean('is_preferred_supplier', '是否为当前门店首选供应商映射'),
      boolean('is_current_valid', '当前是否在报价有效期内'),
      number('alternative_supplier_count', '同商品其他当前有效供应商数量'),
      number('lowest_current_quote_price', '同商品当前最低已审批报价'),
      number('price_difference_from_lowest', '当前报价与同商品最低报价的差额'),
      number('price_premium_rate', '当前报价相对同商品最低报价的溢价率'),
      number('current_price_rank', '同商品当前有效报价价格排名，1 为最低'),
      date('data_as_of', '数据口径时间'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'ask_data_confirmed_profit_view',
    label: '已确认实际利润',
    domain: 'finance',
    description: '已确认月结中的营业收入、完整成本、毛利和经营利润。',
    keywords: ['实际利润', '经营利润', '毛利', '利润率', '月结利润'],
    dataPolicy: '每月仅使用最新 confirmed 版本，不读取 draft 或 reopened 快照。',
    noDataHint: '该期间尚无已确认利润快照，请先在经营利润模块完成月结确认。',
    freshnessField: 'confirmed_at',
    requiredPermissions: ['core:operation-profit:view'],
    storeScopeField: 'store_id',
    defaultTimeField: 'period_month',
    fields: [
      ...base,
      date('period_month', '所属月份'),
      number('version', '快照版本'),
      number('operating_revenue', '营业收入'),
      number('material_cost', '材料成本'),
      number('product_cost', '商品成本'),
      number('commission_cost', '提成成本'),
      number('operating_cost', '经营成本'),
      number('gross_profit', '毛利'),
      number('operating_profit', '经营利润'),
      number('gross_margin_rate', '毛利率'),
      number('operating_margin_rate', '经营利润率'),
      date('confirmed_at', '确认时间'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'ask_data_reconciliation_issue_view',
    label: '财务对账异常',
    domain: 'finance',
    description: '日结对账运行及异常类别、严重度、金额和处理状态。',
    keywords: ['对账', '对账异常', '财务异常', '差异', '未处理异常'],
    dataPolicy: '不开放错误堆栈、异常内部详情和处理备注。',
    freshnessField: 'last_detected_at',
    requiredPermissions: ['core:finance:view'],
    storeScopeField: 'store_id',
    defaultTimeField: 'business_date',
    fields: [
      ...base,
      number('issue_id', '异常 ID'),
      number('run_id', '对账运行 ID；同一运行的异常使用相同 run_id'),
      date('business_date', '业务日期'),
      text('run_status', '运行状态'),
      text('category', '异常类别'),
      text('severity', '严重度'),
      text('issue_status', '处理状态'),
      text('title', '异常标题'),
      number('amount', '异常金额'),
      date('first_detected_at', '首次发现时间'),
      date('last_detected_at', '最近发现时间'),
      date('resolved_at', '解决时间'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'ask_data_member_liability_view',
    label: '会员履约负债',
    domain: 'finance',
    description: '已确认会员负债快照中的储值、赠送和次卡履约义务。',
    keywords: ['会员负债', '履约负债', '合同负债', '次卡负债', '储值负债'],
    dataPolicy: '每个快照日仅使用最新 confirmed 版本，不读取 draft。',
    noDataHint: '当前尚无已确认会员负债快照，请先在会员资产模块完成快照确认。',
    freshnessField: 'confirmed_at',
    requiredPermissions: ['core:prepaid-liability:view'],
    storeScopeField: 'store_id',
    defaultTimeField: 'snapshot_date',
    fields: [
      ...base,
      date('snapshot_date', '快照日期'),
      number('version', '快照版本'),
      number('cash_contract_liability', '现金合同负债'),
      number('gift_obligation', '赠送义务'),
      number('card_liability', '次卡负债'),
      number('total_liability', '负债合计'),
      number('remaining_times', '剩余次数'),
      number('additions', '本期增加'),
      number('releases', '本期释放'),
      number('refunds', '退款减少'),
      number('expirations', '过期减少'),
      number('adjustments', '调整金额'),
      date('confirmed_at', '确认时间'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'ask_data_staff_capacity_view',
    label: '排班与员工产能',
    domain: 'staff',
    description: '按员工和日期计算排班、预约、空闲、超排和工时利用率。',
    keywords: ['排班产能', '员工产能', '工时利用率', '空闲时间', '超排', '预约分钟'],
    dataPolicy: '取消预约不计预约分钟；缺少结束时间时使用项目时长，仍缺失则按 60 分钟。',
    requiredPermissions: ['core:store:scheduling'],
    storeScopeField: 'store_id',
    defaultTimeField: 'work_date',
    fields: [
      ...base,
      number('staff_id', '员工 ID'),
      text('staff_name', '员工姓名'),
      date('work_date', '日期'),
      number('scheduled_minutes', '排班分钟'),
      number('leave_minutes', '请假分钟'),
      number('booked_minutes', '预约分钟'),
      number('idle_minutes', '空闲分钟'),
      number('overbooked_minutes', '超排分钟'),
      number('utilization_rate', '工时利用率'),
      number('reservation_count', '有效预约数'),
      number('completed_count', '完成预约数'),
      number('cancelled_count', '取消预约数'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'ask_data_transfer_status_view',
    label: '库存调拨',
    domain: 'inventory',
    description: '当前门店作为发出方或接收方的库存调拨状态。',
    keywords: ['调拨', '调入', '调出', '调拨单', '跨店库存'],
    dataPolicy: '每张调拨单按当前门店生成 inbound 或 outbound 视角，不开放 items JSON。',
    requiredPermissions: ['core:inventory:transfer'],
    storeScopeField: 'store_id',
    defaultTimeField: 'created_at',
    fields: [
      ...base,
      number('transfer_id', '调拨单 ID'),
      text('transfer_no', '调拨单号'),
      text('direction', '方向：inbound 或 outbound'),
      number('counterpart_store_id', '对方门店 ID'),
      text('counterpart_store_name', '对方门店名称'),
      number('product_count', '商品数'),
      text('status', '调拨状态：pending 为待处理；completed、received、done 均视为已完成'),
      date('created_at', '创建时间'),
      date('updated_at', '更新时间'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'ask_data_bom_consumption_variance_view',
    label: 'BOM 实际消耗偏差',
    domain: 'inventory',
    description: '服务实际耗材与项目 BOM 标准耗材的数量偏差。',
    keywords: ['BOM', '耗材偏差', '实际消耗', '标准用量', '异常消耗'],
    dataPolicy: '标准用量为单次 BOM 用量乘服务次数；绝对偏差率超过 20% 标记异常。',
    noDataHint: '当前没有可关联的服务消耗流水，或消耗流水尚未关联项目和 BOM。',
    requiredPermissions: ['core:inventory:consumption'],
    storeScopeField: 'store_id',
    defaultTimeField: 'occurred_at',
    fields: [
      ...base,
      number('movement_id', '库存流水 ID'),
      date('occurred_at', '发生时间'),
      number('project_id', '项目 ID'),
      text('project_name', '项目名称'),
      number('product_id', '商品 ID'),
      text('product_name', '商品名称'),
      text('sku', 'SKU'),
      number('service_times', '服务次数'),
      number('standard_qty', '标准用量'),
      number('actual_qty', '实际用量'),
      number('deviation_qty', '用量偏差'),
      number('deviation_rate', '偏差率'),
      boolean('is_abnormal', '是否异常'),
      text('standard_status', '标准关联状态'),
      text('source_type', '来源类型'),
      number('source_id', '来源 ID'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'ask_data_customer_feedback_view',
    label: '客户反馈',
    domain: 'customer',
    description: '客户反馈类型、评分、分类、严重度和处理状态。',
    keywords: ['客户反馈', '投诉', '满意度', '低评分', '表扬', '建议'],
    dataPolicy: '客户姓名脱敏；禁止反馈原文、处理备注和手机号。',
    noDataHint: '当前门店尚未沉淀客户反馈记录。',
    freshnessField: 'occurred_at',
    requiredPermissions: ['core:customer:view'],
    storeScopeField: 'store_id',
    defaultTimeField: 'occurred_at',
    fields: [
      ...base,
      number('feedback_id', '反馈 ID'),
      number('customer_id', '客户 ID'),
      text('customer_name_masked', '脱敏客户姓名', 'mask'),
      number('staff_id', '员工 ID'),
      text('staff_name', '员工姓名'),
      number('project_id', '项目 ID'),
      text('project_name', '项目名称'),
      text('feedback_type', '反馈类型：complaint 投诉、satisfaction 满意度、suggestion 建议、praise 表扬'),
      number('rating', '评分（1—5 分）；低评分口径为 rating <= 2'),
      text('category', '反馈分类'),
      text('severity', '严重度：normal、warning、critical'),
      text('status', '处理状态：open、in_progress、resolved、closed；前两项视为未解决'),
      date('occurred_at', '发生时间'),
      date('handled_at', '处理时间'),
      date('resolved_at', '解决时间'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'ask_data_customer_lifecycle_view',
    label: '客户生命周期',
    domain: 'customer',
    description: '客户生命周期阶段、价值档位、流失风险和最高优先级机会。',
    keywords: ['客户生命周期', '生命周期阶段', '流失风险', 'LTV', '客户机会', '触达疲劳'],
    dataPolicy: '每位客户一行；姓名脱敏，不开放推荐权益、渠道和证据 JSON。',
    freshnessField: 'computed_at',
    requiredPermissions: ['core:customer:view'],
    storeScopeField: 'store_id',
    defaultTimeField: 'computed_at',
    requiresTimeScope: false,
    fields: [
      ...base,
      number('customer_id', '客户 ID'),
      text('customer_name_masked', '脱敏客户姓名', 'mask'),
      text('lifecycle_stage', '生命周期阶段'),
      text('ltv_tier', 'LTV 档位'),
      text('churn_risk_level', '流失风险等级'),
      number('touch_fatigue_score', '触达疲劳度'),
      date('computed_at', '计算时间'),
      number('open_opportunity_count', '未关闭机会数'),
      text('top_opportunity_type', '最高优先级机会类型'),
      text('top_priority', '最高优先级'),
      number('top_score', '机会评分'),
      date('opportunity_expires_at', '机会到期时间'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'ask_data_marketing_roi_view',
    label: '营销 ROI',
    domain: 'marketing',
    description: '按日期、策略和渠道汇总触达、转化、归因净收入、成本和 ROI。',
    keywords: ['营销 ROI', '投产', '投入产出', '营销成本', '归因收入', '渠道效果'],
    dataPolicy: '退款冲减归因收入；成本为零时 ROI 为空；estimated 成本不代表实际渠道账单。',
    freshnessField: 'latest_event_at',
    requiredPermissions: ['core:marketing:analytics'],
    storeScopeField: 'store_id',
    defaultTimeField: 'effect_date',
    fields: [
      ...base,
      date('effect_date', '效果日期'),
      number('activity_id', '活动 ID'),
      text('activity_title', '活动名称'),
      number('promotion_id', '优惠 ID'),
      text('promotion_name', '优惠名称'),
      number('strategy_id', '策略 ID'),
      text('strategy_name', '策略名称'),
      text('channel', '渠道'),
      number('exposure_count', '触达数'),
      number('click_count', '点击数'),
      number('conversion_count', '转化数'),
      number('attributed_net_revenue', '归因净收入'),
      number('marketing_cost', '营销成本'),
      number('conversion_rate', '转化率'),
      number('roi', '投入产出比'),
      text('cost_source', '成本来源'),
      date('latest_event_at', '最近效果时间'),
    ],
    allowJoin: false,
  },
];

export const ASK_DATA_FREE_SQL_EXAMPLES = [
  '本月哪个项目收入最高？',
  '本月有哪些严重对账异常？',
  '未来7天哪些员工空闲时间最多？',
  '最近30天哪些项目耗材偏差超过20%？',
  '当前高流失风险客户有哪些？',
  '最近30天哪些营销策略 ROI 最高？',
];
