import type { ReadOnlySqlField, ReadOnlySqlView } from '../read-only-sql-kernel/read-only-sql-kernel.types.js';

const text = (name: string, description: string, policy: ReadOnlySqlField['policy'] = 'allow'): ReadOnlySqlField => ({
  name,
  type: 'string',
  description,
  policy,
});
const number = (name: string, description: string, policy: ReadOnlySqlField['policy'] = 'allow'): ReadOnlySqlField => ({
  name,
  type: 'number',
  description,
  policy,
});
const date = (name: string, description: string, policy: ReadOnlySqlField['policy'] = 'allow'): ReadOnlySqlField => ({
  name,
  type: 'date',
  description,
  policy,
});

const base = [number('store_id', '授权门店 ID'), text('store_name', '门店名称')];

export const ASK_DATA_FREE_SQL_VIEWS: ReadOnlySqlView[] = [
  {
    viewName: 'agent_v3_order_summary_view',
    label: '订单摘要',
    domain: 'order',
    description: '订单、成交、实收、退款和净收摘要。',
    requiredPermissions: ['core:finance:view'],
    storeScopeField: 'store_id',
    defaultTimeField: 'order_created_at',
    fields: [
      ...base,
      number('order_id', '订单 ID'),
      date('order_created_at', '下单时间'),
      number('customer_id', '客户 ID'),
      text('customer_name_masked', '脱敏客户姓名', 'mask'),
      text('order_status', '订单状态'),
      number('total_amount', '订单总额'),
      number('paid_amount', '实收金额'),
      number('refund_amount', '退款金额'),
      number('net_amount', '净收金额'),
      text('pay_method', '支付方式'),
    ],
    allowJoin: true,
  },
  {
    viewName: 'agent_v3_order_item_sales_view',
    label: '商品销售',
    domain: 'product',
    description: '商品销售明细、销量排行和销售额排行。',
    requiredPermissions: ['core:order:products', 'core:goods:products'],
    storeScopeField: 'store_id',
    defaultTimeField: 'order_created_at',
    fields: [
      ...base,
      number('order_id', '订单 ID'),
      date('order_created_at', '订单时间'),
      number('product_id', '商品 ID'),
      text('product_name', '商品名称'),
      text('sku', 'SKU'),
      text('category_name', '商品分类'),
      number('quantity', '销售数量'),
      number('gross_amount', '销售原额'),
      number('discount_amount', '优惠金额'),
      number('net_amount', '净销售额'),
      number('refund_amount', '退款金额'),
      text('order_status', '订单状态'),
    ],
    allowJoin: true,
  },
  {
    viewName: 'agent_v3_project_service_sales_view',
    label: '项目服务销售',
    domain: 'project',
    description: '项目服务次数、项目销售额和预估毛利。',
    requiredPermissions: ['core:order:projects', 'core:store:projects'],
    storeScopeField: 'store_id',
    defaultTimeField: 'order_created_at',
    fields: [
      ...base,
      number('project_id', '项目 ID'),
      text('project_name', '项目名称'),
      text('project_type', '项目分类'),
      date('order_created_at', '订单时间'),
      number('service_quantity', '服务次数'),
      number('net_amount', '项目净销售额'),
      number('estimated_material_cost', '预估耗材成本'),
      number('estimated_margin', '预估毛利'),
    ],
    allowJoin: true,
  },
  {
    viewName: 'agent_v3_payment_refund_view',
    label: '支付与退款',
    domain: 'finance',
    description: '支付、退款和售后退款摘要。',
    requiredPermissions: ['core:finance:view'],
    storeScopeField: 'store_id',
    defaultTimeField: 'paid_at',
    fields: [
      ...base,
      number('order_id', '订单 ID'),
      date('paid_at', '支付时间'),
      date('refunded_at', '退款时间'),
      text('payment_method', '支付方式'),
      number('payment_amount', '支付金额'),
      number('refund_amount', '退款金额'),
      text('payment_status', '支付状态'),
      text('refund_status', '退款状态'),
      text('refund_reason_category', '退款原因分类'),
    ],
    allowJoin: true,
  },
  {
    viewName: 'agent_v3_daily_settlement_view',
    label: '日结',
    domain: 'finance',
    description: '日收入、退款、净收、订单数和客户数。',
    requiredPermissions: ['core:finance:view'],
    storeScopeField: 'store_id',
    defaultTimeField: 'settlement_date',
    fields: [
      ...base,
      date('settlement_date', '结算日期'),
      number('revenue_amount', '收入'),
      number('paid_amount', '实收'),
      number('refund_amount', '退款'),
      number('net_amount', '净收'),
      number('order_count', '订单数'),
      number('customer_count', '客户数'),
    ],
    allowJoin: true,
  },
  {
    viewName: 'agent_v3_product_inventory_view',
    label: '商品库存',
    domain: 'inventory',
    description: '商品当前库存、安全库存、库存金额和最近效期。',
    requiredPermissions: ['core:inventory:products', 'core:inventory:stock'],
    storeScopeField: 'store_id',
    requiresTimeScope: false,
    fields: [
      ...base,
      number('product_id', '商品 ID'),
      text('product_name', '商品名称'),
      text('sku', 'SKU'),
      text('unit', '单位'),
      number('current_stock', '当前库存'),
      number('safety_stock', '安全库存'),
      number('stock_value', '库存金额'),
      text('status', '库存状态'),
      date('nearest_expiry_date', '最近效期'),
    ],
    allowJoin: true,
  },
  {
    viewName: 'agent_v3_stock_movement_view',
    label: '库存流水',
    domain: 'inventory',
    description: '入库、出库、盘点和库存变化流水。',
    requiredPermissions: ['core:inventory:stock', 'core:inventory:consumption'],
    storeScopeField: 'store_id',
    defaultTimeField: 'occurred_at',
    fields: [
      ...base,
      number('movement_id', '流水 ID'),
      number('product_id', '商品 ID'),
      text('product_name', '商品名称'),
      text('sku', 'SKU'),
      text(
        'movement_type',
        '流水类型；常见出库包括 sale_out、service_consume、service_consumption、scrap_out、transfer_out、manual_outbound',
      ),
      number('quantity', '库存变化量；出库为负数，统计出库数量使用 ABS(quantity) 并筛选 quantity < 0'),
      number('before_stock', '变更前库存'),
      number('after_stock', '变更后库存'),
      text('source_type', '来源类型'),
      date('occurred_at', '发生时间'),
    ],
    allowJoin: true,
  },
  {
    viewName: 'agent_v3_inventory_scrap_view',
    label: '库存报废',
    domain: 'inventory',
    description: '报废数量、损耗金额和操作摘要。',
    requiredPermissions: ['core:inventory:consumption'],
    storeScopeField: 'store_id',
    defaultTimeField: 'occurred_at',
    fields: [
      ...base,
      number('movement_id', '流水 ID'),
      number('product_id', '商品 ID'),
      text('product_name', '商品名称'),
      text('sku', 'SKU'),
      number('scrap_quantity', '报废数量'),
      number('loss_amount', '损耗金额'),
      date('occurred_at', '发生时间'),
      text('operator_name', '操作人'),
      text('remark_summary', '备注摘要'),
    ],
    allowJoin: true,
  },
  {
    viewName: 'agent_v3_customer_profile_summary_view',
    label: '客户档案摘要',
    domain: 'customer',
    description: '客户等级、最近到店和消费摘要。',
    requiredPermissions: ['core:customer:view'],
    storeScopeField: 'store_id',
    requiresTimeScope: false,
    fields: [
      ...base,
      number('customer_id', '客户 ID'),
      text('customer_name_masked', '脱敏客户姓名', 'mask'),
      text('phone_last4', '手机号后四位', 'mask'),
      text('member_level', '会员等级'),
      date('last_visit_at', '最近到店时间'),
      date('last_order_at', '最近消费时间'),
      number('total_paid_amount', '累计实收'),
      number('order_count', '订单数'),
      text('tags_summary', '标签摘要'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'agent_v3_staff_profile_view',
    label: '员工档案',
    domain: 'staff',
    description: '美容师和员工基础资料。',
    requiredPermissions: ['core:store:beauticians'],
    storeScopeField: 'store_id',
    requiresTimeScope: false,
    fields: [
      ...base,
      number('staff_id', '员工 ID'),
      text('staff_name', '员工姓名'),
      text('level_name', '级别'),
      text('status', '员工状态；active 表示在职，inactive 表示停用'),
      date('created_at', '创建时间'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'agent_v3_staff_performance_view',
    label: '员工绩效',
    domain: 'staff',
    description: '员工人效、提成、服务量和客单价摘要。',
    requiredPermissions: ['core:beautician-performance:view'],
    storeScopeField: 'store_id',
    defaultTimeField: 'settle_month',
    fields: [
      ...base,
      number('staff_id', '员工 ID'),
      text('staff_name', '员工姓名'),
      date('settle_month', '结算月份'),
      number('paid_amount', '业绩金额'),
      number('average_order_amount', '平均客单价'),
      number('commission_amount', '提成金额'),
      number('service_count', '服务量'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'agent_v3_reservation_view',
    label: '预约',
    domain: 'reservation',
    description: '预约记录、项目、美容师和预约状态。',
    requiredPermissions: ['core:store:reservations'],
    storeScopeField: 'store_id',
    defaultTimeField: 'date',
    fields: [
      ...base,
      number('reservation_id', '预约 ID'),
      number('customer_id', '客户 ID'),
      text('customer_name_masked', '脱敏客户姓名', 'mask'),
      number('project_id', '项目 ID'),
      text('project_name', '项目名称'),
      number('beautician_id', '美容师 ID'),
      text('beautician_name', '美容师名称'),
      date('date', '预约日期'),
      text('start_time', '开始时间'),
      text('status', '预约状态：pending、confirmed、checked_in、completed、cancelled；取消率分子为 cancelled'),
    ],
    allowJoin: false,
  },
  {
    viewName: 'agent_v3_marketing_conversion_view',
    label: '营销转化',
    domain: 'marketing',
    description: '营销活动事件、线索、转化和归因收入。',
    requiredPermissions: ['core:marketing:analytics'],
    storeScopeField: 'store_id',
    defaultTimeField: 'latest_event_at',
    fields: [
      ...base,
      number('activity_id', '活动 ID'),
      text('activity_title', '活动名称'),
      number('event_count', '触达事件数'),
      number('lead_count', '线索数'),
      number('conversion_count', '转化数'),
      number('attributed_revenue', '归因收入'),
      date('latest_event_at', '最近事件时间'),
    ],
    allowJoin: false,
  },
];

export const ASK_DATA_FREE_SQL_EXAMPLES = [
  '本月哪个项目收入最高？',
  '最近30天销量最高的商品有哪些？',
  '本月退款金额按支付方式怎么分布？',
  '当前低于安全库存的商品有哪些？',
  '本月预约取消率是多少？',
  '最近三个月员工服务业绩排行？',
];
